airbnb/visx

- lerna.json
- packages/vx-brush/.babelrc
- packages/vx-brush/Makefile
- packages/vx-brush/package.json
- packages/vx-brush/src/brushes/BoxBrush.js
- packages/vx-brush/src/enhancers/withBrush.js
- packages/vx-brush/src/index.js
- packages/vx-brush/src/utils/constrainToRegion.js
- packages/vx-brush/src/utils/getCoordsFromEvent.js
- packages/vx-demo/components/charts/BrushChart.js
- packages/vx-demo/components/meta.js
- packages/vx-demo/package.json
Simple code sketch to wrap my head around the problem space. Will figure out a better api for adding this interaction. Likely an HOC + component combo. We shall see.
> [brush] sketch of brush and zoom code

- README.md
Forgive me if this the wrong place to put this. 
If we have a really basic example of how to use VX, it might make it a little easier for new folks to get started using it.
I took the SimpleBar chart in the gallery and stripped it down of everything I could so it would be simple enough to just glance over without causing too much information overload.
> Add basic usage to README

- packages/vx-point/Readme.md
I can combine more things into one pull request if you would like. I wanted to make sure that this was the right sort of style that you wanted for docs. Let me know if there's anything I can do to make it better. ❤️
> Add docs for `@vx/point`. Issue #9

- packages/vx-shape/Readme.md
> Add Shape docs

- packages/vx-gradient/Readme.md
- packages/vx-marker/Readme.md
- packages/vx-mock-data/Readme.md
- packages/vx-pattern/Readme.md
- packages/vx-text/Readme.md
> Add Marker, Mock-data, and Text Docs 

- README.md
Congrats on the passing license scan!  Here's an additional report if you're interested.
> Add license report

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/meta.js
- packages/vx-demo/components/page.js
- packages/vx-demo/components/tiles/area.js
- packages/vx-demo/components/tiles/heatmap.js
- packages/vx-demo/components/tiles/lineradial.js
- packages/vx-demo/pages/arcs.js
- packages/vx-demo/pages/heatmaps.js
- packages/vx-demo/pages/lineradial.js
- packages/vx-heatmap/src/heatmaps/circle.js
- packages/vx-heatmap/src/heatmaps/rect.js
- packages/vx-heatmap/src/util/additionalProps.js
- packages/vx-heatmap/src/util/callOrValue.js
- packages/vx-shape/build/index.js
- packages/vx-shape/src/index.js
- packages/vx-shape/src/shapes/Arc.js
- packages/vx-shape/src/shapes/LineRadial.js
- packages/vx-shape/test/LineRadial.test.js
> [shape] add <LineRadial />

- packages/vx-pattern/src/patterns/Circles.js
- packages/vx-pattern/test/PatternCircles.test.js
- Moves the embedded anonymous function that created circles into it's own separate function so that it can be easily tested. 
- Added tests for createCircles
- Ran tests.
- Ran Demo to prove that everything still looks fine visually: 
(Still looks normal)
> [pattern] Add tests for pattern circles

- packages/vx-annotation/package.json
- packages/vx-axis/package.json
- packages/vx-brush/package.json
- packages/vx-clip-path/package.json
- packages/vx-drag/package.json
- packages/vx-glyph/package.json
- packages/vx-gradient/package.json
- packages/vx-grid/package.json
- packages/vx-group/package.json
- packages/vx-heatmap/package.json
- packages/vx-hierarchy/package.json
- packages/vx-marker/package.json
- packages/vx-pattern/package.json
- packages/vx-responsive/package.json
- packages/vx-shape/package.json
- packages/vx-text/package.json
> [vx] move react to peerDeps + devDeps

- packages/vx-glyph/src/glyphs/Cross.js
Now CrossSymbol should work fine.
> fix the bug in crossSymbol so it can be rendered

- packages/vx-shape/test/BarStack.test.js
Update xScale mock fns, forgot to do this in https://github.com/hshoff/vx/pull/87
> [shape] fix barstack.test.js

- packages/vx-shape/src/shapes/AreaClosed.js
In reference to [this comment](https://github.com/hshoff/vx/pull/95). 
Since this was essentially already CR'd I'm just gonna merge this after a day or so if no one has any issues with it.
> Double Quotes to Single Quotes

- packages/vx-shape/src/shapes/Arc.js
- packages/vx-shape/src/shapes/AreaClosed.js
- packages/vx-shape/src/shapes/AreaStack.js
- packages/vx-shape/src/shapes/LinePath.js
fixes: https://github.com/hshoff/vx/issues/100
> [shape] LinePath.defined should default to true

- packages/vx-demo/components/tiles/area.js
- packages/vx-demo/package.json
- packages/vx-demo/pages/arcs.js
- packages/vx-grid/src/grids/Columns.js
- packages/vx-grid/src/grids/Grid.js
- packages/vx-grid/src/grids/Rows.js
- packages/vx-shape/src/shapes/AreaClosed.js
also adds:
- [grid] add styles and restProps support for grid lines
> [shape] add x-value mouseover to area demo

- packages/vx-demo/pages/arcs.js
- packages/vx-demo/pages/areas.js
> [demo] areas == areas, areas != arcs

- packages/vx-demo/package.json
> [demo] use @vx/geo version in deps

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/tiles/geo-mercator.js
- packages/vx-demo/components/tiles/network.js
Minor polish on the `@vx/network` (Graph component) and `@vx/geo` (add graticules) tiles.
> [demo] updated geo + network tiles

- packages/vx-event/src/touchPoint.js
Made for mobile use event. : )
> add_touchPoint

- lerna.json
- package.json
> [pkg] bump lerna 2.0.0-beta.38 => 2.1.2

- package.json
- packages/vx-hierarchy/src/HierarchyDefaultLink.js
- packages/vx-hierarchy/src/HierarchyDefaultNode.js
- packages/vx-hierarchy/src/hierarchies/Cluster.js
- packages/vx-hierarchy/src/hierarchies/Tree.js
- packages/vx-hierarchy/src/index.js
- packages/vx-hierarchy/test/Defaults.test.js
> [hierarchy] fix name collisions

- packages/vx-legend/src/legends/Legend.js
- packages/vx-legend/test/Legend.test.js
Fix for #150 and adds some tests. thanks for catching this @blaze33!
> [legend] fix legend style prop, add tests. fixes #150

- README.md
Thanks to @dylanmoz for the great tutorial! 
Demo: http://dylanmoz.github.io/trello/
Tutorial: https://devblog.classy.org/how-to-make-beautiful-graphs-with-vx-and-react-motion-6ffe7aecf6f3
> [readme] add dylanmoz react-motion + vx tutorial

- packages/vx-shape/src/util/stackOrder.js
> Typo in stack order enum

- README.md
- 
-
- added a demo of my app. Using vx was a blast. Specifically used stack, heatmap, and tooltip for data visualization. Please let me know what you think. Any feedback would be greatly appreciated. You all are awesome.
- 
-
> added a demo of my app

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/tiles/barstackhorizontal.js
- packages/vx-demo/pages/barstackhorizontal.js
- packages/vx-shape/build/index.js
- packages/vx-shape/src/index.js
- packages/vx-shape/src/shapes/BarStackHorizontal.js
- packages/vx-shape/test/BarStackHorizontal.test.js
[demo] Added BarStackHorizontal tile and page
- Added Shape.BarStackHorizontal
- Added BarStackHorizontal example
> [shape] Added BarStackHorizontal

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/tiles/responsive.js
- packages/vx-responsive/package.json
fixes: https://github.com/hshoff/vx/issues/202 no more melting https://vx-demo.now.sh/gallery 
- [responsive] bump `resize-observer-polyfill`
- [demo] add overflow hidden on flex: 1 `<ParentSize />` parents
> [responsive][demo] bump resize-observer-polyfill, fix ff

- packages/vx-text/package.json
- Update `vx-text` author to attribute myself 😄
> Update author for vx-text

- packages/vx-responsive/Readme.md
- 
-
- Backticks import not working so, copy paste , broken :)
- 
-
> Remove Backticks

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/show.js
- packages/vx-demo/pages/text.js
- [demo] add vx-text tile and update `/text` demo
@techniq
> [demo] add vx-text tile and update demo page

- packages/vx-responsive/Readme.md
I separated the documentation with a section for every enhancer and component. 
Enhancers' description have been improved by describing which props will the component get.
Added description and usage example of `ParentSize` previously missing.
> Added description and example of each component and enhancer

- packages/vx-text/src/util/getStringWidth.js
- [text] Remove default width and height from measurement SVG.  Fixes #218
> [text] Remove default width and height from measurement SVG.  Fixes #218

- packages/vx-demo/components/tiles/legends.js
- packages/vx-demo/pages/legends.js
- packages/vx-legend/src/legends/Legend.js
- packages/vx-legend/src/legends/LegendItem.js
- packages/vx-legend/src/util/additionalProps.js
- packages/vx-legend/src/util/callOrValue.js
- packages/vx-legend/test/Legend.test.js
fixes #209
- [legend] make legend items clickable, add `<LegendItem />` propTypes, add click test
> [legend] make legend items clickable. fixes #209

- packages/vx-demo/package.json
> [demo] add @vx/drag dep

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/tiles/linkTypes.js
- packages/vx-demo/pages/linkTypes.js
- Add `<Shape.Link*>` examples to gallery
> Add <Shape.Link*> examples to gallery

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/show.js
- packages/vx-demo/components/tiles/threshold.js
- packages/vx-demo/package.json
- packages/vx-demo/pages/threshold.js
- packages/vx-shape/src/shapes/Area.js
- packages/vx-threshold/.babelrc
- packages/vx-threshold/.npmrc
- packages/vx-threshold/Makefile
- packages/vx-threshold/Readme.md
- packages/vx-threshold/package.json
- packages/vx-threshold/src/Threshold.js
- packages/vx-threshold/src/index.js
- packages/vx-threshold/test/Threshold.test.js
- packages/vx-threshold/test/enzyme-setup.js
- [threshold] add `<Threshold />`. fixes https://github.com/hshoff/vx/issues/245 
- [demo] add /threshold demo
> [threshold] add @vx/threshold. fixes #245

- packages/vx-heatmap/package.json
- packages/vx-heatmap/src/heatmaps/circle.js
- packages/vx-heatmap/src/heatmaps/rect.js
- [shape] add index + yBin to heatmap circle/rect
fixes #302
> [shape] add index + yBin to heatmap circle/rect. fixes #302

- packages/vx-legend/src/shapes/Rect.js
> [legend] spread style prop. fixes #312

- packages/vx-stats/Readme.md
- [stats] update `@vx/stats` readme name to stats
> [stats] update readme name to stats. fixes #323

- packages/vx-network/Readme.md
- [network] remove unrelated docs from readme. fixes https://github.com/hshoff/vx/issues/326
> [network] remove unrelated docs from readme. fixes #326

- packages/vx-text/src/Text.js
- [text] add innerRef prop
fixes #338
> [text] add innerRef prop. fixes #338

- packages/vx-demo/pages/heatmaps.js
- [demo] update heatmap example code to match new api
> [demo] update heatmap example code

- packages/vx-threshold/src/Threshold.js
- [threshold] add id prop for unique clip-path ids
fixes: #341
> [threshold] add id prop for unique clip-path ids

- packages/vx-demo/components/tiles/polygons.js
- packages/vx-shape/Readme.md
- packages/vx-shape/src/shapes/Polygon.js
- [shape] fix for `<Polygon />` rest props
> [shape] fix <Polygon /> rest props

- packages/vx-responsive/src/components/ParentSize.js
- Nothing
- Needed if used in flex layouts where 100% size breaks the layout.
> Add rest props to internal div

- package.json
> [vx] fix lint command

- README.md
- Added a new demo of a project using vx components
> Added new demo of Ethereum Portfolio Toolkit

- packages/vx-demo/static/docs/vx-responsive.html
- packages/vx-responsive/Readme.md
- packages/vx-responsive/docs/api.md
- packages/vx-responsive/docs/docs.md
- [responsive][docs] add innerRef prop docs
related: https://github.com/hshoff/vx/pull/393
> [responsive][docs] add innerRef prop docs

- packages/vx-demo/components/tiles/threshold.js
- packages/vx-demo/static/docs/vx-threshold.html
- packages/vx-threshold/Readme.md
- packages/vx-threshold/docs/api.md
- packages/vx-threshold/docs/docs.md
- packages/vx-threshold/src/Threshold.js
- [threshold][docs] update `clipAboveTo` and `clipBelowTo` prop types to `number|func`
> Harry threshold docs

- packages/vx-demo/components/gallery.js
- packages/vx-demo/components/tiles/geo-custom.js
- packages/vx-demo/components/tiles/geo-mercator.js
- packages/vx-demo/package.json
- packages/vx-demo/pages/geo-custom.js
- packages/vx-geo/src/index.js
- packages/vx-geo/src/projections/CustomProjection.js
- packages/vx-geo/src/projections/Projection.js
fixes #433
- [geo] add `<CustomProjection projection={someProjectionFunction} />`
- [demo] add `<CustomProjection />` tile
> [geo] add <CustomProjection /> fixes #433

- packages/vx-geo/test/CustomProjection.test.js
Forgot to push a commit. 🤦‍♂️ 
- [geo] add `<CustomProjection />` test
> [geo] add CustomProjection test

- packages/vx-scale/src/index.js
- packages/vx-scale/src/scales/symlog.js
- packages/vx-scale/test/scaleSymlog.test.js
Add scaleSymlog 
#426 
https://github.com/d3/d3-scale#symlog-scales
> Add scale Symlog

- packages/vx-demo/static/docs/vx-group.html
- packages/vx-group/Readme.md
- packages/vx-group/docs/api.md
- packages/vx-group/docs/docs.md
- packages/vx-group/src/Group.js
fixes: https://github.com/hshoff/vx/issues/479
- [group] add innerRef prop
- [docs][group] add innerRef prop
> [group] add innerRef prop. fixes #479

- .npmignore
> [root] ignore .next

- packages/vx-mock-data/Readme.md
> Fix broken links in vx-mock-data readme

- packages/vx-scale/Readme.md
> docs: fix broken link

- packages/vx-scale/Readme.md
- packages/vx-scale/src/index.ts
- packages/vx-scale/src/scales/squareRoot.ts
- packages/vx-scale/test/scaleSqrt.test.ts
- Add `scaleSqrt`
- Add `scaleSqrt` documentation
Fixes https://github.com/hshoff/vx/issues/604
> new(vx-scale) add scaleSqrt

- README.md
> Edit in 'Goal' section, under 'Motivation'

- README.md
- packages/vx-brush/src/Brush.tsx
- packages/vx-demo/src/components/tiles/Brush.tsx
- packages/vx-demo/src/pages/Brush.tsx
-
-
- update the development section in README after trying to develop in local machine. There is only one file changing, based on the #634 branch.
-
-
> docs: Update the development section in README

- README.md
> feat(README): another project in the wild showcasing vx

- packages/vx-responsive/src/components/ParentSize.tsx
Follow up to https://github.com/hshoff/vx/pull/763 this fixes the build by making prettier happy.
- fix(vx-responsive): fix prettier format
> fix(vx-responsive): fix prettier format

- packages/vx-brush/package.json
- packages/vx-brush/test/utils.test.ts
- packages/vx-event/test/getXandYFromEvent.test.ts
- packages/vx-event/test/localPoint.test.ts
- [brush] add utils test
- [event] add tests
> test(vx-brush,vx-event): add code coverage

- packages/vx-scale/src/createScale.ts
- Add fallback overload for `createScale`
> feat: scale overload

- packages/visx-shape/src/shapes/link/step/LinkHorizontalStep.tsx
> fix(shape/LinkHorizontalStep): render horizontally not vertically

- README.md
- internal(readme): add https://dollar-to-food-emoji.web.app/ demo to README.md
> internal(readme): add https://dollar-to-food-emoji.web.app/ demo to README.md

- README.md
- Fix the syntax of readme
Sorry...I messed up the format in my last PR
> fix: readme format

- yarn.lock
Forgot to add yarn.lock changes in https://github.com/airbnb/visx/pull/915
- fix(root/demo): bump yarn.lock with next@9.5.4
> fix(demo): bump yarn.lock with next@9.5.4

- README.md
Over the last few days I created this little demo which uses a lot of visx features in combination (stack, tooltip, brush + some interactivity)
> add tokenizedbtc to in the wild list

- CHANGELOG.md
Usually don't make a PR for this, but wrote it up while waiting on a few last PRs to land for `1.3.0` so won't commit directly
> changelog: 1.3.0

- README.md
- Add a new 'In the wild' website
> Update: Readme - In the wild - eft.monster

- .github/workflows/push.yml
Fixes [this](url) actions syntax error 🤦 
```
The workflow is not valid. 
.github/workflows/push.yml (Line: 12, Col: 14): Unexpected value '' 
.github/workflows/push.yml (Line: 14, Col: 9): Unexpected value 'fetch-depth'
```
> fix(workflows/push): fix yaml syntax

- packages/visx-annotation/package.json
- packages/visx-tooltip/package.json
- yarn.lock
- fix(tooltip, annotation): bump react-use-measure to ^2.0.4. fixes https://github.com/airbnb/visx/issues/1091
> fix(tooltip, annotation): bump react-use-measure to ^2.0.4. fixes #1091

- README.md
- Add Pry.co to "In the wild" section
> docs: Add Pry to In the Wild list

- packages/visx-xychart/README.md
- packages/visx-xychart/src/components/XYChart.tsx
Fixing a couple of typo's I came across while working with `XYChart`.
> docs(xychart): fix typos

- packages/visx-scale/package.json
- packages/visx-scale/src/scales/symlog.ts
- packages/visx-scale/src/types/ScaleConfig.ts
- packages/visx-scale/test/scaleSymlog.test.ts
- yarn.lock
> feat(scale): support rounding for symlog

- README.md
Add https://donate.data2thepeople.org/ to "In the wild" section
> Add Data 2 the People to In the Wild list

- packages/visx-responsive/package.json
- packages/visx-shape/package.json
- packages/visx-text/package.json
- packages/visx-xychart/package.json
- yarn.lock
Fixes https://github.com/airbnb/visx/issues/1340 by bumping `(@types/)lodash` to the latest for all packages.
@kristw @gazcn007 
cc @yabbbb
> deps: bump lodash throughout

- README.md
Add https://augora.fr to "In the wild" section
> docs: Add https://augora.fr to "In the wild" section

- packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx
- packages/visx-xychart/src/components/Tooltip.tsx
renamed `RenderTooltipGlypProps` to `RenderTooltipGlyphProps`
> fix(xychart): fix typo

- packages/visx-xychart/README.md
- packages/visx-xychart/src/components/XYChart.tsx
- packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx
- packages/visx-xychart/src/components/series/private/BaseAreaStack.tsx
- packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx
- packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx
- packages/visx-xychart/src/components/series/private/BaseBarStack.tsx
- packages/visx-xychart/src/components/series/private/BaseGlyphSeries.tsx
- packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx
- packages/visx-xychart/src/hooks/useEventEmitter.ts
- packages/visx-xychart/src/hooks/useEventEmitters.ts
- packages/visx-xychart/src/hooks/useEventHandlers.ts
- packages/visx-xychart/src/hooks/useSeriesEvents.ts
- packages/visx-xychart/src/types/series.ts
- packages/visx-xychart/test/hooks/useEventEmitters.test.tsx
Fixes https://github.com/airbnb/visx/issues/1438
-
-
-
-
-
> feat(xychart): support onPointerDown event

- packages/visx-visx/package.json
- packages/visx-visx/src/index.ts
Fixes #1556
Added visx/threshold in visx/visx
> Include visx/threshold in visx/visx

- packages/visx-mock-data/src/index.ts
bitcoinPrice was missing in the mock-data index and could not be imported
> fix(mock-data): add missing bitcoinPrice to index.ts

- README.md
- Add Fig Stats project to "In the wild" readme section
Hope you'll like it 🙂
> docs: Add Fig Stats to In the wild

- packages/visx-demo/src/sandboxes/visx-brush/Example.tsx
- packages/visx-demo/src/sandboxes/visx-wordcloud/Example.tsx
- packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx
- packages/visx-xychart/src/components/XYChart.tsx
- packages/visx-xychart/src/providers/DataProvider.tsx
- packages/visx-xychart/src/types/data.ts
- Replace all instances of `import ... from '@visx/.../src/...';` with `import ... from '@visx/.../lib/...';` 
- Closes: #1659
> fix(demo/sandboxes, xychart): Convert '@visx/.../src/...' to '@visx/.../lib/...'

- packages/visx-zoom/src/types.ts
-
-
- update handlePinch type description
-
-
> docs(zoom): update handlePinch type description

- README.md
Let me know on Slack if you have any questions.
> docs(in the wild): remove broken app link

- scripts/performRelease/createGithubRelease.ts
- scripts/performRelease/fetchCommitsSinceTag.ts
- scripts/performRelease/fetchPRsForCommits.ts
- scripts/performRelease/postReleaseOnPrs.ts
- scripts/utils/getGitHubClient.ts
- scripts/utils/upsertPullRequestComment.ts
Fixes for https://github.com/airbnb/visx/actions/runs/5406423388
> github: fix release types and logic

- README.md
-
-
- Add physician.fyi, which uses visx on its main page to show actions over time as well on physician profiles to shows how they split up their time.
-
-
> Add to "In the wild"

- README.md
📝 Documentation
- Add Superstardle sites to "In The Wild" — [Index by Superstardle](https://index.superstardle.com) & [Salaries by Superstardle](https://salaries.superstardle.com)
Thanks and enjoy!! 👍🏼👌🏼
> docs: add Superstardle in the wild

- packages/visx-xychart/src/components/XYChart.tsx
Print console.info only in developer #1782
> feat(xychart): print console.info only in dev mode

- README.md
📝 Documentation
- Add new Superstardle site to "In The Wild" leveraging `visx/drag` — [Pack'Em by Superstardle](https://playoffs.superstardle.com) 
Thanks and enjoy!! 👍🏼👌🏼
> Adds to "in the wild", new site using visx/drag

- packages/visx-xychart/README.md
Small fix in the documentation on theming.
Cheers
> Fix small error in the code example in the "Theming" section
