packages/vx-responsive/src/components/ScaleSVG.js
Just stumbled across this codebase a spotted a typo in the styles for `@vx/responsive`. Not sure what impact this'll have, but I figured, if it's in there, it should probably be spelt right :)
=> Fix styles typo

packages/vx-scale/Readme.md
In general, I just linked to the d3 docs. This isn't the greatest, but I think it's fine for now, right? If not I can add better docs for each one here too.
=> Add docs for `@vx/scale` package

packages/vx-annotation/Readme.md, packages/vx-curve/Readme.md, packages/vx-glyph/Readme.md, packages/vx-gradient/Readme.md, packages/vx-group/Readme.md
I added some simple docs explaining an example for annotation and a markdown table for properties similar to what [Material-UI](http://www.material-ui.com/#/components/badge#properties) has for it's docs. 
Since working with markdown tables is kind of annoying, I did two things. First I got the [markdown-table-editor](https://atom.io/packages/markdown-table-editor) package for Atom. Then I [wrote a python script](https://gist.github.com/Flaque/beac1aff6ef313875cc6ef8043faf928) to take the function call params and fill out the name, type, and defaults of the table so there was less busy work.
=> Add docs for several different packages.

packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js, packages/vx-axis/src/utils/isHorizontal.js, packages/vx-axis/src/utils/isLeft.js, packages/vx-axis/src/utils/labelTransform.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/pages/axis.js, packages/vx-group/src/Group.js
@hshoff see what you think of this. Because the number of props for the `Axis` components was getting unwieldy, this PR updates them to expect explicit label components to enable full control over their appearance (though simple tweaks like color now require more code as you can see in the `demo -> axis.js`).
I got rid of some props like `tickK` because it seemed like there was mixed logic for using the `tickK` that was passed in for some computations but still inferring orientation with the `ORIENTATION` symbol...which seemed like it could cause bugs with some combos. If users wanted to customize the `tickTransform` they can still do this.
Tested the params by customizing in all directions:
=> pass in axis label components explicitly

packages/vx-demo/components/tiles/bargroup.js, packages/vx-demo/components/tiles/barstack.js, packages/vx-demo/pages/bargroup.js, packages/vx-demo/pages/barstack.js, packages/vx-demo/pages/gallery.js, packages/vx-scale/src/scales/band.js, packages/vx-shape/build/index.js, packages/vx-shape/package.json, packages/vx-shape/src/index.js, packages/vx-shape/src/shapes/AreaStack.js, packages/vx-shape/src/shapes/Bar.js, packages/vx-shape/src/shapes/BarGroup.js, packages/vx-shape/src/shapes/BarStack.js, packages/vx-shape/src/util/callOrValue.js, packages/vx-shape/test/BarGroup.test.js, packages/vx-shape/test/BarStack.test.js
=> [shape] add <BarGroup /> & <BarStack />. fixes #38 

packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js
@hshoff in working with bar charts that don't have band scales (e.g., for time), you have to compute the bar width manually and also the offset from the tick position (see [this discussion](https://stackoverflow.com/questions/18835053/d3-js-calculate-width-of-bars-in-time-scale-with-changing-range) on StackOverflow).
Even if you compute this width and offset the `x` position of the _bars_, the scale itself doesn't account for the offset so the `Axis` is missing padding that you get for free with band scales:
I tried a few different ways of doing this including overriding the `Axis` position function,  but I think simply padding the range is a reasonable way to approach it (e.g., VictoryCharts [supports a `domainPadding` prop](http://formidable.com/open-source/victory/docs/victory-chart/#do …
=> [Axis] add `rangePadding`

packages/vx-responsive/src/enhancers/withParentSize.js, packages/vx-responsive/src/index.js, packages/vx-responsive/test/withParentSize.test.js
This PR adds a new `withParentSize` enhancer to `vx-responsive` to allow a chart to get its parent size if `screenSize` doesn't suffice. Let me know if you think a different approach would be better.
Tested with `@data-ui/xy-chart` and with `jest`, yellow is the HOC's container:
```js
const ResponsiveXYChart = withParentSize(({ parentWidth, children, ...rest }) => (
<XYChart
theme={theme}
width={parentWidth}
height={parentWidth / 1.9}
{...rest}
>
{children}
</XYChart>
));
```
=> [vx-responsive] add withParentSize enhancer

packages/vx-scale/Readme.md, packages/vx-scale/src/index.js, packages/vx-scale/src/scales/time.js, packages/vx-scale/src/scales/utc.js, packages/vx-scale/test/scaleUtc.test.js
Currently there's a bug where adding a `scaleUtc=true` to your `scaleTime` function will cause JS to crash:
``` js
// Crashes! 🚨🚨
scaleTime({
scaleUtc=true, 
...
});
```
This was happening because the `time.js` file was calling `scale.scaleUtc();`, which isn't a function defined by d3. However, d3 does have a function called `scaleUtc` which works exactly like the `scaleTime` function but instead returns time vars in UTC format.  
1. Removes the `scaleUtc` option from the `scaleTime` function in `vx-scale`.
2. Adds a new scale: `scaleUtc` to a `utc.js` file.
3. Updates readme to reflect changes.
4. Adds sanity test for` scaleUtc`.
=> [Bug fix] Move `scaleUtc` into it's own function

packages/vx-axis/src/utils/labelTransform.js
This PR fixes a bug with the (y-axis) label transform logic. For y-axes you often have a pattern where you set the following domain and range to correct for the upper-right `(0,0)` svg coord:
```javascript
domain = [min val, max val];
range = [height, 0] 
// y-axis has `min val` at the bottom and `max val` at the top
```
If you want to have the min value at the _top_ of the scale you actually invert the range to `[0, height]`. The current y-label transform assumes the former and this PR fixes it.
Before:
After:
Verified that current transforms still work as expected:
=> [axis] fix label transform

packages/vx-clip-path/.babelrc, packages/vx-clip-path/Makefile, packages/vx-clip-path/package.json, packages/vx-clip-path/src/clip-paths/CircleClipPath.js, packages/vx-clip-path/src/clip-paths/ClipPath.js, packages/vx-clip-path/src/clip-paths/RectClipPath.js, packages/vx-clip-path/src/index.js, packages/vx-clip-path/test/ClipPaths.test.js
Let me know what you think about the utility of something like this. I think it's less useful than the `Gradients` package but on par with the `Group` package esp since it gets around creating the `<defs>` etc.
Before:
After with `<RectClipPath id="clip"width={innerWidth} height={innerHeight} />`:
=> [ClipPath] add ClipPath package

packages/vx-responsive/package.json, packages/vx-responsive/src/enhancers/withParentSize.js, packages/vx-responsive/src/enhancers/withScreenSize.js
The per-method packages are zero-dependency modules, so they often
include a bunch of extra code compared to importing from lodash/foo. We
can save some bundle size by using these partial includes instead.
Additionally, if I recall correctly, the per-method packages are all
deprecated and no longer updated, so this is the way to go for lodash
moving forward.
=> Replace lodash per-method packages with scoped imports

packages/vx-shape/src/shapes/LinePath.js
This PR adds `strokeDashoffset` prop to `LinePath` component which is helpful for transitions.
=> add strokeDashoffset prop to LinePath

packages/vx-shape/src/shapes/AreaClosed.js
If range of scale does not start at 0, chart would extend beyond bounds of the scale when yScale(0) is used. This fixes it by taking first element of scales range (which should be the lowest y point on screen)
I was not able to test the code, trying to run tests resulted in lots of errors across all packages. Also even if technically correct I am not sure if this does not brake something outside of my usecase.
=> Get min range for area chart baseline

packages/vx-group/src/Group.js, packages/vx-group/test/Group.test.js
This PR adds support for `...restProps` in `<Group />`. I've needed a couple of things like `clipPath` and [`<g>` elements support many other attributes](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g) so this seems useful generally.
Tested with `jest`.
=> [Group] add restProps support

packages/vx-axis/src/index.js, packages/vx-axis/test/Orientation.test.js, packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/legends.js, packages/vx-demo/components/tiles/voronoi.js, packages/vx-demo/pages/legends.js
https://github.com/hshoff/vx/issues/79
also design polish on legends demo
=> [axis] export orientation constants. fixes #79

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/components/tiles/bars.js, packages/vx-demo/components/tiles/gradients.js, packages/vx-demo/components/tiles/voronoi.js, packages/vx-demo/pages/axis.js, packages/vx-demo/pages/gradients.js, packages/vx-gradient/package.json, packages/vx-gradient/src/gradients/LinearGradient.js, packages/vx-legend/src/legends/Legend.js
`@vx/gradient`
- add horizontal gradients with `vertical={false}` - defaults to `true`
- add support for children so you can pass in your own `<stop />`s
- add `rotate` shortcut prop
- add `transform` prop to set your own transform - rotate takes precedence over transform, so if you're adding your own transform remove the rotate prop and include `rotate(270)` or whatever value in your transform string
- add `fromOpacity` and `toOpacity` props
- remove hardcoded `x1, y1, x2, y2`, can set your own - defaults to vertical, set `vertical={false}` to get horizontal or set your own
- add proptypes
`@vx/legend`
- fix shape proptype to add oneOfType string as well as func
=> [gradient] add horizontal linear gradients, make more flexible. fixes #68

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/dots.js, packages/vx-demo/components/tiles/legends.js, packages/vx-demo/pages/dots.js, packages/vx-demo/pages/legends.js, packages/vx-glyph/src/glyphs/Circle.js, packages/vx-glyph/src/glyphs/Diamond.js, packages/vx-glyph/src/glyphs/Square.js, packages/vx-glyph/src/glyphs/Star.js, packages/vx-glyph/src/glyphs/Triangle.js, packages/vx-glyph/src/glyphs/Wye.js, packages/vx-glyph/src/index.js, packages/vx-glyph/test/Circle.test.js, packages/vx-glyph/test/Cross.test.js, packages/vx-glyph/test/Diamond.test.js, packages/vx-glyph/test/Square.test.js, packages/vx-glyph/test/Star.test.js, packages/vx-glyph/test/Triangle.test.js, packages/vx-glyph/test/Wye.test.js
- adds support for the missing d3 symbols from [d3-shape](https://github.com/d3/d3-shape#symbols)
- `<GlyphDot />` should be considered deprecated in favor of `<GlyphCircle />` for a consistent api across all Glyphs, but I'll keep GlyphDot around just in case folks are already using it as legacy
`<GlyphCircle />`
`<GlyphSquare />`
`<GlyphWye />`
`<GlyphTriangle />`
`<GlyphStar />`
`<GlyphCross />`
=> [glyph] add remaining d3 symbols

package.json, packages/vx-demo/pages/docs.js, packages/vx-demo/static/doc_styles.css, packages/vx-demo/static/docs/vx-annotation.html, packages/vx-demo/static/docs/vx-axis.html, packages/vx-demo/static/docs/vx-brush.html, packages/vx-demo/static/docs/vx-curve.html, packages/vx-demo/static/docs/vx-demo.html, packages/vx-demo/static/docs/vx-drag.html, packages/vx-demo/static/docs/vx-event.html, packages/vx-demo/static/docs/vx-glyph.html, packages/vx-demo/static/docs/vx-gradient.html, packages/vx-demo/static/docs/vx-grid.html, packages/vx-demo/static/docs/vx-group.html, packages/vx-demo/static/docs/vx-marker.html, packages/vx-demo/static/docs/vx-mock-data.html, packages/vx-demo/static/docs/vx-pattern.html, packages/vx-demo/static/docs/vx-point.html, packages/vx-demo/static/docs/vx-responsive.html, packages/vx-demo/static/docs/vx-scale.html, packages/vx-demo/static/docs/vx-shape.html, packages/vx-demo/static/docs/vx-text.html, packages/vx-demo/static/docs/vx-zoom.html, scripts/docs/README.md, scripts/docs/constants.js, scripts/docs/index.js, scripts/docs/package.json
- A script to compile Markdown to HTML docs -> Issue #9
This might not be exactly what you meant, but it might help get the docs onto the website for the moment. Let me know your thoughts, I'm not attached to anything in particular and can do something different if you'd like. 
- A new top-level folder `scripts`
- A script `docs` that compiles each package's README into an HTML doc with the same name inside a folder called `docs` inside `vx-demo`.
- Alters the `docs.js` file in `vx-demo` to link to each html page.
- It's really easy to make docs! Woo! `$ node scripts/docs/index.js`
- The docs are in the website immediately so they're easy for people who are interested in VX to view right now! :D 
The HTML docs are static individual files stored inside of the `static` folder (so mixing …
=> Add script to compile Markdown into HTML docs

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/boxplot.js, packages/vx-demo/pages/boxplot.js, packages/vx-glyph/src/glyphs/statistics/BoxPlot.js, packages/vx-glyph/src/index.js, packages/vx-glyph/test/BoxPlot.test.js
As per request, a simple version of  Box Plot is added here as a glyph. 
http://www.physics.csbsju.edu/stats/box2.html 
Or it is too high level for vx? since it is actually not a basic visual component. @williaster
=> added Glyph support for BoxPlot

packages/vx-demo/components/tiles/gradients.js, packages/vx-demo/components/tiles/lineradial.js, packages/vx-demo/pages/gradients.js, packages/vx-gradient/src/gradients/RadialGradient.js, packages/vx-gradient/src/index.js, packages/vx-gradient/test/LinearGradient.test.js, packages/vx-gradient/test/RadialGradient.test.js
fixes: https://github.com/hshoff/vx/issues/83
=> [gradient] add <RadialGradient />. fixes #83

packages/vx-bounds/.babelrc, packages/vx-bounds/Makefile, packages/vx-bounds/Readme.md, packages/vx-bounds/package.json, packages/vx-bounds/src/enhancers/withBoundingRects.js, packages/vx-bounds/src/index.js, packages/vx-bounds/test/withBoundingRects.test.js
This PR adds the `@vx/bounds` package which contains a `withBoundingRects()` higher-order component that is meant to help with detecting whether a given component is overflowing its parent container. This HOC passes the following props to the component which it wraps:
```javascript
const rectShape = PropTypes.shape({
top: PropTypes.number.isRequired,
right: PropTypes.number.isRequired,
bottom: PropTypes.number.isRequired,
left: PropTypes.number.isRequired,
width: PropTypes.number.isRequired,
height: PropTypes.number.isRequired,
});
export const withBoundingRectsProps = {
getRects: PropTypes.func,
rect: rectShape,
parentRect: rectShape,
};
```
**Tests**
Tested with jest and with `@vx/tooltip` in a separate repository:
**Naive tooltip (before`withBoundingRects()`)**
**Smarter tooltip (after …
=> [vx-bounds] add package with 'withBoundingRects()' HOC and tests

packages/vx-shape/package.json, packages/vx-shape/src/shapes/AreaClosed.js, packages/vx-shape/test/Arc.test.js, packages/vx-shape/test/AreaClosed.test.js, packages/vx-shape/test/Line.test.js
Also fixed a bug where `rgba()` was treated as a function because it wasn't in quotes and therefore would cause an `undefined` error.
=> [shape] Add tests for Arc, AreaClosed, & Line

packages/vx-axis/test/Axis.test.js
Adds tests that prove the functionality of:
1. Passing down the classname 
2. Hiding 0th element
3. Hiding axis line
4. Hiding ticks
Let me know if there's anything in here that could be better.
=> [Axis] Add tests to Axis.test.js

packages/vx-boxplot/Readme.md
This adds documentation to [`vx/boxplot`](https://github.com/hshoff/vx/tree/master/packages/vx-boxplot).  It was brought up (by me) in [this issue](https://github.com/hshoff/vx/issues/9).
I tried to follow the style in the rest of the documentation, so I added
- A short description of what a boxplot is
- A table documenting the properties of the `<BoxPlot />` component
Questions I have:
- Is this written in the correctly?
- Is more information necessary?
- Is a picture necessary?
P.S. This is my first PR (ever!), so please let me know if there's anything I missed.  I'm still learning to etiquette of OSS 👶
=> Boxplot readme description + properties

packages/vx-axis/Readme.md, packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js, packages/vx-axis/test/Axis.test.js
This PR does the following with the goal of making the `Axis` ticks more customizable:
1) passes tick index as a second argument to the `tickFormat` function for more customizability options. 
2) adds a `tickValues` prop to all `Axis*` components that lets you specify exactly which tick values to show.
3) updates the readme to address #107 
4) adds `Axis` tests for the new functionality
New jest tests pass and tested`tickValues` and access to tick index in `tickFormat` functionally across all orientations in a linked [`@data-ui`](https://github.com/williaster/data-ui) repo:
=> [axis] make ticks more customizable

packages/vx-tooltip/package.json, packages/vx-tooltip/src/enhancers/withTooltip.js, packages/vx-tooltip/src/index.js, packages/vx-tooltip/src/tooltips/Tooltip.js, packages/vx-tooltip/src/tooltips/TooltipWithBounds.js, packages/vx-tooltip/test/TooltipWithBounds.test.js
This PR adds a`<TooltipWithBounds />` component that wraps the current `<Tooltip />` and is aware of its bounds via the `@vx/bounds` HOC. It also adds some more `PropTypes` to the package.
I found myself wanting a tooltip with this functionality and thought it'd be a useful add here but let me know if you think it's too specialized.
Tested functionally in a linked `@data-ui`
=> [tooltip] add `<TooltipWithBounds />` and PropTypes to `@vx/tooltip` exports

packages/vx-geo/src/graticule/Graticule.js, packages/vx-geo/src/projections/Graticule.js, packages/vx-geo/src/projections/Projection.js
Implemented graticule for projection's.
Draw graticule:
```js
<Mercator
data={world.features}
scale={width / 630 * 100}
translate={[width / 2, height / 2 + 50]}
fill={() => '#8be4c5'}
stroke={() => '#5fcfa7'}
graticule={{
stroke: 'rgba(85, 189, 213, 0.3)'
}}
/>
```
Graticule lines in foreground of the map and outline:
```js
<Mercator
//...
graticuleLines={{
foreGround: true,
stroke: (data) => 'rgba(85, 189, 213, 0.3)'
}}
graticuleOutline={{
stroke: 'rgba(85, 189, 213, 0.3)'
}}
/>
```
Any other ideas to implement graticule. I think graticule as prop is fine because a graticule without a projection doesn't make sense.
=> [geo] add graticule

packages/vx-bounds/package.json
Moving `react-dom` to peerDeps. Fixes https://github.com/hshoff/vx/issues/130
cc @williaster
=> [bounds] move react-dom to peerDeps

packages/vx-hierarchy/Readme.md
I have a few notes/questions:
1. It appears that `className` is passed as a prop to both components, but is never actually called, so I didn't include it in the props table.  Am I missing something here?
2. The props `size`, `nodeSize`, and `separation` are all passed to the respective d3 layouts, and that's where the defaults are being set (not in the vx components).  Should we mention this, or is it not a big deal?
3. Should this readme include more details on `nodeComponent` and `linkComponent`?  Is there a plan to have defaults for these, like in [vx/network](https://github.com/hshoff/vx/tree/master/packages/vx-network)?
[Link to components for convenience.](https://github.com/hshoff/vx/tree/master/packages/vx-hierarchy/src/hierarchies)
Let me know if anything needs clarification!
=> add readme for vx/hierarchy

packages/vx-axis/Readme.md, packages/vx-axis/package.json, packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js, packages/vx-axis/src/utils/labelTransform.js, packages/vx-axis/test/Axis.test.js, packages/vx-axis/test/AxisBottom.test.js, packages/vx-axis/test/AxisLeft.test.js, packages/vx-axis/test/AxisRight.test.js, packages/vx-axis/test/AxisTop.test.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/components/tiles/bargroup.js, packages/vx-demo/components/tiles/barstack.js, packages/vx-demo/pages/axis.js, packages/vx-demo/pages/bargroup.js, packages/vx-demo/pages/barstack.js
This PR makes some (**breaking**❗️) changes to the `@vx/axis` package to address several issues highlighted in #138. It also updates relevant `@vx/axis` tests, the demo pages, and the Readme for the package (I couldn't successfully get the docs script to run locally, though 🤔 ).
**Removed**
The following props were removed to make the API more consistent by getting rid of component wrappers:
- `labelComponent`
- `tickLabelComponent`
The generic `className` prop was also removed for more _granular_ control (see below).
**Added**
To replace the above functionality the following props were added:
- `label` (a string label)
- `labelProps` (`obj`, styles applied to the label `text` element)
- `tickLabelProps` (`(tickValue, index) => obj`, called for each tick, returned styles are applied to …
=> make `@vx/axis` api more sane, update docs

packages/vx-hierarchy/src/DefaultLink.js, packages/vx-hierarchy/src/DefaultNode.js, packages/vx-hierarchy/src/hierarchies/Cluster.js, packages/vx-hierarchy/src/hierarchies/Tree.js, packages/vx-hierarchy/src/index.js, packages/vx-hierarchy/test/Defaults.test.js
This is related to #139 
This PR does the following (each statement applies to both `<Tree />` and `<Cluster />` components:
1. Adds `className` to each `<Group />` component.
* Is this where the `className` prop should go?  I didn't see any other reasonable place to put it.
2. Adds `<DefaultLink />` and `<DefaultNode />` components to each component, along with basic tests for each.
* These render just fine--let me know if there are issues with them.
* I don't know much about testing components, so let me know if we need more comprehensive tests right now 🃏 
This PR **does not**
3. Add defaults to the `size`, `nodeSize`, and `separation` props.
* The defaults are set in the corresponding d3 functions.   The questions is, are we setting defaults at the highest or lowest level they're …
=> Update hierarchy comps

packages/vx-hierarchy/Readme.md
This is a pretty simple update to the readme.
I ❤️ docs
=> [hierarchy] update links and descriptions in readme

packages/vx-demo/components/gallery.js, packages/vx-demo/components/show.js, packages/vx-demo/components/tiles/streamgraph.js, packages/vx-demo/package.json, packages/vx-demo/pages/streamgraph.js, packages/vx-shape/build/index.js, packages/vx-shape/src/index.js, packages/vx-shape/src/shapes/Stack.js, packages/vx-shape/src/util/stackOffset.js, packages/vx-shape/src/util/stackOrder.js, packages/vx-shape/test/Stack.test.js, packages/vx-shape/test/stackOffset.test.js, packages/vx-shape/test/stackOrder.test.js
There are two ways of handling the stack series data + path
```js
<Stack
data={cityTemperature}
keys={keys}
offset="wiggle"
curve={curveBasis}
x={d => xScale(x(d.data))}
y0={d => yScale(d[0])}
y1={d => yScale(d[1])}
fill={d => zScale(d.series.key)}
/>
```
or you can use a render prop for total control of what gets rendered
```js
<Stack
data={layers}
keys={keys}
offset="wiggle"
x={(d, i) => xScale(i)}
y0={d => yScale(d[0])}
y1={d => yScale(d[1])}
render={({ seriesData, path }) => {
return seriesData.map((series, i) => {
return (
<g key={`series-${series.key}`}>
<path
d={path(series)}
fill={zScale(series.key)}
/>
<path
d={path(series)}
fill={`url(#${patternScale(series.key)})`}
/>
</g>
);
});
}}
/>
```
=> [shape][demo] add <Stack />, add /streamgraph

package.json, packages/vx-annotation/package.json, packages/vx-axis/package.json, packages/vx-bounds/package.json, packages/vx-boxplot/package.json, packages/vx-brush/package.json, packages/vx-clip-path/package.json, packages/vx-curve/package.json, packages/vx-demo/package.json, packages/vx-drag/package.json, packages/vx-event/package.json, packages/vx-geo/package.json, packages/vx-glyph/package.json, packages/vx-gradient/package.json, packages/vx-grid/package.json, packages/vx-group/package.json, packages/vx-heatmap/package.json, packages/vx-hierarchy/package.json, packages/vx-legend/package.json, packages/vx-marker/package.json, packages/vx-network/package.json, packages/vx-pattern/package.json, packages/vx-responsive/package.json, packages/vx-scale/package.json, packages/vx-shape/package.json, packages/vx-text/package.json, packages/vx-tooltip/package.json, packages/vx-voronoi/package.json, packages/vx-vx/package.json, packages/vx-zoom/package.json
- should fix https://github.com/hshoff/vx/issues/154 
- `react-addons-test-utils` => `react-test-renderer`
**Note**
- tests are still written using enzyme 2 and react 15, so react 16 behavior isn't guaranteed awesome
- this is mostly for folks that want to get ahead and try out react 16 before everyone else 
💖  If you find any issues using React 16 please open an issue
=> [deps] react 16, react-test-renderer

packages/vx-bounds/test/withBoundingRects.test.js, packages/vx-demo/components/tiles/tree.js, packages/vx-hierarchy/src/hierarchies/Cluster.js, packages/vx-hierarchy/src/hierarchies/Tree.js, packages/vx-hierarchy/test/Cluster.test.js, packages/vx-hierarchy/test/Tree.test.js
More control over rendering. Fix for https://github.com/hshoff/vx/issues/162
```js
<Tree root={someHierarchy}>
{({ links, descendants, data, root }) => {
// up to you
}}
</Tree>
```
cc @techniq
=> [hierarchy] add render prop to <Tree /> + <Cluster />

packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js, packages/vx-axis/test/Axis.test.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/pages/axis.js
This is meant to address
- https://github.com/hshoff/vx/issues/160 - Allow custom component for axis label
- https://github.com/hshoff/vx/issues/149 - Axis tick text transforms
and any future customization/extension by passing render control to the user.
So now you can do:
```js
<AxisBottom
top={height - margin.bottom}
left={margin.left}
scale={xScale}
numTicks={numTicksForWidth(width)}
label="time"
>
{props => {
const tickLabelSize = 10;
const tickRotate = 45;
const tickColor = '#8e205f';
const axisCenter =
(props.axisToPoint.x - props.axisFromPoint.x) / 2;
return (
<g className="my-custom-bottom-axis">
{props.ticks.map((tick, i) => {
const tickX = tick.to.x;
const tickY =
tick.to.y + tickLabelSize + props.tickLength;
return (
<Group
key={`vx-tick-${tick.value}-${i}`} …
```
=> [axis] render prop for axis, full control over rendering

packages/vx-demo/components/tiles/legends.js, packages/vx-legend/src/legends/Threshold.js
Thanks to @alexsinfarosa for spotting this bug https://github.com/hshoff/vx/issues/157
=> [legend] fix legend threshold. fixes #157

packages/vx-demo/components/tiles/area.js, packages/vx-demo/pages/areas.js, packages/vx-event/src/index.js, packages/vx-event/src/localPoint.js, packages/vx-event/src/touchPoint.js
Fixes: https://github.com/hshoff/vx/issues/15
Adds single arity support to `localPoint(event)` which will find the ownerSVG and loop for the owner on nested SVG. This use case was found by @conglei  when his chart has nested svg icons that had event handlers. Thanks to @conglei for pointing this out.
You can still pass in a reference to a specific svg if you want your local point relative to a specific svg element by using dual arity `localPoint(svgNode, event)` or `localPoint(event.target.ownerSVGElement, event)`.
Lastly, this adds touch event support to `localPoint` so you don't have to use `touchPoint` and `localPoint`. `touchPoint` will still exist to prevent breaking changes for folks. I also added `touchPoint` to the exports on index so you can now do `import { touchPoint } from …
=> [event] add touchEvt support to localPnt, find owner svg. fixes #15

packages/vx-shape/package.json, packages/vx-shape/src/shapes/AreaClosed.js, packages/vx-shape/src/shapes/Bar.js, packages/vx-shape/src/shapes/Line.js, packages/vx-shape/src/shapes/LinePath.js, packages/vx-shape/src/shapes/LineRadial.js, packages/vx-shape/src/shapes/LinkHorizontal.js, packages/vx-shape/src/shapes/LinkVertical.js, packages/vx-shape/test/AreaClosed.test.js, packages/vx-shape/test/Bar.test.js, packages/vx-shape/test/Line.test.js, packages/vx-shape/test/LinePath.test.js, packages/vx-shape/test/LineRadial.test.js, packages/vx-shape/test/LinkHorizontal.test.js, packages/vx-shape/test/LinkVertical.test.js
Fix for https://github.com/hshoff/vx/issues/140
Pass a ref callback function as the `innerRef` prop to get the backing ref.
```js
<LinePath
innerRef={(node) => { this.myCoolLine = node; }}
// ...
/>
```
More about refs: https://reactjs.org/docs/refs-and-the-dom.html
=> [shape] add innerRef prop to shapes. fixes #140

packages/vx-demo/components/gallery.js, packages/vx-demo/pages/home.js
super minor fixes for vx-demo.now.sh
=> [demo] fix type on /, fix areas tile details

package.json, packages/vx-hierarchy/src/hierarchies/Cluster.js, packages/vx-hierarchy/src/hierarchies/Pack.js, packages/vx-hierarchy/src/hierarchies/Partition.js, packages/vx-hierarchy/src/hierarchies/Tree.js, packages/vx-hierarchy/src/hierarchies/Treemap.js
I also updated `Tree` and `Cluster` to only pass a single param to the child render function.  Based on [this](https://github.com/d3/d3-hierarchy#hierarchy):
I thought it made sense to swap `data` and `root` names, so now a layout component takes in a `data` prop (instead of `root`) and the child render function receives a `root` prop (instead of `data`, along with removing `descendants`, `links`, etc).
This also makes it more consistent with `BarGroup`, `BarStack`, `Projection`, etc.  I can be talked out of this, but it seemed like it made sense, and since we were already making a breaking change with the number of params passed to the children function, I thought it was worth changing.
=> Add Pack, Partition, and Treemap hierarchical layouts.  Closes #172

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/radar.js, packages/vx-demo/pages/radar.js
🚀  **Enhancements**
Add a radar chart demo.
I'm not good at design, you can make it better. 👻
=> [demo] Add Radar chart; fix #159

packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js
not realllly a bug, but along those lines this PR makes all `<Axis* />` component `tickValues` `propTypes` less restrictive. currently if you were to specify an array of dates for a timeline axis you would get console warnings.
=> [axis] less restrictive tickValue propTypes

packages/vx-shape/build/index.js, packages/vx-shape/src/index.js, packages/vx-shape/src/shapes/Area.js, packages/vx-shape/test/Area.test.js
This PR adds a new `<Area />` component (+ tests) to the `@vx/shape` package to support confidence bands, which the current `<AreaClosed />` component doesn't support. I left the current `<AreaClosed />` component in addition to the new component to avoid breaking changes and because I think there's merit having specialized components for this.
Tested with jest and functionally / visually with a linked `@data-ui` library:
=> 🚀 [shape] add `<Area />` and tests

packages/vx-bounds/src/enhancers/withBoundingRects.js, packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
The goal of this PR is to fix issues like this where the tooltip overlaps the point:
To do so I added optional `leftOffset` and `topOffset` props to the `<TooltipWithBounds />` which offset the final `left` and `top` positions depending on the `boundingClientRect`s it receives from `withBoundingRects`:
- if the tooltip will be *right* of the pointer, it it shifted `+leftOffset`
- if the tooltip will be *left* of the pointer, it it shifted `-leftOffset`
- if the tooltip will be *below* of the pointer, it it shifted `+topOffset`
- if the tooltip will be *above* of the pointer, it it shifted `-topOffset`
I also considered creating `computeLeft({ left, rect, parentRect })` and `computeTop({ top, rect, parentRect })` props that allow the user to fully override the calculation but decided this …
=> [tooltip] add offset props to <TooltipWithBounds />

packages/vx-demo/components/gallery.js, packages/vx-demo/components/show.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/components/tiles/gradients.js, packages/vx-demo/components/tiles/lines.js, packages/vx-demo/components/tiles/responsive.js, packages/vx-demo/pages/axis.js, packages/vx-demo/pages/responsive.js, packages/vx-responsive/package.json, packages/vx-responsive/src/components/ParentSIze.js, packages/vx-responsive/src/components/ParentSize.js, packages/vx-responsive/src/index.js, packages/vx-responsive/test/ParentSize.test.js
- [responsive] add `<ParentSize />` component that uses [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) polyfill. fixes: https://github.com/hshoff/vx/issues/192
- [demo] update gallery tiles to use `<ParentSize />` 
- [demo] add /responsive gallery tile + page
=>  [responsive] add `<ParentSize />` component. fixes #192

packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
This PR fixes a pretty bad and somewhat esoteric bug for `<TooltipWithBounds />` in the `@vx/tooltip` package. Since [my PR](https://github.com/hshoff/vx/pull/193) that introduced optional padding/offsets for this component, it's been acting weird on the edges of containers:
@conglei and I debugged this earlier today and what we think is happening is that the tooltip `width` is being compressed on the edge of charts (when `word-wrap` is set to allow wrapping) like the pic below, making its `width` smaller and `height` larger (note this gif has boundary detection disabled). 
This smaller `width` and larger `height` _are_ reflected in the `withBoundingClientRect`s we get, but it seems because the tooltip is actually offset from the edge of the chart it does not visually appear to change …
=> [tooltip] fix tootlip with bounds offset

packages/vx-stats/src/boxplot/BoxPlot.js
- fixes the container calculation for `<Boxplot />` in `@vx/stats` (it appeared broken for horizontal and vertical positions, rendering negative widths etc)
- moves outliers to the bottom-most layer of the `<Boxplot />`
This is the container element (styled) afterward, for both orientations
- adds class names to the outlier `circle`s and boxplot box `rect`
cc @conglei
=> [stats][boxplot] fix container props calculation

packages/vx-geo/src/projections/Projection.js
None.
- 
Added pointRadius and fixed center.
-
-
Fixed center typo.
- 
-
=> Fix center and add pointRadius, innerRef

packages/vx-demo/pages/text.js, packages/vx-text/src/util/getStringWidth.js
- Add `fontWeight` option to vx-text demo
- Fix memoized `getStringWidth` ignoring styles 
---
=> Fix styled text wrapping

.travis.yml, package.json, packages/vx-axis/package.json, packages/vx-vx/test/index.test.js
- [travis] fix for travis failing for timing out when [not receiving output for 10min](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received)
- [vx][test] fix `@vx/vx` text test. It was looking for `TextOutline` export which was removed with the [new `@vx/text`](https://github.com/hshoff/vx/pull/208)
- [axis] bump `prop-types` dep and use `^`
=> [internal] fix travis builds, vx text test, bump axis prop-types dep

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/drag-i.js, packages/vx-demo/pages/drag-i.js, packages/vx-drag/src/Drag.js, packages/vx-drag/src/index.js, packages/vx-drag/src/util/raise.js
fixes #8 
- [drag] add `<Drag />` component
=> [drag] add @vx/drag, add /drag-i demo + tile. fixes #8

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/drag-i.js, packages/vx-demo/components/tiles/drag-ii.js, packages/vx-demo/pages/drag-i.js, packages/vx-demo/pages/drag-ii.js, packages/vx-drag/src/Drag.js
- [drag] remove `svg` prop. This was causing hacky problems like calling `forceUpdate` in `cDM`. `localPoint()` now finds svg from the event argument.
- [demo] update drag demos, add `touch-action: none` on drag demos so no scrolling when dragging
=> [drag][demo] remove <Drag /> svg prop, update drag demos

packages/vx-demo/components/tiles/linkTypes.js, packages/vx-shape/package.json, packages/vx-shape/src/shapes/link/curve/LinkHorizontalCurve.js, packages/vx-shape/src/shapes/link/curve/LinkRadialCurve.js, packages/vx-shape/src/shapes/link/curve/LinkVerticalCurve.js, packages/vx-shape/src/shapes/link/diagonal/LinkHorizontal.js, packages/vx-shape/src/shapes/link/diagonal/LinkRadial.js, packages/vx-shape/src/shapes/link/diagonal/LinkVertical.js, packages/vx-shape/src/shapes/link/line/LinkHorizontalLine.js, packages/vx-shape/src/shapes/link/line/LinkRadialLine.js, packages/vx-shape/src/shapes/link/line/LinkVerticalLine.js, packages/vx-shape/src/shapes/link/step/LinkHorizontalStep.js, packages/vx-shape/src/shapes/link/step/LinkRadialStep.js, packages/vx-shape/src/shapes/link/step/LinkVerticalStep.js
- Export `source` and `target` props on all `<Link*>` components
- Switch all (except `<LinkRadialStep>`) to use [d3-path](https://github.com/d3/d3-path) instead of svg path data to possibly support `<canvas>` in the future
=> Link path improvements

packages/vx-responsive/src/components/ParentSize.js
Here is a proposed solution for #228 
Just adds debounceTime prop with a default of 300ms.
Note, resize-observer-polyfill waits on requestAnimationFrame between invocations. https://github.com/que-etc/resize-observer-polyfill/blob/a3ae98bcd34e972b92d9e40e8b974a75399503e8/dist/ResizeObserver.js#L214
=> Added debounceTime prop to ParentSize

packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
- N/A
- now it consider window frame. If chart is only half visible the tooltip will adjust to window frame and not get cut.
- N/A
- N/A
- N/A
=> Tooltips With Bounds considering also screen bounds (window frame)

packages/vx-text/Readme.md
- Importing `Text` component from `@vx/text` was incorrect. (See Example
section)
=> Correct README.md of `@vx/text` package

packages/vx-axis/package.json, packages/vx-axis/src/axis/Axis.js, packages/vx-axis/src/axis/AxisBottom.js, packages/vx-axis/src/axis/AxisLeft.js, packages/vx-axis/src/axis/AxisRight.js, packages/vx-axis/src/axis/AxisTop.js, packages/vx-axis/test/Axis.test.js, packages/vx-axis/test/AxisBottom.test.js, packages/vx-axis/test/AxisLeft.test.js, packages/vx-axis/test/AxisRight.test.js, packages/vx-axis/test/AxisTop.test.js, packages/vx-demo/components/tiles/axis.js, packages/vx-demo/pages/axis.js, packages/vx-demo/static/docs/vx-axis.html
None 🎉 
Implements features mentioned in #259 
- use `@vx/text` for axis ticks and axis label
- add `tickComponent` prop to all axis components
1. By default `<Axis />` components now use `@vx/text` to render tick labels. This enables multi line labels and scaling text to fit in a certain amount of space.
Example:
```jsx
<Axis 
{...axisProps}
tickLabelProps = (tickValue, index) => ({
textAnchor: 'middle',
verticalAnchor: 'middle',
width: 100,
scaleToFit: true
})
/>
```
2. `<Axis />` components got a new prop `tickComponent` to enable rendering of custom ticks. With this prop one can completely customize ticks without having to create a new custom `<Axis />` component.
Example:
```jsx
<Axis
{...axisProps}
tickComponent={({ x, y, formattedValue }) => (
<g>
<circle cx={x} cy={y} r={2} …
```
=> add tickComponent prop and use @vx/text for axis ticks

packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
Allows custom classes to be set, as well as the additional flexibility
- 
- Allows custom classes to be set, as well as the additional flexibility of being able to interface with the underlying Tooltip component
-
- 
-
=> Pass props through to underlying Tooltip component

packages/vx-scale/Readme.md, packages/vx-scale/package.json, packages/vx-scale/src/index.js, packages/vx-scale/src/scales/color/schemeCategory10.js, packages/vx-scale/src/scales/color/schemeCategory20.js, packages/vx-scale/src/scales/color/schemeCategory20b.js, packages/vx-scale/src/scales/color/schemeCategory20c.js, packages/vx-scale/test/schemeCategory10.test.js, packages/vx-scale/test/schemeCategory20.test.js, packages/vx-scale/test/schemeCategory20b.test.js, packages/vx-scale/test/schemeCategory20c.test.js
- Removed color scales, recommending that users look to [`d3-scale-chromatic`](https://github.com/d3/d3-scale-chromatic), following d3's lead in release [5.0.0](https://github.com/d3/d3/releases/tag/v5.0.0)
- The following files/tests/documentation are no longer part of `vx/scale`:
- `schemeCategory10`
- `schemeCategory20`
- `schemeCategory20b`
- `schemeCategory20c`
- N/A
- Added a section on color scales, which goes over how one would use `d3-scale-chromatic` with `vx/scale`
- I tried out my code in a [sandbox](https://codesandbox.io/s/j7jo3k1q49), if you'd like to see it 🙂  
- Fixes #262 
- 🎉
=> Update scales with d3 v5

packages/vx-tooltip/Readme.md, packages/vx-tooltip/src/enhancers/withTooltip.js
These all apply to the `@vx/tooltip` package.
- adds an optional `containerProps` as a second HOC "config" argument of `withTooltip(BaseComponent [, containerProps])`. This exposes a hook to enable users to customize any props on the container element.
- sets `width` and `height` to `inherit` by default on the container. I'm kind of on the edge with this and am open to removing it because it may be an edge case, but my reasoning is as follows: if a user is combining `withTooltip` and a responsive component like `ParentSize` like this example, they'll have to update the `withTooltip` container `div` to also have full width/height so this would be a "smart default".
```css
body, #root { width: 100%; height: 100%; }
```
```js
class ChartWithTooltip extends React.Component {
// ...stuff …
```
=> [tooltip] expose optional containerProps in withTooltip, add tooltip readme

packages/vx-text/src/Text.js
This should fix the bug mentioned in https://github.com/hshoff/vx/issues/267.
I had several problems with this which made me come to the solution of using transforms for this bug fix.  
1. `px` values for `dx` and `dy` were fine and worked.
2. `em` values were fine as long as `fontSize` was explicitly provided for `<Text />`. Without `fontSize` there is no value to use for the transformation from `em -> px` without accessing the DOM.
3. `rem` units had the same problem that there is no way of transforming to `px` without the DOM.
4. I couldn't do `<text dy="1em">...</text>` because the child `<tspan>` defines a `dy` value that overwrites the one from `<text>`. I'm not quite sure why. [example](https://codepen.io/anon/pen/QmexEp)
In the end setting a CSS transform seemed like the easiest …
=> fix: tickLabelProps dy and dx work again

packages/vx-demo/components/tiles/axis.js, packages/vx-demo/pages/axis.js
- [demo] add `<AxisRight />` to /axis demo tile
Confirmed fixes for: https://github.com/hshoff/vx/issues/276 + https://github.com/hshoff/vx/issues/267
=> [demo] add AxisRight to axis demo

packages/vx-demo/components/tiles/barstack.js, packages/vx-demo/pages/barstack.js, packages/vx-grid/src/grids/Columns.js, packages/vx-grid/src/grids/Grid.js, packages/vx-grid/src/grids/Rows.js
- [grid] add support for band scales. fixes https://github.com/hshoff/vx/issues/268
- [demo] demo band scale grid on /barstack
can also change the offset:
```js
<Grid
top={margin.top}
left={margin.left}
xScale={xScale}
yScale={yScale}
width={xMax}
height={yMax}
stroke={'black'}
strokeOpacity={0.1}
xOffset={(xScale.bandwidth() - xScale.step()) / 2}
/>
```
=> [grid] support band scales. fixes #268

packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
Fixes #289 by not passing the `getRects` func prop from `withBoundingRects` to `Tooltip`. 
Tested locally to ensure we no longer get the React error reported (`React does not recognize the 'getRects' prop on a DOM element`)
cc @emepyc
=> [tooltip][TooltipWithBounds] don't pass getRects to Tooltip

packages/vx-geo/Readme.md, packages/vx-geo/src/index.js, packages/vx-geo/src/projections/NaturalEarth.js, packages/vx-geo/src/projections/Projection.js
- No breaking changes
- Adding the Natural Earth (1) projection from https://github.com/d3/d3-geo
> The Natural Earth projection is a pseudocylindrical projection designed by Tom Patterson. It is neither conformal nor equal-area, but appealing to the eye for small-scale maps of the whole world.
=> Adding the Natural Earth projection

packages/vx-shape/Readme.md, packages/vx-shape/src/shapes/Area.js, packages/vx-shape/src/shapes/AreaClosed.js, packages/vx-shape/src/shapes/LinePath.js
See #295 for an explanation of the issue and some related discussion about the components affected.
- Updating accessors to pass all the arguments from D3 for LinePath, AreaClosed, and Area.
- Updating documentation for LinePath and AreaClosed to reflect the above changes. 
Note: Area has no current documentation to update.
=>  [shape] pass d3 accessor arguments to the x and y props of LinePath, AreaClosed, and LinePath #295

packages/vx-chord/.babelrc, packages/vx-chord/.npmrc, packages/vx-chord/Readme.md, packages/vx-chord/package.json, packages/vx-chord/rollup.config.js, packages/vx-chord/src/Chord.js, packages/vx-chord/src/Ribbon.js, packages/vx-chord/src/index.js, packages/vx-chord/test/Chord.test.js, packages/vx-chord/test/Ribbon.test.js, packages/vx-chord/test/enzyme-setup.js, packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/chord.js, packages/vx-demo/package.json, packages/vx-demo/pages/chord.js, packages/vx-heatmap/src/heatmaps/circle.js, packages/vx-shape/src/shapes/LinePath.js
- [chord] add `@vx/chord` - `<Chord />`, `<Ribbon />`
- [demo][shape] add chord demo, fix prop types
fixes: https://github.com/hshoff/vx/issues/189
=> [chord][demo] add @vx/chord. fixes #189

packages/vx-shape/src/shapes/Pie.js
I'd like to be able to animate a pie chart but for most animation frameworks, we need access to the children groups in order to modify the path parameters. By adding an optional render function, we can add animation to the pie chart while allowing users to choose their own animation framework.
None
- Add optional render function as child of Pie to allow more fine grained control of rendering.
=> Support Custom Rendering For Pie Charts

packages/vx-grid/package.json
I was updating all of the `@data-ui` deps to use the new build and encountered an issue with deep-importing from `@vx/grid` because the `build` directory was missing, I think due to it not being included under `files` in the `package.json`.
I looked in all of the other packages and didn't see `build` missing so this is probably the only case 👍
=> [grid] include `build/` dir in package

packages/vx-shape/src/shapes/AreaClosed.js
- Adds optional y0 for custom area fills
- Primary Example: show negative area as integral
- I know typical pattern is for y0 to be an accessor passed to yScale, which isn't flexible enough in this case. Interested to hear thoughts and happy to refactor to fit project patterns.
```
const stock = appleStock.slice(800).map((val, index) => ( index < 250
? val
: { ...val, close: -val.close })
);
....
<AreaClosed
data={stock}
xScale={xScale}
yScale={yScale}
x={xStock}
y={yStock}
y0={Math.min(yScale(0), yScale.range()[0])}
strokeWidth={1}
stroke={'url(#gradient)'}
fill={'url(#gradient)'}
/>
```
=> [area-closed] add optional y0 for custom area fills

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/bargrouphorizontal.js, packages/vx-demo/pages/bargrouphorizontal.js, packages/vx-shape/Readme.md, packages/vx-shape/src/index.js, packages/vx-shape/src/shapes/BarGroupHorizontal.js, packages/vx-shape/test/BarGroupHorizontal.test.js
Been using this library a little while now and really enjoying it, thank you! I needed this twist on the `BarGroup` component and wanted to contribute back.
- [shape] adds `<BarGroupHorizontal />` component
- Adds documentation for `<BarGroup />` and `<BarGroupHorizontal />`
=> [shape] Add <BarGroupHorizontal /> component

packages/vx-shape/src/shapes/Pie.js, packages/vx-shape/test/Pie.test.js
[`pie.sortValues(null)`](https://github.com/d3/d3-shape#pie_sortValues) turns off the default sorting, but before this PR `pie.sort` was never called with a `null` value. Hopefully this isn't a breaking change.
- `<Pie pieSort={null} pieSortValues={null} />` isn't ignored
=> <Pie /> Allow null sort callbacks

packages/vx-demo/components/tiles/heatmap.js, packages/vx-heatmap/src/heatmaps/circle.js, packages/vx-heatmap/src/heatmaps/rect.js
The heatmap demo overflows on the top (see the white half circle):
This is due to the way the y-positions of the heatmap elements are calculated. This can be simplified by using the array lengths to calculate the positions (imho the cleaner way).
This is what the updated Heatmap demo looks like:
----
- Different `vx-heatmap` API
- Cleaner `vx-heatmap` API, better Heatmap layout
- Adds a separation attribute (margin between the two heatmaps) to the heatmap demo
- Removes usage of `data[0].bins.length` as reference bins length, calculates maximum
- Fixes broken Heatmap demoo
- Removes hardcoded left margin of 5
=> Cleaned up and simplified heatmaps

README.md
- added a new demo repo to the readme file
- demo exists in perpetuity on heroku at https://codecov-dash.herokuapp.com/
- repo exists at https://github.com/ezy/code-coverage-dashboard
=> add new demo of code coverage dash

packages/vx-axis/src/utils/labelTransform.js
- Fix `labelTransform` function in *@vx/axis* to correctly align the axis label when different values for the scale's *range* are specified, in particular when it does not start (or end) with a 0.
To give a visual example, take a scale defined as below(same as [this](https://github.com/hshoff/vx/blob/master/packages/vx-demo/components/tiles/axis.js#L43#L47), but with a slightly different range): 
```
const yScale = scaleLinear({
range: [yMax, yMax / 2],
domain: [0, max(data, y)],
nice: true
});
```
this is what we get with the current code(which basically uses a `Math.max(...range) / 2` to compute the center):  
while this is the same example with the fix:
=> Fix label transform computation

.eslintignore, package.json
- add linting
- fix #128 
If you run `npm run lint`, you would discover there are:
```bash
✖ 10557 problems (10488 errors, 69 warnings)
6731 errors and 0 warnings potentially fixable with the `--fix` option.
```
lol 😂
=> [development] add linting

packages/vx-demo/pages/boxplot.js
Source to match code in https://github.com/hshoff/vx/blob/master/packages/vx-demo/components/tiles/boxplot.js#L6
References previous merge request #350
Prettier has stripped `return` statement from `export default()` on commit.
=> update boxplot example 

packages/vx-demo/components/gallery.js, packages/vx-demo/components/tiles/polygons.js, packages/vx-demo/pages/polygons.js, packages/vx-shape/Readme.md, packages/vx-shape/src/index.js, packages/vx-shape/src/shapes/Polygon.js, packages/vx-shape/src/util/trigonometry.js, packages/vx-shape/test/Polygon.test.js
I have added a new simple `<Polygon />` component that takes `sides` and `length` props and does the rest.  I have added it to `vx-shape`
```js
// hexagon
<Polygon sides={6} size={25} {...additionalProps} />
```
-
I have added a demo to `vx-demo` and updated the vx-shape README
-
=> add <Polygon /> to vx-shape

packages/vx-text/src/util/getStringWidth.js
fixes document height issues
- measurement svg is now hidden from view to avoid document sizing issues
- #356
=> add display:none to getStringWidth svg

packages/vx-responsive/src/components/ParentSize.js
- [responsive] remove `debounceTime` prop from `restProps`
quick fix for: https://github.com/hshoff/vx/pull/363
=> [responsive] remove debounceTime prop from restProps

packages/vx-scale/src/scales/band.js, packages/vx-scale/src/scales/linear.js, packages/vx-scale/src/scales/log.js, packages/vx-scale/src/scales/ordinal.js, packages/vx-scale/src/scales/point.js, packages/vx-scale/src/scales/power.js, packages/vx-scale/src/scales/quantile.js, packages/vx-scale/src/scales/quantize.js, packages/vx-scale/src/scales/threshold.js, packages/vx-scale/src/scales/time.js, packages/vx-scale/src/scales/utc.js
- Add `type` property as utility to scales to do specific actions or use specific interfaces from "agnostic" contexts.
=> add scale type

packages/vx-legend/src/legends/Legend.js, packages/vx-legend/src/legends/LegendLabel.js
- Add optional `flex` prop for overriding `flex` css property to LegendLabel
- Allow overriding flex property to fix [IE flexbox bug](https://stackoverflow.com/questions/39192995/flex-container-wont-expand-to-fit-content-in-ie). IE 11 does not seem to expand to minimum content width when flex-basis is 0px (this is the case when using the shorthand `flex: 1`).
I encountered a bug with the LegendLabel layout on IE11, and setting the flex property to `flex: auto` fixed it. I was hesitant to change the style for all usages, so I added an optional `flex` prop to `Legend` and `LegendLabel`.
=> Add optional flex prop to LegendLabel

packages/vx-grid/Readme.md, packages/vx-grid/src/grids/Columns.js, packages/vx-grid/src/grids/Grid.js, packages/vx-grid/src/grids/Rows.js
- Allow passing in tickValues prop to both Columns and Rows, to render grid lines at specific values.
- Allow passing in rowTickValues prop and columnTickValues prop to Grid
- Update vx-grid's Readme.md to reflect the changes above
One of the benefits of this feature is that it allows the alignment of grid lines to the tickValues passed into Axis components.
=> [grid] Add tickValues prop

packages/vx-grid/Readme.md, packages/vx-grid/src/grids/Columns.js, packages/vx-grid/src/grids/Grid.js, packages/vx-grid/src/grids/Rows.js
This PR
- updates `strokeWidth` `propTypes` in the `@vx/grid` components to allow numbers in addition to strings. 
- updates the readme and changes component names to reflect the component names exported in the package `index.js`
=> [grid] allow number `strokeWidth`s

packages/vx-tooltip/src/tooltips/TooltipWithBounds.js
- From experiment, it appears that fractional pixel values can sometimes lead to shaky rendering when using Firefox. Fixes #388.
=> [tooltip][TooltipWithBounds] Use integer pixel values for translation

packages/vx-responsive/src/components/ScaleSVG.js, packages/vx-responsive/test/ScaleSVG.test.js
add the ability to add a ref to `ScaleSVG`
I currently need a ref in the svg rendered from `ScaleSVG`.
```
<svg
preserveAspectRatio={preserveAspectRatio}
viewBox={`${xOrigin} ${yOrigin} ${width} ${height}`}
ref={innerRef}
>
{children}
</svg>
```
=> add innerRef prop to ScaleSVG in @vx/responsive

packages/vx-tooltip/Readme.md
- The **Tooltip** title wasn't visible in the `Components` section of the vx-tooltip readme
- There were as well some typos in the file
=> Make Tooltip title visible under component section in the vx-tooltip readme file

packages/vx-demo/static/docs/vx-bounds.html, packages/vx-demo/static/docs/vx-geo.html, packages/vx-demo/static/docs/vx-mock-data.html, packages/vx-demo/static/docs/vx-pattern.html, packages/vx-demo/static/docs/vx-point.html, packages/vx-demo/static/docs/vx-responsive.html, packages/vx-demo/static/docs/vx-tooltip.html, packages/vx-geo/Readme.md, packages/vx-geo/docs/api.md, packages/vx-geo/docs/docs.md, packages/vx-geo/package.json, packages/vx-geo/src/index.js, packages/vx-geo/src/projections/EqualEarth.js, packages/vx-geo/src/projections/Projection.js, packages/vx-geo/test/EqualEarth.test.js
- Adds the Equal Earth projection to @vx/geo. Equal Earth is pretty new (was added to d3-geo a couple months ago), but is becoming increasingly popular because it doesn't really distort land masses and their areas. See [this](https://www.gislounge.com/equal-earth-map-projection/) for more info.
=> Add Equal Earth projection to @vx/geo

packages/vx-responsive/docs/api.md, packages/vx-responsive/docs/docs.md, packages/vx-responsive/src/components/ScaleSVG.js
I got warning with **ScaleSVG** component:
```javascript
import { ScaleSVG } from "@vx/responsive";
...
<ScaleSVG width={400} height={200}>
<LineRadial width={500} height={200} />
</ScaleSVG>
...
```
[![Edit 98yx2qvryp](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/98yx2qvryp)
```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `n`, expected `function`.
```
So I suppose it should be **PropTypes.any** for **ScaleSVG** component
=> Fix-VX-Responsive-ScaleSVG-PropTypes

packages/vx-demo/pages/bargrouphorizontal.js
- None, only updated string value.
- N/A
- No need to update any additional documentation
- As a d3 first-timer and react long-timer, I was excited to dip my toes in with vx. I followed the demo code, however I was struck with an angry error screen:
After a bit of debugging I realized the issue lay with the demo code. The `children` fn parameter in the demo code was expecting an argument to destructure and then map over the resulting `barGroups` value. However in the BarGroupHorizontal component in `vx/packages/vx-shape/src/shapes/BarGroupHorizontal.js` on line 66 it was only ever being passed one argument of type array. Therefore, removing the unnecessary destructuring of `barGroups` resolved the issue.
- N/A
=> [shape/BarGroupHorizontal] Remove unnecessary destructuring of props in demo code

packages/vx-shape/src/shapes/LinePath.js
- Fixes a proptype for the LinePath `defined` prop. Should use `oneOfType` rather than `oneOf`.
=> Fix proptype for LinePath 'defined' prop

packages/vx-demo/pages/drag-ii.js
- Remove unused localPoint import
- Remove xScale and yScale props from the LinePath. Using them on the current implementation of the line path throws the error shown below and they are no longer part of the [props](https://github.com/hshoff/vx/blob/master/packages/vx-shape/Readme.md#linepath-) of the LinePath in the current implementation.
=> Cleanup DragII Demo

packages/vx-demo/pages/barstack.js
- fixed broken BarStacks example. Bar Stack Horizontal example works correct, but BarStack for some reason uses `({ barStacks })` instead of `barStacks`
=> Fixed broken BarStacks example

package.json, packages/vx-responsive/src/components/ParentSize.js
fixes #258 
- [responsive] `<ParentSize />` replace `for..of` with `forEach()` to fix IE11 error without having to sham `Symbol`. More info: https://github.com/hshoff/vx/issues/258
=> [responsive] ParentSize for..of => entries.forEach to fix ie11. fixes #258

packages/vx-responsive/src/components/ParentSize.js
fixes: https://github.com/hshoff/vx/issues/436
- [responsive] add debounceTime back to prevent it spreading on children through restProps. fixes #436
=> [responsive] remove debounceTime from restProps. fixes #436

packages/vx-glyph/Readme.md
- [glyph] fixes outdated `@vx/glyph` examples in the readme docs. fixes https://github.com/hshoff/vx/issues/452
=> [glyphs] update outdated glyphs docs. fixes #452

packages/vx-text/package.json
Noticed these were being pulled in when installing the package, so moving to dev dependencies since they aren't referenced in the source.
- Move Babel dependencies to dev only.
=> Move Babel deps to dev only

packages/vx-demo/components/tiles/zoom-i.js, packages/vx-demo/static/docs/vx-zoom.html, packages/vx-zoom/Readme.md, packages/vx-zoom/docs/api.md, packages/vx-zoom/docs/docs.md, packages/vx-zoom/src/Zoom.js
Chrome 73 made `wheel` event listeners passive by default.  A passive event listener is an event listener that does not call `preventDefault()` on the event. This is great because it makes scrolling faster. [https://developers.google.com/web/updates/2019/02/scrolling-intervention](https://developers.google.com/web/updates/2019/02/scrolling-intervention).
Google found 98% of `wheel` and `mousewheel` event listeners do not call `preventDefault()`. So the trade off here of faster scrolling on the web for the relatively small cost of 2% of listeners need to opt-in to making the wheel listener active. Unfortunately, `<Zoom />` falls in the 2% here.
Convert event listeners that rely on `preventDefault()` to active.
```diff
- node.addEventListener('wheel', this.handleWheel);
+ …
```
=> [zoom] make wheel event active by default. fixes #455

packages/vx-shape/src/shapes/Arc.js, packages/vx-shape/src/shapes/Pie.js, packages/vx-shape/test/Arc.test.js
- [shape] `<Arc />` and `<Pie pieValue={} />` props now check for `!== undefined`. Before `0` wouldn't set the prop to `0` because `if (0)` is `false`. This is only a breaking change if you were passing `0` before and happy with `<Arc />` treating that as `undefined` and using d3.arc() defaults.
- [shape] `<Arc />` now respects `0` as an allowed prop value
- [shape] `<Pie />`  `pieValue` now respects `0` as an allowed prop value
- [shape] add more `<Arc />` tests
- [shape] convert `Arc.test` from `CRLF` => `LF`
=> [shape] add arc prop undefined checks. fixes #462

packages/vx-heatmap/src/heatmaps/HeatmapRect.js
- [heatmap] remove `bin.x0`. The x0 offset is accounted for in `bin.x`. fixes #474
=> [heatmap] rm bin.x0. fixes #474

packages/vx-boxplot/src/boxplots/BoxPlot.js
- 
-
-
:bug: Bug Fix
-  Described in issue #471 displaying boxplots horizontally causes the rectangle to be displayed in the wrong location.
-
=> Fix rectangle displaying incorrectly for horizontal layouts

packages/vx-boxplot/src/boxplots/BoxPlot.js, packages/vx-stats/src/boxplot/BoxPlot.js
Counterpart to https://github.com/hshoff/vx/pull/472 which fixes the bug in `@vx/boxplot`. Eventually the plan is deprecate `@vx/boxplot` in favor of `@vx/stats`. Until then, we'll need to update both. 
- [stats] fix horizontal boxplot in @vx/stats
=> [stats] fix horizontal boxplot in @vx/stats

packages/vx-text/src/Text.js
- Don't split strings rendered by `<Text />` when encountering a set of non-breaking space characters. Currency strings output by Number.toLocaleString, for example, can contain non-breaking space characters. The emitted SVG tspan elements (words) should not be split by these characters.
=> Don't split words on non-breaking space char

packages/vx-scale/package.json
Counterpart to https://github.com/hshoff/vx/pull/470 which makes sure the correct `d3-scale` version is installed to support the addition of `scaleSymlog`.
- [scale] [d3-scale 2.2.2 changed](https://github.com/d3/d3-scale/issues/117) the behavior of a collapsed domain. See [this comment](https://github.com/hshoff/vx/issues/473#issuecomment-508203310) for how to handle the updated behavior.
- [scale] bump d3-scale dep to `^2.2.2` for scaleSymlog
_Sidenote_: Since `d3-scale` [added convenience constructors](https://github.com/d3/d3-scale/issues/157) (`scale(domain, range)`) we may deprecate `@vx/scale` in favor of `d3-scale` in the future. Currently, `@vx/scale` only adds two additional behaviors around d3-scale: Convenience constructors (as named args: `scale({ domain, range })`) and a …
=> [scale] bump d3-scale dep for scaleSymlog

package.json
Should fix the broken build on master https://travis-ci.org/hshoff/vx/builds/591675984
- [eslint] disable `no-useless-name`
=> [root] disable no-useless-rename

package.json
Some reason lint fails on travis-ci but passes locally. 
- [eslint] turn off react/jsx-curly-brace-presence
=> [eslint] turn off react/jsx-curly-brace-presence

packages/vx-bounds/src/index.ts, packages/vx-chord/src/Ribbon.tsx, packages/vx-network/src/Graph.tsx, packages/vx-shape/src/shapes/BarStack.tsx, packages/vx-shape/src/shapes/LineRadial.tsx
This PR fixes a few things
- Closes #542, where `type` exports in `@vx/bounds` and `@vx/shape` were not handled correctly in the `esm/` build. 
- It seems that the `export { TypeName, VariableName } from '...'` and `export { TypeName }` syntax doesn't correctly distinguish TS `type`s / `interface`s from JS variables, and since `types` are not generated for `esm/` this gives unresolved errors in the `demo` packages which imports from `esm/`
- This seems to be resolved with more explicit `type` exports: the demo builds without error, and the `type`s don't show up in the `esm/` files any more
- Loosens requirements for some `type`s that I noticed were giving errors in the demo: 
- `@vx/network` `Graph` 
- `@vx/shape` `LineRadial`
- `@vx/chord` `Ribbon`
@hshoff
=> fix(network, shape, chord, bounds): Fix type exports + misc component types

README.md
As noted in #542, the `readme` doesn't include the changes introduced in #484 for using `yarn` workspaces and `nimbus`. This PR updates accordingly.
@hshoff
=> docs(Readme): Add `yarn` and `nimbus` deets

packages/vx-demo/src/pages/docs.js
There are lots of packages in navigation sidebar that aren't displayed on the package list page:
https://vx-demo.now.sh/docs
I left out a few that don't really have docs:
- `demo` 
- `vx` 
- `brush`
- `event`
-
-
-
-
-
=> [docs] add more packages to package list page

packages/vx-demo/src/components/tiles/bargrouphorizontal.js, packages/vx-demo/src/pages/bargrouphorizontal.js, packages/vx-shape/src/shapes/BarGroupHorizontal.tsx
Fixes #573.
- [shape] `BarGroupHorizontal` now takes an uninverted `xScale`.
=> Uninvert BarGroupHorizontal x scale

packages/vx-demo/src/components/tiles/chord.js, packages/vx-demo/src/pages/chord.js
This PR updates the chord diagram.
1. The linear gradients are replaced by static colors to better show what is going on.
2. The coloring of the ribbons is fixed. Previously, the coloring function was used identically for the arcs and ribbons (using the index), but that doesn't work for ribbons, as the index of a ribbon is not related to the index of the arcs (resulting in a ribbon coloring that doesn't make sense). Now, the index of the target group is used to color the ribbons.
3. The code example of the chord graph is updated accordingly.
**Old**:
Notice how the coloring of the ribbons with identical source and target group is different than the coloring of that group. I suppose that this wasn't noticed because of the gradients :smile:
**New**:
=> Update Chord Diagram example to make more sense

packages/vx-demo/src/components/gallery.js, packages/vx-demo/src/components/tiles/Statsplot.tsx, packages/vx-demo/src/pages/Statsplot.tsx, packages/vx-responsive/src/enhancers/withParentSize.tsx, packages/vx-responsive/src/enhancers/withScreenSize.tsx, packages/vx-scale/src/scales/band.ts, packages/vx-stats/src/types.ts, packages/vx-tooltip/src/enhancers/withTooltip.tsx
This PR is part of #579 to re-write the `vx-demo` site in TypeScript. It re-writes the `Statsplot` example in TypeScript.
**Before/After**
- Fixes the types for `ProvidedProps` vs `BaseComponentProps` for `withTooltip`, `withScreenSize`, and `withParentSize` in `@vx/responsive` and `@vx/tooltip`
- Makes `TooltipData` a generic in `withTooltip` for better consumer experience
- Fixes a `.range()` type issue with `GenericScale in the `@vx/stats` package
cc @hshoff @kristw @schillerk
=> typescript(vx-demo): rewrite StatsPlot example in TypeScript

packages/vx-demo/src/components/gallery.js, packages/vx-demo/src/components/tiles/Gradients.tsx, packages/vx-demo/src/components/tiles/Polygons.tsx, packages/vx-demo/src/pages/Gradients.tsx, packages/vx-demo/src/pages/Polygons.tsx, packages/vx-scale/src/scales/band.ts
This PR is part of #579 to re-write the `vx-demo` site in TypeScript. It re-writes the `gradients` + `polygons` examples in TypeScript and makes a fix to `scaleBand`.
**Before/After**
Fixes `@vx/scale`s `scaleBand` `StringLike` generic to accept anything coercible to strings. The previous syntax was wrong/used coercible number syntax.
cc @hshoff @kristw @schillerk
=> typescript(vx-demo): re-write Gradients + Polygons demos in TypeScript

packages/vx-text/src/Text.tsx
- [text] Remove deprecated lifecycles used in Text
Fixes #396. Closes #431. I thought I might as well take a crack at converting the deprecated lifecycles to something better. I was gonna use hooks but I have no idea if I can use it yet.
=> Change Text's use of deprecated lifecycle

packages/vx-demo/src/components/tiles/Legends.tsx, packages/vx-demo/src/pages/Legends.tsx, packages/vx-legend/src/legends/Linear.tsx, packages/vx-legend/src/legends/Threshold.tsx
This PR closes #605 where `@vx/legend`'s `LegendThreshold` does not generate the correct number of labels after the `TS` re-write.
**More context**
Without a major refactor, the base `Legend` generates its labels from the `domain` of the input `scale`. However for `threshold` (and `quantile`) scales,[ if the `domain` contains `n` threshold values, the `range` should include `n+1` values](https://github.com/d3/d3-scale#threshold_domain) to capture both the `less than domain[0]` and `greater than domain[1]` intervals of the thresholds.
**The fix**
- Previously this wasn't accounted for and thus `LegendThreshold` did not include the last value in range as seen in the linked issue. This updates `LegendThreshold` to instead behave like `LegendQuantile` to effectively allow label generation …
=> fix(vx-legend): Fix label generation in `Threshold` legend

packages/vx-responsive/src/enhancers/withParentSize.tsx, packages/vx-responsive/src/enhancers/withScreenSize.tsx
Fixes #619 where the TS re-write introduced a regression wherein the state is initialized with `undefined`, while the render method checks for `null`s
@hshoff @kristw 
cc @dson
=> fix(vx-responsive): fix enhancer parent/screen size checks

packages/vx-zoom/src/Zoom.tsx
In the Zoom package, the constrain function initially took a reference to the constrain prop once on mount. During subsequent renders the function never updated when the prop did.
This PR changes it so that this.props.constrain function will always be the most recent reference. This is important when working with hooks and useCallback made functions, which will create a new reference with updates.
- Im not sure if this was intentional, after all it very well could be
- [#622](https://github.com/hshoff/vx/issues/622)
=> Fixed Zoom constrain prop to work with useCallback made functions

packages/vx-tooltip/Readme.md, packages/vx-tooltip/src/enhancers/withTooltip.tsx, packages/vx-tooltip/test/withTooltip.test.ts, packages/vx-tooltip/test/withTooltip.test.tsx
- Addresses #609, enabling the `withTooltip` enhancer to be used on components that render within an SVG, such as `Axis`
- Since this removes the container `div` added by `withTooltip`, any implementations relying on the container would have to instead add such a container around their wrapped component themselves.  To me it looks like a more flexible approach since it allows any component to be enhanced using `withTooltip`, but there may be use cases or context I'm not aware of here!
=> Allow withTooltip to be used to enhance components rendered within an SVG element

packages/vx-demo/src/components/tiles/BarStack.tsx, packages/vx-demo/src/pages/BarStack.tsx, packages/vx-tooltip/Readme.md, packages/vx-tooltip/package.json, packages/vx-tooltip/src/enhancers/withTooltip.tsx, packages/vx-tooltip/src/hooks/useTooltip.ts, packages/vx-tooltip/src/index.ts, packages/vx-tooltip/test/useTooltip.test.tsx
- Add a `useTooltip` hook to manage tooltip state for functional components, as discussed in https://github.com/hshoff/vx/issues/609
- This PR introduces `useState`, which requires bumping the `peerDep` for react to `^16.8.0-0`
- Update `vx-tooltip` readme to include the new `useTooltip` hook, and recommend a state management approach depending on use case (specifically: recommending `useTooltip` for functional components, or `withTooltip` for class components)
- Rewrite the `BarStack` demo to use `useTooltip` instead of `withTooltip`, so there is an example of each approach to managing tooltip state in the gallery (`BarStack` for `useTooltip`, `BarStackHorizontal` for `withTooltip`)
- Rewrote `withTooltip` in terms of `useTooltip`, to avoid maintaining multiple different implementations
=> Add useTooltip hook

packages/vx-tooltip/src/hooks/useTooltip.ts
- Fixing a few linter errors regarding shadowed variables that I didn't catch when I submitted https://github.com/hshoff/vx/pull/631, and which don't seem to be flagged as part of the Travis build (see: https://github.com/hshoff/vx/issues/638).
=> style(vx-tooltip): resolve linter errors (no-shadow)

.travis.yml
- Consolidated the `matrix` and `jobs` configuration in `.travis.yml`, since those two keys override each other.  This was causing Travis to run the default test script (`yarn test`) instead of running both the test and lint steps as desired (closes https://github.com/hshoff/vx/issues/638).
~~Note: the CI build for this this will (correctly) fail, since the linter will throw errors until https://github.com/hshoff/vx/pull/639 is merged.~~ I've rebased over the latest master and force pushed, so I'd expect CI to pass now 🤞
=> ci(travis): Move fast_finish to jobs key

README.md
Additionally, should the section header above this fix be `Rebuild one package` (one instead of on)?
- Fix typo in root readme
=> Fix typo within readme

packages/vx-brush/src/BaseBrush.tsx, packages/vx-brush/src/Brush.tsx, packages/vx-brush/src/types.ts
- None
- Brush now listens to when a mouseup event happens on the window to disable brush drag
- Brush accepts an optional prop to default the scrubber state to an initial value
-
-
-
=> new(vx-brush): handle mouseup outside of Brush extent

packages/vx-tooltip/Readme.md, packages/vx-tooltip/package.json, packages/vx-tooltip/src/index.ts, packages/vx-tooltip/src/tooltips/Tooltip.tsx, packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx, packages/vx-tooltip/test/Tooltip.test.tsx
-
- Enable users to use or remove default tooltip styles
- Update tooltip docs
-
-
Fixes https://github.com/hshoff/vx/issues/650
=> Remove tooltip default styles

packages/vx-brush/src/BaseBrush.tsx, packages/vx-brush/src/Brush.tsx, packages/vx-brush/src/types.ts, packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/components/tiles/Brush.tsx, packages/vx-tooltip/test/Tooltip.test.tsx
This fixes some problems with the implementation of `initialBrushPosition` from #618 
- the type `BrushStartEnd` expected both `x` and `y` of `start`/`end` to be defined, which doesn't work if you have a `vertical-` or `horizontal-`only brush. Fixed to handle partials.
- the initial brush worked if you dragged in a new position, or extended a side, but not if you dragged the initial brush window. to fix this I updated some of the initial `state.start/end` logic which is used by `BrushSelection` upon moving a selection.
**Before**
**After**
Also updates the demo to include an `initialBrushPosition` which should be useful for peeps
Jest was failing locally to collect coverage due to a missing react component function name. I added one to fix locally, and see if it fixes anything on CI. …
=> fix(vx-brush): Fix initialBrushPosition

packages/vx-tooltip/src/hooks/useTooltip.ts
When using `useTooltip` introduced in #631 I noticed that passing `showTooltip` or `hideTooltip` to a child component causes unnecessary and potentially expensive render cascades / child updates even though `tooltipLeft`, `tooltipTop`, or `tooltipData` didn't change.
This should be fixable by using the `useCallback` hook, where the callbacks are not instantiated each render, and thus `PureComponent`s or `React.memo`ized components should not update unless `tooltipLeft`, `tooltipTop`, or `tooltipData` update.
cc @ptmx
=> perf(vx-tooltip): use useCallback in useTooltip

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-chord/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-chord/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-chord/package.json, packages/vx-demo/src/docs-v2/examples/vx-chord/sandbox-styles.css, packages/vx-demo/src/pages/Chord.tsx
Part of #624, re-writes the `Chord` demo to link out to code-sandbox. [Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-chord/packages/vx-demo/src/docs-v2/examples/vx-chord?file=/index.tsx) (update branch to master upon merge).
=> new(vx-demo): convert Chord to codesandbox example

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-pack/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-pack/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-pack/package.json, packages/vx-demo/src/docs-v2/examples/vx-pack/sandbox-styles.css, packages/vx-demo/src/pages/Pack.tsx
Part of #624, re-writes the `Pack` demo to link out to code-sandbox. [Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-pack/packages/vx-demo/src/docs-v2/examples/vx-pack) (update branch to master upon merge).
=> new(vx-demo): convert Pack demo to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-radar/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-radar/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-radar/package.json, packages/vx-demo/src/docs-v2/examples/vx-radar/sandbox-styles.css, packages/vx-demo/src/pages/Radar.tsx
Part of #624, re-writes the `Radar` demo to link out to code-sandbox. [Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-radar/packages/vx-demo/src/docs-v2/examples/vx-radar) (update branch to master upon merge).
=> new(vx-demo): convert Radar to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-zoom-i/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-zoom-i/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-zoom-i/package.json, packages/vx-demo/src/docs-v2/examples/vx-zoom-i/sandbox-styles.css, packages/vx-demo/src/pages/Zoom-i.tsx
Part of #624, re-writes the `ZoomI` demo to link out to code-sandbox. [Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-zoom/packages/vx-demo/src/docs-v2/examples/vx-zoom-i) (update branch to master upon merge).
=> new(vx-demo): convert ZoomI to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-treemap/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-treemap/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-treemap/package.json, packages/vx-demo/src/docs-v2/examples/vx-treemap/sandbox-styles.css, packages/vx-demo/src/pages/Treemap.tsx
Part of #624, re-writes the `Treemap` demo to link out to code-sandbox. Would love to make this animated but will save for a future update.
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-treemap/packages/vx-demo/src/docs-v2/examples/vx-treemap) (update branch to master upon merge).
=> new(vx-demo): convert Treemap to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-bars/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-bars/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-bars/package.json, packages/vx-demo/src/docs-v2/examples/vx-bars/sandbox-styles.css, packages/vx-demo/src/pages/Bars.tsx
Part of #624, re-writes the `Bars` demo to link out to code-sandbox. 
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-bars/packages/vx-demo/src/docs-v2/examples/vx-bars) (update branch to master upon merge).
=> new(vx-demo): convert Bars to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/components/Show.tsx, packages/vx-demo/src/docs-v2/examples/vx-threshold/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-threshold/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-threshold/package.json, packages/vx-demo/src/docs-v2/examples/vx-threshold/sandbox-styles.css, packages/vx-demo/src/pages/Threshold.tsx
Part of #624, re-writes the `Threshold` demo to link out to code-sandbox. 
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-threshold/packages/vx-demo/src/docs-v2/examples/vx-threshold) (update branch to master upon merge).
=> new(vx-demo): convert Threshold to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-barstack-horizontal/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-barstack-horizontal/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-barstack-horizontal/package.json, packages/vx-demo/src/docs-v2/examples/vx-barstack-horizontal/sandbox-styles.css, packages/vx-demo/src/docs-v2/examples/vx-barstack/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-barstack/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-barstack/package.json, packages/vx-demo/src/docs-v2/examples/vx-barstack/sandbox-styles.css, packages/vx-demo/src/pages/BarStack.tsx, packages/vx-demo/src/pages/BarStackHorizontal.tsx, packages/vx-tooltip/Readme.md
Part of #624, re-writes the `BarStack` and `BarStackHorizontal` demos to link out to code-sandbox. Links: [BarStack](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-barstack/packages/vx-demo/src/docs-v2/examples/vx-barstack), [BarStackHorizontal](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-barstack/packages/vx-demo/src/docs-v2/examples/vx-barstack-horizontal) (update branches to master upon merge).
It also updates the `@vx/tooltip` readme to fix #675 
Stack
Horizontal stack
=> new(vx-demo): convert BarStack, HorizontalBarStack to codesandbox

packages/vx-event/src/getXAndYFromEvent.ts
Zoom component's zoom.dragMove worked incorrectly on touchmove event, moving only alongside 135 degree angle. Fixing the typo fixes this problem.
=> fix getting coords from touch event for y typo

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-area/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-area/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-area/package.json, packages/vx-demo/src/docs-v2/examples/vx-area/sandbox-styles.css, packages/vx-demo/src/docs-v2/examples/vx-stacked-areas/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-stacked-areas/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-stacked-areas/package.json, packages/vx-demo/src/docs-v2/examples/vx-stacked-areas/sandbox-styles.css, packages/vx-demo/src/pages/Areas.tsx, packages/vx-demo/src/pages/Stacked-Areas.tsx
Part of #624, re-writes the `Areas` and `StackedAreas` demos to link out to code-sandbox. 
Links: [StackedAreas](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-stackedareas/packages/vx-demo/src/docs-v2/examples/vx-stacked-areas), [Areas](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-stackedareas/packages/vx-demo/src/docs-v2/examples/vx-area) (update branch to master upon merge).
**StackedAreas**
**Areas**
=> new(vx-demo): convert Areas, StackedAreas to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-bargroup-horizontal/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-bargroup-horizontal/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-bargroup-horizontal/package.json, packages/vx-demo/src/docs-v2/examples/vx-bargroup-horizontal/sandbox-styles.css, packages/vx-demo/src/docs-v2/examples/vx-bargroup/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-bargroup/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-bargroup/package.json, packages/vx-demo/src/docs-v2/examples/vx-bargroup/sandbox-styles.css, packages/vx-demo/src/pages/BarGroup.tsx, packages/vx-demo/src/pages/BarGroupHorizontal.tsx
Part of #624, re-writes the `BarGroup` and `BarGroupHorizontal` demos to link out to code-sandbox. Links: [BarGroup](https://codesandbox.io/s/github/hshoff/vx/tree/chris--bargroup/packages/vx-demo/src/docs-v2/examples/vx-bargroup), [BarGroupHorizontal](https://codesandbox.io/s/github/hshoff/vx/tree/chris--bargroup/packages/vx-demo/src/docs-v2/examples/vx-bargroup-horizontal) (update branches to master upon merge).
**BarGroup**
**BarGroupHorizontal**
**Gallery**
=> new(vx-demo): convert BarGroup, BarGroupHorizontal to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-dendrogram/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-dendrogram/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-dendrogram/package.json, packages/vx-demo/src/docs-v2/examples/vx-dendrogram/sandbox-styles.css, packages/vx-demo/src/pages/Dendrograms.tsx
Part of #624, re-writes the `Dendrogram` demo to link out to code-sandbox. 
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-dendrogram/packages/vx-demo/src/docs-v2/examples/vx-dendrogram) (update branch to master upon merge).
=> new(vx-demo): convert Dendrogram to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-network/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-network/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-network/package.json, packages/vx-demo/src/docs-v2/examples/vx-network/sandbox-styles.css, packages/vx-demo/src/pages/Network.tsx
Part of #624, re-writes the `Network` demo to link out to code-sandbox. 
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-network/packages/vx-demo/src/docs-v2/examples/vx-network) (update branch to master upon merge).
=> new(vx-demo): convert Network to codesandbox

packages/vx-demo/src/components/Gallery.tsx, packages/vx-demo/src/docs-v2/examples/vx-polygons/Example.tsx, packages/vx-demo/src/docs-v2/examples/vx-polygons/index.tsx, packages/vx-demo/src/docs-v2/examples/vx-polygons/package.json, packages/vx-demo/src/docs-v2/examples/vx-polygons/sandbox-styles.css, packages/vx-demo/src/pages/Polygons.tsx
Part of #624, re-writes the `Polygons` demo to link out to code-sandbox. 
[Link](https://codesandbox.io/s/github/hshoff/vx/tree/chris--sandbox-polygons/packages/vx-demo/src/docs-v2/examples/vx-polygons) (update branch to master upon merge).
=> new(vx-demo): convert Polygons to codesandbox

packages/vx-tooltip/Readme.md, packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx, packages/vx-tooltip/test/TooltipWithBounds.test.tsx
-
- Add unstyled prop to TooltipWithbounds
- Update Tooltips documentation
- Make Typescript happy when the `unstyled` prop is passed to `TooltipWithBounds`
-
Fixes https://github.com/hshoff/vx/issues/691
=> Fix tooltip with bounds

packages/vx-responsive/src/components/ParentSize.tsx, packages/vx-responsive/src/enhancers/withParentSize.tsx, packages/vx-responsive/src/enhancers/withScreenSize.tsx
Debounce calls can still fire after unmount, so we need to cancel them.
=> Fix debounced calls after unmount in responsive components

packages/vx-responsive/src/components/ParentSize.tsx, packages/vx-responsive/src/enhancers/withParentSize.tsx, packages/vx-responsive/src/enhancers/withScreenSize.tsx
The build is currently broken from #588 which doesn't seem to have triggered the `typescript` build. The way that `debounce` was added in `ParentSize`, `withParentSize`, and `withScreenSize` didn't yield the correct types / was not valid.
=> fix(vx-responsive): fix debounce types

packages/vx-demo/src/sandboxes/vx-pattern/Example.tsx, packages/vx-pattern/src/constants/index.ts, packages/vx-pattern/src/patterns/Lines.tsx, packages/vx-pattern/test/PatternLines.test.tsx
- Add diagobalRightToLeft orientation
Fixes https://github.com/hshoff/vx/issues/723
=> add diagonal right to left pattern

packages/vx-legend/src/legends/Legend/LegendLabel.tsx, packages/vx-legend/src/legends/Legend/LegendShape.tsx, packages/vx-legend/src/legends/Legend/index.tsx, packages/vx-legend/src/shapes/Circle.tsx, packages/vx-legend/src/shapes/Line.tsx, packages/vx-legend/src/types/index.ts, packages/vx-legend/src/util/renderShape.ts, packages/vx-legend/test/Legend.test.tsx
This adds some additional features + hooks to `@vx/legend` which were needed for me to integrate the `Legend` component in the [`XYChart` POC](https://github.com/hshoff/vx/pull/745).
- Add `Line` shape (now have `Line`, `Rect`, and `Circle`)
- Add `legendLabelProps` to `Legend` to support customization of label styles (and integration of the `XYChart` `theme`)
- Pass `item` + `itemIndex` in `RenderShapeProvidedProps`; it currently passes `label` which doesn't help if your logic is based off of the `Legend` `scale` `domain`
=> new(vx-legend): add Line, legendLabelProps, more props in renderShape

packages/vx-axis/src/axis/Axis.tsx
This makes a small update to `@vx/axis` for _non-continuous_ scales. [Continuous scales support `.ticks([count])`](https://github.com/d3/d3-scale#continuous_ticks), but things like band scales do not. 
Currently `Axis` will use `.ticks()` if it exists, and falls back to `.domain()` for scales that don't have it. This is fine except for charts with a very large `domain`, in which case it'd be an improvement to account for `numTicks` if it's passed, to allow filtering to a reasonable number without requiring full specification of `tickValues`. I added that logic here.
**Before**
```tsx
<Axis numTicks={5} scale={bandScale} />
```
**After**
=> new(vx-axis): use numTicks when falling back on scale.domain

packages/vx-responsive/src/components/ParentSize.tsx, packages/vx-responsive/src/enhancers/withParentSize.tsx, packages/vx-responsive/src/enhancers/withScreenSize.tsx
- add leading calls to debounced resize function in all @vx/responsive HOCs and components. This prevents the initial render from blocking, increasing perceived page load speed.
Fixes #753 
The gifs below represent a page refresh. I set the debounceTime to 1000ms for demonstration purposes. The **Before** image shows a 1 second delay before the chart gets rendered on reload. The **After** image immediately renders the component on reload.
**Before:**
**After:**
=> new(vx-responsive): add leading option to resize debounce

packages/vx-demo/package.json, packages/vx-demo/src/pages/docs/tooltip.tsx, packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx, packages/vx-demo/src/sandboxes/vx-tooltip/Example.tsx, packages/vx-demo/src/sandboxes/vx-tooltip/package.json, packages/vx-tooltip/Readme.md, packages/vx-tooltip/package.json, packages/vx-tooltip/src/hooks/useTooltipInPortal.tsx, packages/vx-tooltip/src/index.ts, packages/vx-tooltip/src/tooltips/Tooltip.tsx, packages/vx-tooltip/src/tooltips/TooltipWithBounds.tsx, packages/vx-tooltip/test/useTooltip.test.tsx, packages/vx-tooltip/test/useTooltipInPortal.test.tsx, yarn.lock
This PR is into #755 and 
- adds a new `userTooltipInPortal` hook to addresses the issue of `Portal` not being easy to use by lib consumers. Notes: 
- this adds a new [`react-use-measure`](https://github.com/react-spring/react-use-measure) dependency for the robust bounds logic
- `react-use-measure` relies on `ResizeObserver`. rather than adding the polyfill here like we do in `@vx/responsive`, I'm opting to just expose the `useMeasure` polyfill injection system. So, users can add it themselves to `window` or pass it in directly to the hook. I've noted this in the `Readme`.
- updates the `tooltip` demo added in #755 to use this hook instead of `Portal` + `react-use-measure`
- updates the `vx-tooltip` Readme to include `useTooltipInPortal` and `Portal`
- updates the `barstack` example to …
=> new(vx-tooltip): add useTooltipInPortal

packages/vx-responsive/src/components/ParentSize.tsx
`enableDebounceLeadingCall` is being passed into `div`, causing a warning. Remove it from `restProps` to prevent this issue.
=> Exclude enableDebounceLeadingCall from restProps

packages/vx-scale/src/types/ScaleConfig.ts, packages/vx-stats/src/BoxPlot.tsx, packages/vx-stats/src/ViolinPlot.tsx, packages/vx-stats/src/types.ts, packages/vx-stats/test/BoxPlot.test.tsx, packages/vx-stats/test/ViolinPlot.test.tsx
None
* Export a few more types from `@vx/scale`: 
```
TimeScaleType
ContinuousScaleType
DiscretizingScaleType
DiscreteScaleType
ContinuousDomainScaleType
```
a bit more comment
None
Update `vx/stats` to use types from `vx/scale`
=> feat: add meta scale types and update vx/stats to use types from vx/scale

packages/vx-shape/src/index.ts, packages/vx-shape/src/shapes/BarRounded.tsx, packages/vx-shape/test/BarRounded.test.tsx
fixes: #529 
- [shape] add `<BarRounded />` shape
- [shape] add bar rounded tests
```jsx
// apply 6px radius to top left corner and top right corner
<BarRounded top radius={6} />
// apply 6px radius to top left corner and bottom left corner
<BarRounded left radius={6} />
// apply 6px radius to top right corner and bottom right corner
<BarRounded right radius={6} />
// apply 6px radius to bottom left corner and bottom right corner
<BarRounded bottom radius={6} />
// only apply 6px radius to top left corner
<BarRounded topLeft radius={6} />
// only apply 6px radius to top right corner
<BarRounded topRight radius={6} />
// only apply 6px radius to bottom right corner
<BarRounded bottomRight radius={6} />
// only apply 6px radius to bottom Left corner
<BarRounded bottomLeft radius={6} />
// …
```
=> feat(vx-shape): add BarRounded shape

packages/vx-demo/src/sandboxes/vx-area/Example.tsx, packages/vx-demo/src/sandboxes/vx-axis/Example.tsx, packages/vx-demo/src/sandboxes/vx-barstack/Example.tsx, packages/vx-grid/package.json, packages/vx-grid/src/grids/Grid.tsx, packages/vx-grid/src/grids/GridColumns.tsx, packages/vx-grid/src/grids/GridRows.tsx, packages/vx-grid/src/types.ts
Similar to `@vx/axis` in #773 , `@vx/grid` components now accept D3 Scale as generic type instead of `ScaleInput`. Developers should not expect to specify this generic type as it can be inferred from the passed scale.
=> feat(grid): update scale types in vx/grid

packages/vx-demo/src/sandboxes/vx-legend/Example.tsx, packages/vx-legend/package.json, packages/vx-legend/src/legends/Legend/index.tsx, packages/vx-legend/src/legends/Linear.tsx, packages/vx-legend/src/legends/Ordinal.tsx, packages/vx-legend/src/legends/Quantile.tsx, packages/vx-legend/src/legends/Size.tsx, packages/vx-legend/src/legends/Threshold.tsx, packages/vx-legend/src/types/index.ts, packages/vx-legend/src/util/defaultDomain.ts, packages/vx-legend/src/util/identity.ts, packages/vx-legend/src/util/labelTransformFactory.ts, packages/vx-legend/test/scales.test.tsx
Update generic types for legend components
extract `defaultDomain` helper
Verified that the demo looks exactly the same.
=> feat(legend): update scale types for vx/legend

packages/vx-scale/src/operators/reverse.ts, packages/vx-scale/src/operators/scaleOperator.ts, packages/vx-scale/src/scales/band.ts, packages/vx-scale/src/scales/linear.ts, packages/vx-scale/src/scales/log.ts, packages/vx-scale/src/scales/ordinal.ts, packages/vx-scale/src/scales/point.ts, packages/vx-scale/src/scales/power.ts, packages/vx-scale/src/scales/quantile.ts, packages/vx-scale/src/scales/quantize.ts, packages/vx-scale/src/scales/squareRoot.ts, packages/vx-scale/src/scales/symlog.ts, packages/vx-scale/src/scales/threshold.ts, packages/vx-scale/src/scales/time.ts, packages/vx-scale/src/scales/utc.ts, packages/vx-scale/src/types/ScaleConfig.ts, packages/vx-scale/test/scaleLinear.test.ts, packages/vx-scale/test/scalePoint.test.ts
- Add `reverse` field to scale config. This will reverse the `range`. Useful when the ranges are programmatically supplied to the scale factories such as in `XYChart` and developers want easy way to reverse the dynamic `range`.
=> feat(scale): add reverse operator

packages/vx-text/package.json, packages/vx-text/src/Text.tsx, packages/vx-text/src/util/getStringWidth.ts, packages/vx-text/test/Text.test.tsx, packages/vx-text/test/svgMock.ts, yarn.lock
- Fix complains when `NaN` or invalid values are passed as `x` or `y`
```
Warning: Received NaN for the `%s` attribute. If this is expected, cast the value to a string.%s
```
- Remove `prop-types` from dependency. (no longer used)
- List `lodash.memoize` in dependency of `vx/text` which is smaller than entire `lodash`. 
- Fix issue with jsdom and re-enable unit tests.
=> minor fix to <Text> and re-enable unit tests.

packages/vx-grid/test/Columns.test.tsx, packages/vx-grid/test/Grid.test.tsx, packages/vx-grid/test/GridColumns.test.tsx, packages/vx-grid/test/GridRows.test.tsx, packages/vx-grid/test/Rows.test.tsx, packages/vx-shape/test/utils/D3ShapeFactories.test.ts, packages/vx-shape/test/utils/getBandwidth.test.ts, packages/vx-threshold/test/Threshold.test.tsx, packages/vx-zoom/test/Zoom.test.tsx
- Add tests for `vx/grid`, `vx/zoom`, `vx/threshold`, `vx/shape`
- Boost test coverage from ~49% to 52.891%
=> test: add unit tests

packages/vx-xychart/src/components/series/LineSeries.tsx, packages/vx-xychart/test/DataProvider.test.tsx, packages/vx-xychart/test/DataRegistry.test.ts, packages/vx-xychart/test/LineSeries.test.tsx, packages/vx-xychart/test/ThemeProvider.test.tsx, packages/vx-xychart/test/XYChart.test.tsx, packages/vx-xychart/test/theme.test.tsx
This PR adds tests to #789 (separate for easier review)
=> test(xychart): add DataProvider tests

packages/visx-demo/src/sandboxes/visx-axis/package.json
Currently the `/axis` [sandbox](https://codesandbox.io/s/github/hshoff/vx/tree/master/packages/vx-demo/src/sandboxes/vx-axis) is broken because it doesn't specify the needed `react-spring` dependency, which is a peer dependency of `@vx/react-spring`. This works in the demo site because the demo package includes the dependency.
=> fix(demo/axis): add react-spring dependency

packages/visx-axis/src/axis/Axis.tsx, packages/visx-axis/test/Axis.test.tsx, packages/visx-demo/src/sandboxes/visx-threshold/Example.tsx
Fixes #815 . 
This was a regression introduced in #779 / `0.0.199` where `renderTicks` was factored out to allow for an animated variant. We had to pass `tickLabelProps` to `renderTicks` as an array, one for each tick value. However tick `index` corresponded to the _pre-filtered_ `index`, which does not match the `tickLabelProps` array index when `hideZero=true`. This was most noticeable when there were no `tickLabelProps` for the final tick value (see example below), but in reality all of the styles were off by an index of +1.
A simplification of the problem:
```ts
const tickValues = [0, 1, 2];
const filteredTickValues = [{ value: 1, index: 1 }, { value: 2, index: 2 }]; // hideZero filtered
const tickLabelProps = [tickLabelPropsFn(1, 1), tickLabelPropsFn(2, 2)];
// renderTicks
...
const …
```
=> fix(Axis): tick index = post-filtered index

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-xychart/customTheme.ts, packages/visx-react-spring/src/axis/AnimatedTicks.tsx, packages/visx-xychart/package.json, packages/visx-xychart/src/classes/DataRegistry.ts, packages/visx-xychart/src/components/XYChart.tsx, packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/LineSeries.tsx, packages/visx-xychart/src/enhancers/withRegisteredData.tsx, packages/visx-xychart/src/hooks/useDataRegistry.ts, packages/visx-xychart/src/hooks/useScales.ts, packages/visx-xychart/src/index.ts, packages/visx-xychart/src/providers/DataProvider.tsx, packages/visx-xychart/src/theme/colors.ts, packages/visx-xychart/src/theme/themes/dark.ts, packages/visx-xychart/src/types/data.ts, packages/visx-xychart/src/types/index.ts, packages/visx-xychart/src/types/series.ts, packages/visx-xychart/src/utils/getScaleBandwidth.ts, packages/visx-xychart/src/utils/getScaledValueFactory.ts, packages/visx-xychart/test/BarSeries.test.tsx, packages/visx-xychart/test/Grid.test.tsx, packages/visx-xychart/test/LineSeries.test.tsx, packages/visx-xychart/test/mocks/getDataContext.ts, packages/visx-xychart/test/useDataRegistry.test.tsx, packages/visx-xychart/test/withRegisteredData.test.tsx, yarn.lock
This PR adds `BarSeries` to the `xychart` package and refactors / fixes other issues in the process
- adds `BarSeries` component
- adds `withRegisteredData` HOC which swaps `data`/`xAccessor`/`yAccessor` props for those in the `DataRegistry` in context. This makes `*Series` implementation more straight forward because they should always use values from context so they are in sync with the context scales.
- re-writes `useDataRegistry`
- previously this hook just returned a constant instance of `DataRegistry`, which did not result in the necessary `hook` => `scales` => `context` => `component` updates when the registry was updated.
- the new implementation mirrors the `DataRegistry` API and uses it for its implementation
- improves the light/dark theme colors:
for the `/xychart` demo:
- …
=> new(xychart): add BarSeries

packages/visx-pattern/src/patterns/Lines.tsx
The body of this case clause on a line 26 duplicates the body of this case clause on a line 14. This may be caused by a copy-paste error. If this usage is intentional, consider using fall-through to remove code duplication.
=> Remove code duplication

packages/visx-text/test/Text.test.tsx
Add various missing tests for `@visx/text` to get its coverage to 100% line coverage.
I'm not too seasoned in writing tests, so any constructive criticism/code review is very welcome. This PR is mostly intended to be a first small try at what will hopefully be several coverage-focused PRs.
=> test(text): improve @visx/text coverage

packages/visx-xychart/package.json, packages/visx-xychart/src/components/Tooltip.tsx, packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/LineSeries.tsx, packages/visx-xychart/src/types/event.ts, packages/visx-xychart/src/utils/findNearestDatumSingleDimension.ts, packages/visx-xychart/test/classes/DataRegistry.test.ts, packages/visx-xychart/test/components/Axis.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/Grid.test.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx, packages/visx-xychart/test/components/Tooltip.test.tsx, packages/visx-xychart/test/components/XYChart.test.tsx, packages/visx-xychart/test/enhancers/withRegisteredData.test.tsx, packages/visx-xychart/test/hooks/useDataRegistry.test.tsx, packages/visx-xychart/test/hooks/useEventEmitter.test.tsx, packages/visx-xychart/test/providers/DataProvider.test.tsx, packages/visx-xychart/test/providers/EventEmitterProvider.test.tsx, packages/visx-xychart/test/providers/ThemeProvider.test.tsx, packages/visx-xychart/test/providers/TooltipProvider.test.tsx, packages/visx-xychart/test/utils/findNearestDatum.test.ts
This PR builds on #825 and adds tests for all added components:
- `components/`
- `hooks/`
- `providers/`
- `utils/`
It also organizes the `test/` directory into subfolders to match `src/`
=> test(xychart): add Event + Tooltip tests

README.md
- Add a new "In the wild" link
- Renamed vx > visx
=> Add a new "In the wild" link

packages/visx-shape/src/shapes/Line.tsx, packages/visx-shape/test/Line.test.tsx
Resolves cases where rectilinear lines on non-high DPI screens have an extra semi-opaque pixel added to the width because the line is set between pixels: https://github.com/airbnb/visx/issues/656
- Automatically set `shapeRendering` to `crispEdges` if rectilinear (completely horizontal or vertical).
I think this is the safest setting because using `crispEdges` on non-rectilinear lines may disable anti-aliasing, depending on the user agent.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering
> **crispEdges**
> This value indicates that the user agent shall attempt to emphasize the contrast between clean edges of artwork over rendering speed and geometric precision. To achieve crisp edges, **the user agent might turn off anti-aliasing** for all lines and curves or …
=> Set Line shapeRendering to crispEdges if rectilinear

packages/visx-responsive/src/enhancers/withParentSize.tsx
Adds the ability to set `initialWidth/initialHeight` to `@visx/responsive`s `withParentSize`. Closes #554.
=> Add `initialHeight` and `initialWidth` to `withParentSize`

packages/visx-stats/src/util/computeStats.ts, packages/visx-stats/test/computeStats.test.ts
- Fixes #427 by changing method to calculate `firstQuartile` and `thirdQuartile`
*Test result*
=> fix(computeStats) #427 Exception thrown when firstQuartile and thirdQuartile are equal

packages/visx-responsive/src/components/ParentSize.tsx
This PR
- add a new prop to ParentSize (`disableFor`) to skip when a component doesn't want to be notified by a size change of a certain prop
- also converted the class component to a functional component (hopefully was ok). I did that in a separate commit so you could see what was needed for the feature
Note: I did attempt a test and was unsuccessful, so more than happy to add one provided some direction. I use react-testing-library, so unsure how to simulate resize of an element with enzyme.
~Also, `disableFor` might not be the best name for the prop, so I am open to changing it.~
Close #247
=> new(responsive): add `ignoreDimensions` prop to handle rerenders

packages/visx-tooltip/src/tooltips/Tooltip.tsx, packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx, packages/visx-tooltip/test/TooltipWithBounds.test.tsx
- This PR should close #767 
Please correct me if I did something wrong as I am new to Open Source.
=> fix TooltipWithBounds positioning

packages/visx-stats/src/util/computeStats.ts, packages/visx-stats/test/computeStats.test.ts
=> fix(stats): update min/max in computeStats to handle no outliers

packages/visx-xychart/test/components/Tooltip.test.tsx, packages/visx-xychart/test/providers/TooltipProvider.test.tsx
Builds on #846, adding tests for the new `Tooltip` + `TooltipProvider` functionality (new tests highlighted). Separated for review-ability.
=> test(xychart): add refined Tooltip, TooltipProvider tests

packages/visx-demo/src/sandboxes/visx-xychart/CustomChartBackground.tsx, packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-tooltip/src/hooks/useTooltip.ts, packages/visx-tooltip/src/hooks/useTooltipInPortal.tsx, packages/visx-xychart/package.json, packages/visx-xychart/src/components/Tooltip.tsx, packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/LineSeries.tsx, packages/visx-xychart/src/context/TooltipContext.tsx, packages/visx-xychart/src/providers/TooltipProvider.tsx, packages/visx-xychart/src/types/tooltip.ts, packages/visx-xychart/src/utils/findNearestDatumX.ts, packages/visx-xychart/src/utils/findNearestDatumY.ts, packages/visx-xychart/test/components/Tooltip.test.tsx, packages/visx-xychart/test/providers/TooltipProvider.test.tsx
**TODO**
**`@visx/tooltip`**
allow function signatures for `useTooltip`'s `updateTooltip` + `showTooltip`
```tsx
// before
showTooltip({ tooltipData, ... });
//after 
showTooltip(currentState => ({ _logic based on currentState_ }));
```
**why?** this mirrors how `react` `setState` works, and was needed to implement tooltip data merging properly in `xychart/TooltipProvider`. when `TooltipProvider` tries to merge `tooltipData` when the hook state is updated in quick succession, the hook-provided value may be stale.
<hr />
**`@visx/xychart`**
Builds on #825 and adds more fully-featured `Tooltip` functionality:
- `TooltipProvider` no longer simply returns the `useTooltip` hook state, but adds additional functionality so that `TooltipContext.tooltipData` now includes both the _**globally …
=> new(xychart): refine TooltipContext + Tooltip functionality

packages/visx-network/src/DefaultNode.tsx
Apply the `r` and `fill` props to the `circle` svg element. Please feel free to close if this isn't the direction the library was planning to go, but it seems like one might wish to use the DefaultNode but simply change the radius and colour, especially as it was already being defaulted to a value.
=> fix(network): apply fill and radius props to circle element in DefaultNode

packages/visx-demo/src/sandboxes/visx-area/Example.tsx, packages/visx-demo/src/sandboxes/visx-bars/Example.tsx, packages/visx-demo/src/sandboxes/visx-curve/Example.tsx, packages/visx-demo/src/sandboxes/visx-dots/Example.tsx, packages/visx-demo/src/sandboxes/visx-glyph/Example.tsx, packages/visx-demo/src/sandboxes/visx-heatmap/Example.tsx, packages/visx-demo/src/sandboxes/visx-legend/Example.tsx, packages/visx-demo/src/sandboxes/visx-radar/Example.tsx, packages/visx-demo/src/sandboxes/visx-responsive/Lines.tsx, packages/visx-demo/src/sandboxes/visx-shape-line-radial/Example.tsx, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/Example.tsx, packages/visx-demo/src/sandboxes/visx-stacked-areas/Example.tsx, packages/visx-demo/src/sandboxes/visx-stats/Example.tsx, packages/visx-demo/src/sandboxes/visx-streamgraph/Example.tsx, packages/visx-demo/src/sandboxes/visx-threshold/Example.tsx, packages/visx-demo/src/sandboxes/visx-zoom-i/Example.tsx, packages/visx-scale/package.json, packages/visx-scale/test/createScale.test.ts, packages/visx-scale/test/scaleLog.test.ts, packages/visx-scale/test/scaleSqrt.test.ts, packages/visx-scale/test/scaleSymlog.test.ts, packages/visx-scale/test/scaleTime.test.ts, packages/visx-scale/test/scaleUtc.test.ts, packages/visx-scale/test/updateScale.test.ts, packages/visx-stats/src/BoxPlot.tsx, packages/visx-stats/src/ViolinPlot.tsx, yarn.lock
- bump `@types/d3-scale` 
Fix #855
=> build: bump @types/d3-scale

packages/visx-tooltip/src/tooltips/Tooltip.tsx, packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx, packages/visx-tooltip/test/TooltipWithBounds.test.tsx
This partially reverts #828 (which fixed #767) because the re-implementation of in `Tooltip` to use `transform` instead of `top/left` for positioning breaks cases where users themselves set `style.transform` and would thus be a 💥  breaking change. This was true in the `/areas` demo:
Before
After
**`@visx/tooltip`** 
- adds a new `applyPositionStyle` which applies `position: absolute` so that users who set `unstyled=true` don't have to set this themselves via a CSS selector 🤦 . In a future breaking change this will be the default behavior.
=> fix(tooltip): fallback to left/top positioning, add applyPositionStyle

packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx
-  #466 : change logic to calculate position
=> [TooltipWithBounds] fix : overflowing its parent on small screens

README.md
- Remove some dead link in the readme (some of them might just need to re-deploy 🤔  so if we shouldn't remove them, I can put them back)
- Add one link of mine, the UI of the demo and the tutorial is written in Traditional Chinese and has been shared by the newsletter I'm running
=> refactor: remove dead link and add one link

packages/visx-xychart/src/hooks/useDimensions.ts, packages/visx-xychart/src/providers/DataProvider.tsx, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/mocks/getDataContext.ts, packages/visx-xychart/test/utils/combineBarStackData.test.tsx, packages/visx-xychart/test/utils/findNearestDatum.test.ts
Adds tests for new `BarStack` functionality introduced in the base branch #865.
@kristw
=> test(xychart): add BarStack tests

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-xychart/customTheme.ts, packages/visx-xychart/package.json, packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/BarStack.tsx, packages/visx-xychart/src/components/series/LineSeries.tsx, packages/visx-xychart/src/enhancers/withRegisteredData.tsx, packages/visx-xychart/src/hooks/useDataRegistry.ts, packages/visx-xychart/src/hooks/useDimensions.ts, packages/visx-xychart/src/index.ts, packages/visx-xychart/src/providers/DataProvider.tsx, packages/visx-xychart/src/typeguards/isChildWithProps.ts, packages/visx-xychart/src/types/data.ts, packages/visx-xychart/src/types/event.ts, packages/visx-xychart/src/types/series.ts, packages/visx-xychart/src/utils/combineBarStackData.ts, packages/visx-xychart/src/utils/findNearestStackDatum.ts, packages/visx-xychart/src/utils/getBarStackRegistryData.ts, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/mocks/getDataContext.ts, packages/visx-xychart/test/utils/combineBarStackData.test.tsx, packages/visx-xychart/test/utils/findNearestDatum.test.ts
**TODO**
This PR adds `BarStack` to `@visx/xychart` with an API that wraps `BarSeries` (this was planned in the POC, but could simplify in the future): 
```tsx
<BarStack>
<BarSeries dataKey="sf" data={..} />
<BarSeries dataKey="ny" data={..} />
</BarStack>
```
It also updates the `/xychart` demo
- adds option to render `BarStack` (in the demo this is not compatible with `LineSeries`/`BarSeries` because they share `dataKey`s so controls are disabled accordingly)
- adds option to render _negative values_. this lets me test that negative stacks work correctly (ditto for other Series types)
**Tooltip**
**Negative values**
**Horizontal**
Some notes on the implementation
- The general flow is:
1) collect `props.data` from child `BarSeries`
2) create combined stacked data structure (using child …
=> new(xychart): add BarStack series

packages/visx-xychart/src/components/series/BarGroup.tsx, packages/visx-xychart/src/index.ts, packages/visx-xychart/test/__mocks__/@visx/event.ts, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx, packages/visx-xychart/test/mocks/setupTooltipTest.test.tsx, packages/visx-xychart/test/mocks/setupTooltipTest.tsx
This PR 
- adds tests for `BarGroup` introduced in #870
- adds `__mocks__/@visx/event` + `setupTooltipTest` helper to more easily test `show/hideTooltip` functionality in `*Series`
- adds `mouseover/mouseout` tests to `BarSeries`, `LineSeries`, `BarGroup`, and `BarStack` series components
@kristw
=> test(xychart): add BarGroup + mouseover tests

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/src/components/series/BarGroup.tsx, packages/visx-xychart/src/components/series/BarStack.tsx, packages/visx-xychart/src/index.ts, packages/visx-xychart/test/__mocks__/@visx/event.ts, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx, packages/visx-xychart/test/mocks/setupTooltipTest.tsx
**TODO**
This adds a `BarGroup` series to `@visx/xychart` which supports tooltips, negative values, and horizontal rendering like other `*Series`. It updates the `/xychart` demo to include it.
@kristw @techniq
=> new(xychart): add BarGroup

packages/visx-demo/src/sandboxes/visx-area/Example.tsx
This fixes an issue with the `/areas` demo where it doesn't correctly handle non-zero margins (note: the demo isn't updated with non-zero margins, it just handles them correctly if users tweak them in the sandbox, etc.)
Can play with the updated sandbox [here](https://codesandbox.io/s/github/airbnb/visx/tree/chris--fix-areas-demo/packages/visx-demo/src/sandboxes/visx-area?file=/Example.tsx) (link will break when PR is merged)
**before**
**after**
=> fix(demo/areas): handle non-zero margins

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/src/components/series/AnimatedAreaSeries.tsx, packages/visx-xychart/src/components/series/AreaSeries.tsx, packages/visx-xychart/src/components/series/private/AnimatedPath.tsx, packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx, packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx, packages/visx-xychart/src/index.ts, packages/visx-xychart/src/utils/getScaleBaseline.ts, packages/visx-xychart/test/components/AreaSeries.test.tsx, packages/visx-xychart/test/utils/getScaleBaseline.test.ts
This PR 
- adds `AreaSeries`, `AnimatedAreaSeries`, and `BaseAreaSeries` for a common implementation
- adds tests for new files
- updates the `xychart` demo to group line + bar series separately.
**new demo**
**renders horizontal negative values correctly**
@kristw @techniq
=> new(xychart): add AreaSeries + AnimatedAreaSeries

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/package.json, packages/visx-xychart/src/components/series/private/AnimatedBars.tsx, packages/visx-xychart/src/components/series/private/AnimatedGlyphs.tsx, packages/visx-xychart/src/components/series/private/AnimatedPath.tsx, packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarStack.tsx, packages/visx-xychart/src/components/series/private/BaseGlyphSeries.tsx, packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx, packages/visx-xychart/src/hooks/useScales.ts, packages/visx-xychart/src/providers/DataProvider.tsx, packages/visx-xychart/src/types/data.ts, packages/visx-xychart/src/utils/getScaledValueFactory.ts, packages/visx-xychart/src/utils/isDiscreteScale.ts, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/mocks/getDataContext.ts, yarn.lock
This PR is a mix of improvements + new functionality for `xychart` which are all related by the rabbit hole 🐰 ⚫    I went down trying to fix one problem:
> when transitioning between `horizontal` and `vertical` orientation in the `/xychart` demo, or transitioning between more or fewer data points, `AnimatedPath` would throw due to a cryptic `react-spring` error
The improvements are:
1) does a sweep to handle missing values across all `*Series` and in scale domain calculation
- tested by updating the `/xychart` demo 
2) (✅  fix for above error) updates `AnimatedPath` to handle missing values and a _**changing number of values**_ by using [`d3-interpolate-path`](https://github.com/pbeshai/d3-interpolate-path) for interpolating `path` `d` attributes
- caveats: the only animation case this …
=> new(xychart): handle rendering + tweening missing values

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-xychart/package.json, packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx
This PR 
- exposes the `curve` line interpolation prop in `BaseAreaSeries` + `BaseLineSeries`
- adds `curve` controls to the `/xychart` demo to illustrate + test that interpolation works correctly
This is very addicting to play with
@kristw @techniq
=> new(xychart): expose curve types

packages/visx-demo/package.json
- fix(demo): bump next dep to [9.5.4](https://github.com/vercel/next.js/releases/tag/v9.5.4)
=> fix(demo): bump next dep to 9.5.4

packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/components/GlyphSeries.test.tsx, packages/visx-xychart/test/hooks/useScales.test.tsx, packages/visx-xychart/test/utils/isDiscreteScale.test.ts
This PR adds tests for missing data additions in #898 
@kristw
=> test(xychart): add missing data tests

packages/visx-demo/src/pages/docs/drag.tsx, packages/visx-demo/src/sandboxes/visx-drag-i/Example.tsx, packages/visx-demo/src/sandboxes/visx-drag-ii/Example.tsx, packages/visx-drag/Readme.md, packages/visx-drag/package.json, packages/visx-drag/src/Drag.tsx, packages/visx-drag/src/index.ts, packages/visx-drag/src/useDrag.tsx, packages/visx-drag/src/util/useStateWithCallback.ts, packages/visx-drag/test/raise.test.ts, packages/visx-drag/test/useDrag.test.ts, packages/visx-drag/test/useStateWithCallback.test.ts
This PR 
- adds a `useDrag` hook to `@visx/drag` to complement the render props `<Drag />` component 
- **(I need this for some `@visx/annotation` work)**
- refactors `<Drag />` to use `useDrag`
- bumps `react` `peerDependency` to `^16.8.0-0` to support hooks
- adds support for `PointerEvents` (in addition to `Mouse` and `Touch` events) in drag callbacks
- updates `@visx/demo` `/drag-ii` to use `useDrag` so we have examples of both usages
- updates `/docs/drag` to include `useDrag`
- adds minimal tests for all `@visx/drag` apis
Tested via
- verified `/drag-ii` is still functional
- Updated docs
=> new(drag): add `useDrag` hook

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-xychart/src/components/XYChart.tsx, packages/visx-xychart/test/components/XYChart.test.tsx
This PR adds a usability improvement to `@visx/xychart`, making it optional for package consumers to render `DataProvider` which is arguably an internal implementation detail (note that it is already optional for consumers to render `TooltipProvider` and `EventEmitterProvider`). 
Users can still render `DataProvider` up the parent chain for advanced use cases like linked charts, where it's desirable to share a single `DataContext`.
```tsx
// before (still valid)
() => (
<DataProvider xScale={..} yScale={..} theme={..}>
<XYChart width={..} height={..}>
{...}
</XYChart>
</DataProvider>
)
// after
() => (
<XYChart 
xScale={..} 
yScale={..} 
theme={..}
width={..} 
height={..}
>
{...}
</XYChart>
)
```
**Testing**
=> new(xychart): make DataProvider optional

packages/visx-annotation/Readme.md, packages/visx-annotation/src/components/Label.tsx, packages/visx-demo/src/components/Gallery/AnnotationTile.tsx, packages/visx-demo/src/components/Gallery/index.tsx, packages/visx-demo/src/pages/annotation.tsx, packages/visx-demo/src/pages/docs/annotation.tsx, packages/visx-demo/src/sandboxes/exampleToVisxDependencyLookup.ts, packages/visx-demo/src/sandboxes/visx-annotation/Example.tsx, packages/visx-demo/src/sandboxes/visx-annotation/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-annotation/findNearestDatum.ts, packages/visx-demo/src/sandboxes/visx-annotation/index.tsx, packages/visx-demo/src/sandboxes/visx-annotation/package.json, packages/visx-demo/src/sandboxes/visx-annotation/sandbox-styles.css
This builds on #907 and 
- adds a new `/annotation` demo
- adds an `Annotation` tile to the Gallery + as an example to `/docs/annotation`
- adds the new components to `/docs/annotation`
**TODO**
**Demo**
**Tile**
=> new(demo): add Annotation demo

packages/visx-annotation/package.json, packages/visx-annotation/src/components/Label.tsx, packages/visx-annotation/test/CircleSubject.test.tsx, packages/visx-annotation/test/Connector.test.tsx, packages/visx-annotation/test/EditableAnnotation.test.tsx, packages/visx-annotation/test/Label.test.tsx, packages/visx-annotation/test/LineSubject.test.tsx
Adds tests to `@visx/annotation` components introduced in #907 
=> test(annotation): add tests for new annotation components

packages/visx-annotation/package.json, packages/visx-shape/src/shapes/Arc.tsx, packages/visx-shape/test/Arc.test.tsx, yarn.lock
This supersedes #892 and partially addresses #886, it
- conditionally renders `@visx/shape`s `Arc` when no `data` is specified _**if angles + radii are specified**_
- adds a warning if we render `null` due to missing `data` + angles + radii for better dev experience
As mentioned in both issues above, d3-shape supports two types of usage for `arc()`, it can be configured with constant angles + radii, or passed them (as `data` in `@visx/shape`):
```ts
const arc1 = d3.arc();
arc1({ innerRadius, ... }); // "M0,-100A100,100,0,0,1,100,0L0,0Z"
const arc2 = d3.arc().innerRadius(...)...;
arc2(); // "M0,-100A100,100,0,0,1,100,0L0,0Z"
```
@hshoff @kristw 
cc @oscar-broman @thecodeah
=> fix(shape): conditionally render Arc without data

packages/visx-annotation/src/components/EditableAnnotation.tsx, packages/visx-annotation/test/EditableAnnotation.test.tsx, packages/visx-demo/src/sandboxes/visx-annotation/Example.tsx, packages/visx-demo/src/sandboxes/visx-annotation/ExampleControls.tsx
This PR adds the ability to specify whether one or both of the annotation **subject** or **label** are editable within `EditableAnnotation`, to support different use cases. Updates the demo to show this functionality.
=> new(annotations/EditableAnnotation): add canEditSubject canEditLabel

packages/visx-brush/src/Brush.tsx, packages/visx-demo/src/sandboxes/visx-brush/Example.tsx
@williaster - I know you already have a PR up but I was wondering what you think of this.
cc #577
=> new(brush): expose updateBrush method

packages/visx-annotation/src/components/CircleSubject.tsx, packages/visx-annotation/src/components/Connector.tsx, packages/visx-annotation/src/components/Label.tsx, packages/visx-annotation/src/index.ts, packages/visx-demo/src/sandboxes/visx-annotation/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-demo/src/sandboxes/visx-xychart/customTheme.ts, packages/visx-xychart/package.json, packages/visx-xychart/src/components/Tooltip.tsx, packages/visx-xychart/src/components/XYChart.tsx, packages/visx-xychart/src/components/annotation/AnimatedAnnotation.tsx, packages/visx-xychart/src/components/annotation/Annotation.tsx, packages/visx-xychart/src/components/annotation/AnnotationCircleSubject.tsx, packages/visx-xychart/src/components/annotation/AnnotationConnector.tsx, packages/visx-xychart/src/components/annotation/AnnotationLabel.tsx, packages/visx-xychart/src/components/annotation/AnnotationLineSubject.tsx, packages/visx-xychart/src/components/annotation/private/BaseAnnotation.tsx, packages/visx-xychart/src/index.ts, packages/visx-xychart/src/theme/buildChartTheme.ts, packages/visx-xychart/src/theme/themes/dark.ts, packages/visx-xychart/src/theme/themes/light.ts, packages/visx-xychart/src/types/theme.ts, packages/visx-xychart/test/theme.test.tsx
This PR integrates the new `@visx/annotation`s into `@visx/xychart` and updates the demo. Most of the work is wrappers around the annotation components to provide theme + dimensions from `XYChart`'s context, and I also added an `AnimatedAnnotation` variant so that they can animate upon data changes. 
A quick summary of components added for ease of review
- `private/BaseAnnotation` powers `Annotation` and `AnimatedAnnotation` (mirrors how `AnimatedSeries` work)
- `Annotation`
- `AnimatedAnnotation`
**Animation**
**Editable**
**Theme support**
**Horizontal line annotations**
Noting that you can render an annotation per data point, so this PR fixes #903 
Something like this
```tsx
{data.map((d, i) => (
<AnimatedAnnotation key={i} dataKey="New York" datum={d} dx={0} dy={-10}>
<AnnotationLabel …
```
=> new(xychart): add annotations

packages/visx-demo/src/pages/home.tsx
- none
- Small improvement to the `View Gallery` button located on the Home page. Mouse over cursor should switch to the pointer cursor when the mouse is hovering the button. Please refer to the Next.js documentation about the implemented solution: [If the child is a custom component that wraps an <a> tag
](https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag).
=> fix(demo): fix view demo hover pointer

packages/visx-shape/src/shapes/AreaClosed.tsx
Fixes a small issue I noticed when answering #954 , we don't set `y0` when it is `0` because of the truthy/falsy logic. A work around for now is to set `y0={() => 0}`
cc @puchm
=> fix(shape/AreaClosed): set y0 when it equals zero

packages/visx-xychart/test/components/Annotation.test.tsx, packages/visx-xychart/test/components/AnnotationCircleSubject.test.tsx, packages/visx-xychart/test/components/AnnotationConnector.test.tsx, packages/visx-xychart/test/components/AnnotationLabel.test.tsx, packages/visx-xychart/test/components/AnnotationLineSubject.test.tsx, packages/visx-xychart/test/components/Axis.test.tsx, packages/visx-xychart/test/mocks/getDataContext.ts
This PR adds tests for `@visx/xychart` annotations added in #938 
=> test(xychart): add Annotations tests

packages/visx-xychart/src/hooks/useEventEmitter.ts, packages/visx-xychart/test/hooks/useEventEmitter.test.tsx, packages/visx-xychart/test/hooks/usePointerEventEmitters.test.tsx, packages/visx-xychart/test/hooks/usePointerEventHandlers.test.tsx
This PR adds `PointerEvent` handler tests for the functionality added in #947 :
=> test(xychart): add PointerEvent tests

packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarStack.tsx, packages/visx-xychart/src/components/series/private/BaseGlyphSeries.tsx, packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx, packages/visx-xychart/src/providers/TooltipProvider.tsx
This fixes a couple of issues with `PointerEvent`s in `@visx/xychart`:
- `*Series` subscribe to events from `EventProvider`, but when `source`s were added there was a mismatch between the emitter `source` <> handler `source`, so handlers were not being invoked.
- `TooltipProvider` had an issue where `hideTooltip` was debounced, which meant a call sequence of `showTooltip => hideTooltip => showTooltip` could result in the debounced `hideTooltip` call being invoked _after_ the `showTooltip` call and closing the tooltip. This was fixed by canceling the debounced call in the `showTooltip` handler.
=> fix(xychart): PointerEvent fixes

packages/visx-event/src/getXAndYFromEvent.ts, packages/visx-event/src/typeGuards.ts, packages/visx-event/src/types.ts, packages/visx-event/test/getXandYFromEvent.test.ts
This adds support for `FocusEvent`s to `@visx/event`'s `localPoint` and adds corresponding tests. This is needed to enable tab-able / focusable tooltips in `XYChart` (coming in another PR).
Implementation-wise, since `FocusEvent`s do not have a `clientX/Y` like `MouseEvent`s, I think it makes sense to have the location of the focus event be the center of the `event` `target`'s bounding client rect but am open to other thoughts.
=> new(event): support FocusEvents in localPoint

packages/visx-xychart/src/hooks/useEventEmitter.ts, packages/visx-xychart/src/hooks/useEventHandlers.ts, packages/visx-xychart/src/utils/findNearestGroupDatum.ts, packages/visx-xychart/test/components/AreaSeries.test.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx, packages/visx-xychart/test/hooks/useEventEmitters.test.tsx, packages/visx-xychart/test/hooks/useEventHandlers.test.tsx, packages/visx-xychart/test/utils/findNearestDatum.test.ts
- Adds tests for `FocusEvent` logic added in #959 
- improves logic in `findNearestGroupDatum` to better handle band scale padding (space between bars)
Always nice when tests reveal bugs – `onFocus` handlers weren't being invoked correctly in `useEventHandlers`, so fixed that in the process.
=> test(xychart): add focus/blur handler tests

packages/visx-scale/Readme.md, packages/visx-scale/package.json, packages/visx-scale/src/index.ts, packages/visx-scale/src/operators/unknown.ts, packages/visx-scale/src/scales/radial.ts, packages/visx-scale/src/types/Scale.ts, packages/visx-scale/src/types/ScaleConfig.ts, packages/visx-scale/test/scaleRadial.test.ts, yarn.lock
- Added `Radial Scale` which will help in creating charts like `circular bar plot`. Adding it as a part of #832
=> feat(*): added scale radial

yarn.lock
This just updates `yarn.lock` after a fresh install on `master`. I think it wasn't updated in #946 after the addition of `@testing-library/react-hooks` as dev dependency [here](https://github.com/airbnb/visx/pull/946/files#diff-385f722e4964031d4ad6f8524b8f1ca27fe998a638f67630ca12146f93d6d4feR46).
=> deps: update yarn.lock

packages/visx-xychart/package.json
Closes #884
This updates the `@visx/xychart` config to make it a non-private package, to support publishing for `1.3.0` 🎉   
Note I did publish a pre-release version of this for testing and it was [successful](https://unpkg.com/browse/@visx/xychart@1.3.0-alpha.0/lib/index.js).
=> internal(xychart): make package public

packages/visx-tooltip/Readme.md
-
-
- Corrects an error in the tooltip readme where the prop table for `TooltipWithBounds` lists `offsetTop` as `offsetRight`.
-
-
=> [tooltip] Corrects a documentation error

packages/visx-demo/src/components/Gallery/XYChartTile.tsx, packages/visx-demo/src/components/Gallery/index.tsx, packages/visx-demo/src/components/PackageList.tsx, packages/visx-demo/src/pages/docs/xychart.tsx, packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/package.json, packages/visx-demo/src/sandboxes/visx-xychart/sandbox-styles.css, packages/visx-demo/src/types/index.ts, packages/visx-xychart/README.md, packages/visx-xychart/package.json
This PR
- fleshes out the `README` for `@visx/xychart` to cover most aspects of the API, including some example code snippets
- note I've added `<details />` sections so that the rest of the `/docs/xychart` page with example tile(s) + comprehensive API will be visible without needed to scroll a lot
- adds a `/docs/xychart` page to the demo site, and the `XYChartTile` to the gallery 🎉 
I plan to add a couple more examples but non-gallery codesandboxes will be easier to create when the package is published
=> docs(xychart): add README, add docs/xychart page, add XYChart gallery tile

packages/visx-xychart/README.md, packages/visx-xychart/src/types/series.ts
- [xychart] make EventHandlerParams event optional
This adds a few more codesandbox examples to the `@visx/xychart` README, some demonstrating advanced usage of context providers:
[`Annotation` example](https://codesandbox.io/s/annotations-8npmf?file=/Example.tsx)
<hr />
[`EventEmitterProvider` example](https://codesandbox.io/s/eventemitterprovider-w8jhl?file=/Example.tsx)
<hr />
[`ThemeProvider` + custom theme chart background example](https://codesandbox.io/s/themeprovider-sbdvz?file=/Example.tsx)
<hr />
[`DataProvider/EventEmitterProvider` example of linked tooltips / small multiples](https://codesandbox.io/s/linked-tooltips-7s0jz?file=/Example.tsx), closes #800 
<hr />
[`TooltipProvider` example of programmatic tooltip triggering](https://codesandbox.io/s/programmatic-tooltips-hh7ly?fi …
=> docs(xychart): add advanced usage sandbox examples

packages/visx-xychart/README.md
Fixed missing import in example xychart code.
Closes #975
=> docs(xychart): Add missing import in example (#975)

packages/visx-xychart/src/hooks/useScales.ts
Fixes scale options  not applying in `XYChart`. See https://github.com/airbnb/visx/issues/986
`zero`, `nice`,... options are applied in `createScale`. they were overwritten by setting the `domain` and `range` afterwards. this PR makes sure the `domain` and `range` are set in the `createScale` call directly so that other options are applied in the correct order.
=> Fix scale options in xychart

packages/visx-stats/src/BoxPlot.tsx
- right now there is a check for the values before calling `valueScale` which is supposed to check `undefined` and `null` value but it is filtering out the value `0`
when an inverted linear scale is passed as `valueScale` the value 0 is at the top, not the bottom. And values can be 0 and it is a valid value for `valueScale` function.
=> fix(stats): passing value 0 to valueScale

packages/visx-annotation/src/components/LineSubject.tsx, packages/visx-xychart/src/components/annotation/AnnotationLineSubject.tsx
It was impossible to set `strokeWidth` on `LineSubject`s because the property was never passed through. I also augmented the types with the svg line properties because I was getting type errors when trying to set `strokeDasharray`
=> [annotation] Fix LineSubject types and strokeWidth

packages/visx-annotation/src/components/Label.tsx, packages/visx-demo/src/sandboxes/visx-annotation/ExampleControls.tsx
This fixes a couple of small issues with `Label` from `@visx/annotation`:
- the prop types for `Label` were not correctly generated in `docs/annotation` because the exported component name did not match the file name (this is a limitation of the TS doc type generation, should turn on the lint rule for this)
- `Label`'s `props.backgroundPadding` can be of shape `number | { top?: number, right: ..., bottom: ..., left: ... }`. the logic for the `object` shape was currently broken / this fixes it.
- there was no default for `anchorLineStroke`, so if you set `showAnchorLine={true}` it wasn't visible by default. should have a default so users aren't confused!
- Previously the `/annotation` demo didn't update the annotation position on screen size changes. This results in a broken example in …
=> fix(annotation/Label): fix doc types and padding

packages/visx-xychart/src/components/Tooltip.tsx
Fixes #990. Previously setting `strokeWidth` on `Tooltip` crosshair styles had no effect because the parent `SVG` width/height of `1px` didn't allow it. Fixed by setting `overflow: visible`.
**Before** 
for `vertical/horizontalCrosshairStyle={{ strokeWidth: 8, strokeDasharray: '4,4', stroke: 'yellow' }}`
**After**
for same styles
@hshoff 
cc @Janpot
=> fix(xychart/Tooltip): enable style overflow in crosshairs

packages/visx-scale/src/index.ts, packages/visx-scale/src/utils/scaleCanBeZeroed.ts, packages/visx-scale/test/utils/getTicks.test.ts, packages/visx-scale/test/utils/scaleCanBeZeroed.test.ts, packages/visx-xychart/src/components/XYChart.tsx, packages/visx-xychart/src/hooks/useScales.ts, packages/visx-xychart/src/providers/DataProvider.tsx
This fixes a default behavior issue with `XYChart` scales, where their domains don't include `zero` by default if the scale allows. Including `zero` in the axis domain is generally best practice, and users can still opt out by setting `x/yScaleConfig={{ zero: false }}`. 
**Before** 
This `AreaSeries` has 3 y-values which are all equal and non-zero. It renders like this because the y-domain is `[100, 100]`. This was also reported in #1003 
**After**
With the same data + chart config, the y-domain is now `[0, 100]`. 
Verified it works for negative values, and horizontal orientation.
- Adds a `scaleCanBeZeroed` typeguard util to `@visx/scale` (needed for typing these changes)
- exposes `DataProvider`'s `horizontal` prop in `XYChart` (noticed a small TODO during this work)
@hshoff @kristw 
cc …
=> fix(xychart): include zero in scale domains by default

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/src/components/series/AnimatedBarSeries.tsx, packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/private/AnimatedBars.tsx, packages/visx-xychart/src/components/series/private/AnimatedGlyphs.tsx, packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarStack.tsx, packages/visx-xychart/src/components/series/private/BaseGlyphSeries.tsx, packages/visx-xychart/src/utils/cleanColorString.ts, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/BarStack.test.tsx, packages/visx-xychart/test/components/GlyphSeries.test.tsx, packages/visx-xychart/test/utils/cleanColorString.test.ts
This closes #996 and adds the ability to override color via `colorAccessor` to the following series that should feasibly support per-datum colors (you can already override colors for `Line/AreaSeries`)
- `BarSeries`
- `GlyphSeries`
- `BarStack`
- `BarGroup`
It also
- adds tests for new functionality
- updates the `/xychart` demo to show this functionality (annotated datum gets a pattern color)
- updates `AnimatedGlyph/Bars` to handle `url(#...)` based colors (hadn't tested this before and `react-spring` chokes on them; have a solution that looks okay tho)
@hshoff
=> new(xychart): add colorAccessor to relevant series

CODE_OF_CONDUCT.md
Airbnb has adopted a newer version of the `Contributor Covenant Code of Conduct` than what we reference in `visx`. This updates our `Code of Conduct` to match [Airbnb's root template](https://github.com/airbnb/.github/blob/main/CODE_OF_CONDUCT.md). 
Note that we could simply delete `CODE_OF_CODUCT.md` and `airbnb/.github/CODE_OF_CONDUCT.md` will be the default shown in PRs and issues, but I think it's more clear if we have a file in this repo so it's more prominent.
@hshoff @lencioni
=> (CODE_OF_CODUCT): sync with Airbnb

packages/visx-demo/src/sandboxes/visx-barstack/Example.tsx, packages/visx-demo/src/sandboxes/visx-barstack/package.json
This closes #1016 and improves the logic for tooltip positioning in the `/barstack` demo. That example was refactored to use `TooltipInPortal` when it was added, and the logic wasn't as robust as it should have been. 
**tl;dr** `left/top` should have been in SVG coordinates, but `top` was in viewport coordinates. If anything is rendered above the chart this breaks (as shown in the issue, reproduced with the yellow box below).
**Before**
**After**
@hshoff 
cc @wisyr
=> fix(demo/barstack): improve Tooltip positioning logic

packages/visx-xychart/src/components/axis/BaseAxis.tsx, packages/visx-xychart/src/hooks/useDimensions.ts, packages/visx-xychart/src/hooks/useScales.ts, packages/visx-xychart/src/providers/DataProvider.tsx, packages/visx-xychart/src/utils/combineBarStackData.ts, packages/visx-xychart/src/utils/getScaleBandwidth.ts, packages/visx-xychart/test/components/AreaStack.test.tsx, packages/visx-xychart/test/hooks/useStackedData.test.tsx
This adds tests for `useStackedData` and `AreaStack` added in #1019 
In the process of adding tests I fixed two `DataProvider` issues which can result in invalid scales on initial render:
- an invalid object spread in `useDimensions` could result in `width`, `height`, or `margin` being `undefined` upon initialization, resulting in invalid `scale.range`
- `d3` scales initialized with `domain: []` result in `domain = [NaN, NaN]`, which previously could happen when no data was present in the data registry (now we defer `scale` initialization until data is present)
=> test(xychart): add AreaStack tests

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx
This updates the `/xychart` demo to include `AreaStack` added in #1019 (see images there), and also adds a toggle for `stackOffset` for both `AreaStack` and `BarStack`.
=> new(demo/xychart): add AreaStack, add stackOffset variable for stacks

packages/visx-tooltip/src/hooks/useTooltipInPortal.tsx, packages/visx-xychart/src/components/Tooltip.tsx, packages/visx-xychart/test/components/Tooltip.test.tsx
This PR fixes an issue with `XYChart`'s `Tooltip` described in #983, where `Tooltip` position does **not** correctly update when the chart container changes position due to limitations with `react-use-measure` (note that position **does** update upon page scroll or container resize). It's not obvious how to fix this with `IntersectionObserver`, etc. so I used a relatively simple approach:
- expose `react-use-measure`'s `forceRefreshBounds` function in the `@visx/tooltip` `useTooltipInPortal` hook, which will force update the `Tooltip` container bounds
- invoke ^`forceRefreshBounds` whenever `@visx/xychart`'s `Tooltip` goes from the `unopen => open` state
Closes #983.
**Before**
In this case, the chart animates in from the left so the `Portal` thinks its bounds are way left/off screen …
=> new(tooltip, xychart): force update TooltipInPortal bounds

packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx
Small type fix, title says it all.
=> type(xychart/BaseAreaSeries): add SVGPathElement props to allowed lineProps

packages/visx-axis/src/axis/AxisRenderer.tsx, packages/visx-axis/src/types.ts, packages/visx-axis/test/Axis.test.tsx, packages/visx-axis/test/AxisBottom.test.tsx, packages/visx-axis/test/AxisLeft.test.tsx, packages/visx-axis/test/AxisRight.test.tsx, packages/visx-axis/test/AxisTop.test.tsx, packages/visx-axis/test/Orientation.test.ts, packages/visx-xychart/src/components/axis/BaseAxis.tsx
This updates the signature of `@visx/axis`'s `Axis.props.tickLabelProps`:
```ts
// before
(tickValue, index) => TextProps
// after
(tickValue, index, tickValues) => TextProps
```
This is consistent with how many `d3` accessors work (gives you access to the data point, index, and all data points) as well as matches the signature of [`Axis.props.tickFormat`](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/types.ts#L16). 
I noticed this as a limitation when using `xychart` in an internal app (e.g., if you want to right-align the last tick, but don't know how many ticks you have since `numTicks` is approximate).
=> new(axis): pass all tick values in tickLabelProps signature

packages/visx-demo/src/sandboxes/visx-xychart/Example.tsx, packages/visx-xychart/src/components/Tooltip.tsx
Closes #1054. 
Previously when either `snapTooltipToDataX`/`snapTooltipToDataY` were set on `<Tooltip />`, and a hovered `datum` had a missing value for the corresponding `x`/`y`, we rendered the tooltip at `0,0` and also rendered the tooltip glyphs (circles corresponding to the hovered points) incorrectly.
Also fixes the demo to not show `NaN` values for missing data.
**Before**
**After**
cc @mira-t
=> fix(xychart): improve positioning with missing data

packages/visx-annotation/src/components/Label.tsx, packages/visx-xychart/src/components/annotation/private/BaseAnnotation.tsx
Two small bug fixes for annotations:
- in `@visx/xychart`'s `AnnotationLabel`, make `dataKey` optional (you can either annotate a `datum` from a given series `dataKey`, or pass a custom `datum` in which case `dataKey` is not needed)
- account for `fontFamily` in `@visx/annotation`'s `Label` styles so `Text` uses it in its size calculations
=> fix(xychart, annotation): optional dataKey, label styles

packages/visx-xychart/src/components/series/AnimatedAreaSeries.tsx, packages/visx-xychart/src/components/series/AreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/test/components/AreaSeries.test.tsx
Adds optional `x0Accessor` and `y0Accessor` functions to `AreaSeries` in order to override the scale baseline _per datum_ and support bands. 
Couple notes:
- this currently doesn't account for `x0/y0` values in the scale domain, so implicitly `x0/y0` should be within the `x/y` domain as defined by the `x/yAccessors`.
- these accessors are incompatible with `AreaStack`, `<AreaStack><AreaSeries y0Acessor={..} {...} /> </AreaStack>` will have no effect
Tested 
=> new(xychart/BaseAreaSeries): add x/y0Accessor functions to support bands

packages/visx-demo/src/sandboxes/visx-network/Example.tsx, packages/visx-network/src/Graph.tsx, packages/visx-network/src/Links.tsx, packages/visx-network/src/Nodes.tsx
Fixes #939 
- This changes the type signature of a public-facing prop, so it might be considered a breaking change. However, the type option that's being removed was broken anyway, so this doesn't break any functionality.
- Extended `network` example to show use of `nodeComponent` and `linkComponent`, as well as `top` and `left` props. Adapted from demo in comment of https://github.com/airbnb/visx/issues/939
- Remove string type from `nodeComponent` and `linkComponent` props in `network` package. This type was invalid in spite of being in the type signature. See https://github.com/airbnb/visx/issues/939
=> fix(network): string type in node/linkComponent

packages/visx-demo/.happo.js
Title says it all, there are a couple of demos which visually don't look different but fail happo.
=> build(happo): decrease compare threshold

packages/visx-xychart/src/components/axis/Axis.tsx, packages/visx-xychart/src/types/axis.ts, packages/visx-xychart/src/types/index.ts
Somewhere between a bug fix and a feature, this just updates the `@visx/xychart` `Axis` component to export the `AxisScale` generic type so users don't need to import it from (or even install) `@visx/axis`. It also sets a default for the generic. 
I'd maybe consider it a :bug: in the sense that users can't reference the correct generic without `@visx/axis`.
=> fix(xychart/Axis): export AxisScale type, set default Scale generic

packages/visx-xychart/src/components/Tooltip.tsx, packages/visx-xychart/test/components/Tooltip.test.tsx
This fixes an issue that was missed in #1068 when rendering tooltips for missing data. That PR fixed the case where tooltip circles are not rendered for shared tooltips (multiple series in the tooltip) but not the single-series tooltiip:
**Before**
**After**
@kristw @etr2460
=> fix(xychart/Tooltip): don't render glyph for null data

lerna.json, package.json, yarn.lock
Our last auto-release bumped **all** packages rather than just those which changed. Seeing if a `lerna` version bump fixes this.
=> deps(lerna): bump to 3.22.0

packages/visx-shape/src/shapes/LinePath.tsx, packages/visx-shape/test/LinePath.test.tsx, packages/visx-xychart/src/components/series/private/BaseAreaSeries.tsx, packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx, packages/visx-xychart/test/components/AreaSeries.test.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx
Title says it all. This is a good default behavior in order to make sure that paths of single data points surrounded by `null` values are still visible for `Line` and `AreaSeries`.
~We could also consider setting this as the default in `@visx/shape`, but that's a very popular package so I worry about changing behavior~ 🤔 
EDIT: going to make this change in `@visx/shape` as well as `@visx/xychart` so that all packages / consumers get the fix.
**Before**
**After**
@kristw @etr2460 @hshoff
=> fix(shape, xychart): default LinePath strokeLinecap to round

packages/visx-text/src/index.ts
Currently @visx/text does not export its types. So the following does not work:
`import { TextProps } from '@visx/text';`
This PR adds the exporting of those types.
Ugly work-around until then:
```
import { Text } from '@visx/text';
Parameters<typeof Text>[0]>
```
=> Export types in @visx/text

.github/workflows/push.yml, scripts/performRelease/performLernaRelease.ts
This attempts to fix a couple issues with the github actions push release workflow:
- Specifies a [`--dist-tag`](https://github.com/lerna/lerna/tree/main/commands/publish#--dist-tag-tag) for `lerna` releases. Currently this is always `latest`, which we don't want for alpha releases since it would make the alpha pre-release the default download
- Currently lerna is bumping/releasing **all** packages for each release, even if packages have not changed. I found [this issue](https://github.com/lerna/lerna/issues/2542) with a tip for why this happens, hoping it'll clear it up. 
- **tl;dr** `actions/checkout@v2` only fetches the most recent commits by default, which makes lerna think it needs to publish all packages because it doesn't have the context of previous releases
**Issue before** …
=> internal(workflows/release): add next dist-tag, fix lerna releases

packages/visx-xychart/src/providers/TooltipProvider.tsx, packages/visx-xychart/test/providers/TooltipProvider.test.tsx
This fixes an issue with `NaN` / missing data in the `TooltipProvider` layer. Previously if there were multiple series and one had a missing value, the `Tooltip` would get "stuck" in the missing data series regardless of mouse position. This fixes the logic and adds tests for it.
**Before**
Note: mouse is near the green line, but tooltip is stuck in the missing yellow / SF line.
**After**
Note: mouse is near the green line without missing data, and so is the tooltip
Also note that this is mostly for the overall `nearestDatum` calculation, the nearest datum for each series are still available in the tooltip callback
=> fix(xychart/TooltipProvider): handles NaNs in nearestDatum logic

scripts/performRelease/index.ts, scripts/performRelease/performLernaRelease.ts
This is mostly a PR to trigger a non-`alpha-release`, because of an implication of the release flow I hadn't fully internalized (and rather than committing something random, I added a comment about this implication to the release script 😄 ):
_If there are any PRs since the last tag which have an `alpha-release` label, the release will be an `alpha-release`_ 
(#1107 had this tag and thus the release was an alpha, I've since removed that tag). Here's an example
- `tag @ whatever` created
- Merge PR 1 tagged `alpha-release` + `patch-release` => triggers `alpha patch`
- Merge PR 2 tagged `minor-release` => triggers `alpha minor`
- Remove `alpha-release` from PR 1
- Merge PR 3 tagged `patch-release` => triggers `non-alpha minor` (`minor` required from PR 2)
The alternative I think is to …
=> fix(scripts/performRelease): add comment, fix typo

packages/visx-xychart/src/components/XYChart.tsx
- Fixes https://github.com/airbnb/visx/issues/1077
**Root cause of problem:**
Because xychart doesn't require from consumers wrap himself with all contexts (DataContext, EventEmmiterContext) xychart wraps himself recursively 
https://github.com/airbnb/visx/blob/c21e48bc2307557dc5560cd0f88014769d1ee5ac/packages/visx-xychart/src/components/XYChart.tsx#L153-L166
Which is good but here is a small problem. A bit early in this component we call `useEventHandlers` hook just to add consumer's handlers to our events from our EventEmmitter context emitter 
https://github.com/airbnb/visx/blob/c21e48bc2307557dc5560cd0f88014769d1ee5ac/packages/visx-xychart/src/components/XYChart.tsx#L112-L118
And this is a call tree how I understand that 
- call XYChart for the first time
- call useEventHandlers …
=> fix(xychart): onPointerUp fires twice

packages/visx-brush/src/BaseBrush.tsx, packages/visx-brush/src/BrushHandle.tsx, packages/visx-brush/src/BrushSelection.tsx, packages/visx-drag/src/Drag.tsx
I opened this pr with the same changes as in this one https://github.com/airbnb/visx/pull/864, but with addressing the reviews as well in order to speed things up.
- none
-
-
- #845 
-
=> fix(brush): use PointerEvents instead of MouseEvents 

packages/visx-shape/src/shapes/Polygon.tsx
- The Polygon component can now accept `points` as a field to override its functionality for generating the points based on the `size`, `sides` and `center` props. This allows users of the library to leverage the underlying `polygon`'s flexibility while still making use of visx's styles and utilities.
Note: If a `points` prop is provided to a Polygon component, it's now used by the Polygon rather than being passed to the children.
- I've introduced an additional prop to the `Polygon` component and provided a comment as documentation for it.
=> new(shape/Polygon): add optional 'points' override

CONTRIBUTING.md, package.json
This fixes #1166 , it 
- updates `CONTRIBUTING.MD` to reflect the current scripts used to rebuild a specific package.
- removes the deprecated scripts (which should be fine now that this is documented).
- updates `build:workspace`/`type:workspace` to `workspaces` (with an `s`) since that better reflects the cli `--workspaces=` argument
cc @jakeisnt
=> development(contributing): update docs to rebuild single packages

packages/visx-annotation/src/components/Label.tsx
- Possible breaking change (remove default value of width at label component from @visx/annotation)
- Fixes https://github.com/airbnb/visx/issues/1126
This PR is trying to improve horizontal label positioning at @visx/annotation package.  
Info from https://github.com/airbnb/visx/issues/1126
> Label component from @visx/annotation is trying to calculate right position for text within component according x,y,dx and dy props. But this component does’t take into account real width of text element
TLDR; This fix has added real width measures by `useMeasures` hook and now label component does calculation according real width and paddings value as well.
**Examples**
Problem - Bad label positioning example
https://codesandbox.io/s/bold-antonelli-0v17h?file=/src/pie-chart.tsx
GitHub repo branch …
=> fix(visx/annotation) Improve label positioning, add maxWidth

packages/visx-grid/src/grids/GridColumns.tsx, packages/visx-grid/src/grids/GridRows.tsx, packages/visx-grid/src/utils/getScaleBandwidth.ts, packages/visx-grid/test/utils.test.ts
Fixes #1176. The offset differences between the grid + axis lines was due to `@visx/grid` not accounting for scale `bandwidth` in its offset.
Note the gaps on the side of the chart described in the issue can be controlled by setting the band scale `padding` config to `0`.
**Before**
**After**
cc @jimmy-e
=> fix(grid,xychart): account for scale bandwidth in offsets

packages/visx-annotation/src/components/Label.tsx, packages/visx-text/src/Text.tsx, packages/visx-text/src/types.ts
- Fixes: https://github.com/airbnb/visx/issues/1111
I don't have a clear understanding of this but it seems like `react-use-measure` hook doesn't work well with inner `svg` element within <Text />. 
I consider this problem came from how Firefox treats empty svg elements without width and height within another svg element with height and width - They usually have `width=100%` `height=100%` of parent size even if we put size value from CSS `width: 0px; height: 0px;` explicitly.
In the first render we're getting a really big value of Text svg height, so we're just stuck with this big initial height value here and therefore have this visual behaviour here.
Possible solution in this PR this is replace `innerRef` target from svg `<Text />` root element to `<text />` element which can be …
=> fix(@visx/text) Bad size measurements in Firefox

packages/visx-responsive/src/components/ParentSize.tsx
- If you mount visx within react-testing-library, you might've encountered the error:
```Error: Uncaught [TypeError: resize.cancel is not a function]```
We no longer reference the resize callback if we haven't initialised it yet.
=> fix(responsive): don't call resize.cancel if we never initialised

packages/visx-zoom/src/Zoom.tsx
- can provide optional offsetX and offsetY to `zoom.dragMove` 
- Fixes #1172 / #1169 
I was trying to implement panning after the mouse leaves element/browser bounds. To achieve this I attached the mousemove listener directly to `window`. This resulted in the problem that `mousedown` has a different `event.target` than `mousemove`. As a result, there was a jump whenever it goes from `mousedown` to `mousemove`, resulting in a very bad ux.
I tried every solution I could think of and this is the only way I got it to work. If using `ParentSize`, I set the move offset to be `-x` and `-y` of `parent.ref.getBoundingClientRect`, which is the position of the zoom container relative to window.
~~This doesn't fix my problem 100%, because on the very first mousemove there is still a wrong coordinate. …
=> new(@visx/zoom): adjust drag move to take optional offset

packages/visx-shape/src/shapes/BarGroup.tsx, packages/visx-shape/src/shapes/BarGroupHorizontal.tsx, packages/visx-shape/src/shapes/BarStack.tsx
Fixes #1217 
Fixes an issue with docs for `@visx/shape` where the component exports didn't match the file name, which breaks `react docgen`. I noticed this when there were some API [questions](https://github.com/airbnb/visx/discussions/1207#discussioncomment-734231) about `BarStack` vs `BarStackHorizontal` and couldn't find `BarStack` in the docs 😱 .
From `/docs/shape`
cc @jimmy-e
=> docs(shape): fix docs fror BarGroup, BarGroupHorizontal, and BarStack

packages/visx-scale/package.json, yarn.lock
The latest minor version `3.3.0` of `d3-scale` makes use of utility functions exposed by `d3-time` version `2.1.0` (see: https://github.com/d3/d3-scale/commit/80ff9b202907968ad40ac84fa6347c6768f503c3#commitcomment-50668715)
This makes `d3-scale` `3.3.*` incompatible with `d3-time` `1.x` or even `2.0.0`
=> fix(scale): upgrade d3-time to v2.4 for d3-scale compatibility

packages/visx-xychart/src/components/Tooltip.tsx
This makes a perf improvement for how the `<Tooltip />` works in `@visx/xychart`. It's rendered inside a portal which requires using `react-use-measure` + `ResizeObserver` to update position upon resize and scroll. Currently this is all initialized even if `TooltipContext.tooltipOpen=false` which has two implications:
- on pages with dozens of charts, I've seen the chrome error `ResizeObserver loop limit exceeded` which [isn't critical](https://stackoverflow.com/a/50387233/1933266) but means that `ResizeObserver was not able to deliver all observations within a single animation frame.` which suggests perf isn't great
- if you enable scroll in the `UseMeasureOptions`, the `Tooltip` component (for every chart on the page) will rerender on every scroll which is rough. 
So I simply added a …
=> fix(xychart/Tooltip): bail early when tooltip is closed

packages/visx-shape/src/shapes/Pie.tsx, packages/visx-shape/test/Pie.test.tsx
This is a PR for issue #1193 
- None. Previously the `fill` property supported only `string` value. It still accepts the `string` value (but can also accept a string accessor function). I added a test case for both.
- This PR enables developers to create a Pie chart with custom colors per wedge by just using the `<Pie />` component. Prior, they had to add the `<path>` elements as children of the `<Pie>` in order to dynamic colors.
- The `fill` function can now be a `string` or a function that receives an `PieArcDatum<Datum>` and returns a `string` fill value: `(arc: PieArcDatum<Datum>) => string`.
- Wouldn't call this a bug fix....
- Um... ?
=> new(shape): support dynamic fill directly in Pie

.github/workflows/push.yml
- pushing to `master` in forked repo triggers the `push.yml` github action workflow which include npm release. The release won't be successful (because fork doesn't have npm credentials) but it may bump the versions of `package.json` in the fork.
This PR add condition in the workflow to only run `commit size` and `release` steps from `airbnb/visx` but not from `some-fork/visx`.
=> build: skip release workflow when in forked repo

.github/workflows/push.yml
I recently found out that the happo diffs we often see in PRs is due to **not** running happo on the push github action. Hopefully this fixes is 🤞 
@kristw @trotzig
=> build: run happo on push

packages/visx-react-spring/src/axis/AnimatedAxis.tsx, packages/visx-react-spring/src/axis/AnimatedTicks.tsx, packages/visx-react-spring/test/AnimatedTicks.test.tsx
This adds support for the `tickComponent` prop on `AnimatedAxis`. It was already documented as being supported.
=> feat(animatedaxis): add tickComponent support (#977)

packages/visx-zoom/src/types.ts
- Added my changes from #1180 to types/provided zoom interface
As a side note, I would really appreciate if we can add react@17 to the peer dependencies... Currently 17 is not included. I'm running production on 17 for a while and it works fine. With the latest changes in npm 7, there are many errors when trying to use with react 17 even though it works fine. Which is kinda sad considering most people trying to get into this lib are probably just installing react 17 thinking it doesn't work. If you guys are cool with it I can make PRs for this too.
=> fix(zoom): fix provided zoom interface

packages/visx-demo/package.json, packages/visx-demo/src/components/Gallery/SplitLinePathTile.tsx, packages/visx-demo/src/pages/splitlinepath.tsx, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/Example.tsx, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/generateSinPoints.ts, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/generateSinSegments.ts, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/generateSnakePath.ts, packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/package.json, packages/visx-shape/src/shapes/SplitLinePath.tsx, packages/visx-shape/src/util/getOrCreateMeasurementElement.ts, packages/visx-shape/src/util/getSplitLineSegments.ts, yarn.lock
`SplitLinePath` can split line by multiple algorithms
```tsx
<SplitLinePath segmentation="x" />
```
- `x`: Split based on x-position, assuming x values increase only (`segment[i].x > segment[i-1].x`) or decrease only (`segment[i].x < segment[i-1].x`).
- `y`: Split based on y-position, assuming y values increase only (`segment[i].y > segment[i-1].y`) or decrease only (`segment[i].y < segment[i-1].y`).
- `length`: Assuming the path length between consecutive points are equal. (This was the original algorithm that led to #920.)
Default is set to `x`.
- Update `SplitLinePath` example
- Fix #920
=> feat(shape): add more segmentation for SplitLinePath

packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/hooks/useStackedData.ts, packages/visx-xychart/src/typeguards/isChildWithProps.ts, packages/visx-xychart/src/utils/getChildrenAndGrandchildrenWithProps.ts
Fixes #1040 
Demo with the following (also validated with `BarGroup` and `BarStack`)
```tsx
<AreaStack curve={curve} offset={stackOffset} renderLine={stackOffset !== 'wiggle'}>
<>
<AreaSeries
dataKey="Austin"
data={data}
xAccessor={accessors.x.Austin}
yAccessor={accessors.y.Austin}
fillOpacity={0.4}
/>
<AreaSeries
dataKey="New York"
data={data}
xAccessor={accessors.x['New York']}
yAccessor={accessors.y['New York']}
fillOpacity={0.4}
/>
<AreaSeries
dataKey="San Francisco"
data={data}
xAccessor={accessors.x['San Francisco']}
yAccessor={accessors.y['San Francisco']}
fillOpacity={0.4}
/>
</>
</AreaStack>
```
@kristw 
cc @valtism @tonyneel923
=> fix(xychart): support fragment and array type children of stacks/groups

packages/visx-annotation/package.json, packages/visx-axis/package.json, packages/visx-brush/package.json, packages/visx-chord/package.json, packages/visx-demo/package.json, packages/visx-geo/package.json, packages/visx-glyph/package.json, packages/visx-grid/package.json, packages/visx-group/package.json, packages/visx-heatmap/package.json, packages/visx-hierarchy/package.json, packages/visx-legend/package.json, packages/visx-marker/package.json, packages/visx-network/package.json, packages/visx-pattern/package.json, packages/visx-react-spring/package.json, packages/visx-shape/package.json, packages/visx-stats/package.json, packages/visx-text/package.json, packages/visx-threshold/package.json, packages/visx-tooltip/package.json, packages/visx-voronoi/package.json, packages/visx-xychart/package.json, yarn.lock
noticed warnings during install
```
warning workspace-aggregator-d56295b5-e1bb-4287-aa1e-e72f5692b6cf > docs > @visx/xychart > @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
```
Looks like `classnames@>=2.3` comes with types
=> fix: remove @types/classnames

packages/visx-brush/src/BaseBrush.tsx, packages/visx-brush/src/BrushCorner.tsx, packages/visx-brush/src/BrushHandle.tsx, packages/visx-brush/src/BrushSelection.tsx, packages/visx-drag/src/Drag.tsx
This should fix both 
- https://github.com/airbnb/visx/issues/1283 and
- https://github.com/airbnb/visx/issues/845
Demo of the start/end callback invocations for move/resize/fresh brush:
@gazcn007 @kristw 
cc @JoeVanGundy
=> fix(brush, drag): call start callbacks consistently, support mobile

package.json, packages/visx-demo/src/sandboxes/visx-geo-custom/Example.tsx, packages/visx-demo/src/sandboxes/visx-zoom-i/Example.tsx, packages/visx-zoom/package.json, packages/visx-zoom/src/Zoom.tsx, packages/visx-zoom/src/types.ts, packages/visx-zoom/test/Zoom.test.tsx, yarn.lock
- zoom.containerRef needs to be added to whatever element needs zoom functionality.
- props.transformMatrix was changed to => initialTransformMatrix
- passive/style/className were removed
Zoom now supports mobile pinch.
I consolidated the handlers all into react-use-gesture. A user can opt out by not adding the containerRef so it seems like passive was no longer necessary.
In order for mobile zoom to work fully users must add ```style={{ touchAction: 'none' }}``` to the element in order for the browser to allow js to handle pinch and zoom.
Also I had to use the newest version of use-gesture which is technically in beta because of bugs in version 9. By the author's own admission it is ready for production so I do not see an issue with it.
Discussion which prompted this PR: …
=> new(zoom): add pinch and zoom support

packages/visx-demo/src/sandboxes/visx-geo-albers-usa/Example.tsx
Improve the USA map demo by making use of all 4 colors already defined in the example, rather than only the first two.
=> new(demo/geo-albers/usa): use all 4 colors in the map

packages/visx-text/src/hooks/useText.ts, packages/visx-text/src/types.ts, packages/visx-text/test/Text.test.tsx
- `scaleToFit` now takes the option `'shrink-only'`
=> new(text): Add 'shrink-only' option to 'scaleToFit'

packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/src/components/Tooltip.tsx
Tooltip: Make it possible to distinguish between `nearestDatum` and other series in `renderGlyph`. Also correct the type of `renderGlyph`.
Alternatively we could go for different mechanisms, like passing the `nearestDatum` or `nearestDatumKey` so consumers can compare themselves with the `key` prop, or something like a `type: 'datum' | 'series'`. Also not sure if the naming of `isNearestDatum` is in the spirit of the library. Suggestions welcome.
_edit: Actually, looks like users are already able to achieve this behaviour by using the `TooltipContext` in their custom tooltip glyph, so I'm fine with discarding this PR altogether as well._
=> new(xychart): distinguish nearestDatum in renderGlyph

packages/visx-xychart/src/components/series/BarSeries.tsx, packages/visx-xychart/src/components/series/private/AnimatedBars.tsx, packages/visx-xychart/src/components/series/private/AnimatedPath.tsx, packages/visx-xychart/src/components/series/private/Bars.tsx, packages/visx-xychart/src/components/series/private/BaseBarGroup.tsx, packages/visx-xychart/src/components/series/private/BaseBarSeries.tsx, packages/visx-xychart/src/components/series/private/BaseBarStack.tsx, packages/visx-xychart/src/types/series.ts, packages/visx-xychart/test/components/BarGroup.test.tsx, packages/visx-xychart/test/components/BarSeries.test.tsx, packages/visx-xychart/test/components/BarStack.test.tsx
This builds on #1097, and adds support for rounded `BarSeries` bars in `@visx/xychart` (including as children of `BarGroup`, `BarStack`) through the `radius`/`radiusAll`/`radiusTop`/`radiusBottom`/`radiusLeft`/`radiusRight` props. 
Note that when a `radius` is specified, the bar will be rendered with a `path` instead of a `rect`. I'm debating about **always** rendering a `BarRounded` (even if `radius=0`) for consistency, but I think 
- that would be a breaking change
- `path`s currently cannot animate on entrance `0 => value` (same for lines/areas right now) while `rect`s can. I think this is a limitation of `d3-interpolate-path`.
Closes #1092 and #1093.
Note that if users want full control over rendering bars (discussed in #1092), they can import …
=> new(xychart/BarSeries,BarGroup,BarStack): add support for bar radius

packages/visx-responsive/src/components/ParentSize.tsx, packages/visx-responsive/src/components/ParentSizeModern.tsx
-
-
-
I noticed that `debounceTime` wasn't being respected in ParentSize; the children function was being called many times a second. It ended up being because of the default value for `ignoreDimensions` triggering `useMemo` to reinstantiate the `resize` function, which makes the `useEffect` execute.
I also noticed that `children` always get's called initially with `width` 0. I changed that so a layout does not render until an initial width has been measured. We can remove this part of the PR if need be, but it will require users to add a `width === 0 ? null : renderContent()` type check anytime they use ParentSize to avoid rendering with that "incorrect" initial width.
-
=> fix(responsive): fix shallow equality check on default array value for ParentSize

packages/visx-drag/src/Drag.tsx, packages/visx-drag/src/useDrag.ts, packages/visx-drag/src/util/clampNumber.ts
- Restrict draggable area
- Option to disable snapping to centre of pointer on drag start.
Started from this discussion https://github.com/airbnb/visx/discussions/1365
`snapToCursor` (default behaviour):
https://user-images.githubusercontent.com/1286001/139196553-633e9a86-00b2-4391-bc4d-849489ff8e74.mov
`snapToCursor={false}`:
https://user-images.githubusercontent.com/1286001/139196579-6b81de6f-db42-499f-91f5-8b5d1eb9ebc0.mov
Restricted to chart area (draggable area extends beyond):
https://user-images.githubusercontent.com/1286001/139196632-19d10701-fb10-48e1-8d95-174697701fd7.mov
=> new(drag): add options to restrict <Drag> area and control snapToPointer behaviour

README.md
Removed $ sign from Usage in Readme to make the copying getting started a bit easier
=> Removed $ sign from Usage in Readme

packages/visx-zoom/src/Zoom.tsx
This fixes https://github.com/airbnb/visx/issues/1382 where the `useGesture` refactor of `@visx/zoom` led to 2x scale calls on the final `onWheel` invocation where the gesture is no longer active (see this [line](https://github.com/pmndrs/use-gesture/blob/374b87e043030c0927de9eb609149b3156b5bc5b/packages/core/src/engines/WheelEngine.ts#L29) where the `onWheel` event is emitted on "wheel end" causing it to get triggered one extra time at the end, thanks @nikostri for digging into this! 🙏 ).
Hard to capture the fix in a screenshot, but here you can see that we can detect the gesture is no longer `active` and bail before the second call to avoid the second scale.
@gazcn007 @kristw @hshoff 
cc @ronlv10 @nikostri
=> fix(zoom): avoid 2x scale invocations on wheel end

packages/visx-annotation/src/components/HtmlLabel.tsx, packages/visx-annotation/src/components/Label.tsx, packages/visx-annotation/src/components/LabelAnchorLine.tsx, packages/visx-annotation/src/index.ts, packages/visx-annotation/test/Label.test.tsx, packages/visx-demo/src/pages/docs/annotation.tsx
Add option to pass in an element to render as a label as a child.
Uses <foreignObject> to allow user to pass in an HTML element.
Related to this discussion: https://github.com/airbnb/visx/issues/1173
This has the benefit of letting the element handle text reflow, with
the drawback being that the user need to manage min and max width of
the container element they render.
This approach seems much better imo, favouring composability over
configuration which is much more in line with the philosophy of d3.
=> Annotation label <foreignobject> render

packages/visx-responsive/src/components/ParentSizeModern.tsx, packages/visx-responsive/src/enhancers/withParentSizeModern.tsx, packages/visx-responsive/src/types/index.ts
This supersedes https://github.com/airbnb/visx/pull/1253 and fixes https://github.com/airbnb/visx/pull/1104. It removes the global declaration of `ResizeObserver` which breaks consumers ability to upgrade to `typescript@4` (which has its own `ResizeObserver` types).
Somewhat related to https://github.com/airbnb/visx/pull/1422
@gazcn007 @hshoff @kristw 
cc @MSiddharthReddy @HHK1
=> fix(responsive): remove global ResizeObserver type declaration

packages/visx-annotation/package.json, packages/visx-annotation/test/Label.test.tsx, packages/visx-responsive/package.json, packages/visx-responsive/src/components/ParentSize.tsx, packages/visx-responsive/src/enhancers/withParentSize.tsx, packages/visx-tooltip/package.json, packages/visx-tooltip/test/useTooltipInPortal.test.tsx, packages/visx-xychart/package.json, packages/visx-xychart/test/components/Tooltip.test.tsx, yarn.lock
Fixes #1325 . This refactors our usage of `resize-observer-polyfill` to `@juggle/resize-observer`. The former is no longer maintained and its `ResizeObserver` types will conflict with `typescript@^4`'s own type defs (see https://github.com/que-etc/resize-observer-polyfill/issues/83, thus this fixes one subtask of #1421). 
It makes the changes in the following packages:
- `@visx/responsive`: dependency
- `@visx/annotation`: devDependency
- `@visx/xychart`: devDependency
- `@visx/tooltip`: devDependency (this was actually missing previously)
@gazcn007 @kristw @hshoff
cc @gbiryukov
=> deps: replace resize-observer-polyfill with @juggle/resize-observer

packages/visx-annotation/src/components/HtmlLabel.tsx, packages/visx-annotation/test/HtmlLabel.test.tsx, packages/visx-demo/src/pages/annotation.tsx, packages/visx-demo/src/sandboxes/visx-annotation/Example.tsx, packages/visx-demo/src/sandboxes/visx-annotation/ExampleControls.tsx
These were called out as optional in  #1383 where `HtmlLabel` was added to `@visx/annotation`:
- render `AnnotationLine` **on top of** the html content so its not clipped
- add an optional `containerStyle` prop so that consumers don't have to add an extra wrapper `div` to apply styles (since `HtmlLabel` already renders one).
Adds an `Annotation content type` control to the `/annotation` demo to enable toggling between the `SVG <> HTML` label types.
Adds a simple jest test for the new `HtmlLabel`
@valtism @hshoff @gazcn007 @kristw
=> new(annotation): add HtmlLabel demo, add containterStyle prop

packages/visx-grid/src/grids/GridColumns.tsx, packages/visx-grid/src/grids/GridRows.tsx, packages/visx-grid/src/types.ts, packages/visx-react-spring/src/axis/AnimatedTicks.tsx, packages/visx-react-spring/src/grid/AnimatedGridColumns.tsx, packages/visx-react-spring/src/grid/AnimatedGridRows.tsx
Fixes https://github.com/airbnb/visx/issues/1435 and possibly related to https://github.com/airbnb/visx/issues/1038, https://github.com/airbnb/visx/issues/969 (both closed)
Was able to reproduce @carlsverre 's issue by using a time scale where values only varied on the order of MS – as suggested the value is coerced to a date string which omits the MS and is therefore equal across children
I updated the logic to include the index of the tick (and made the same fix for animated grid columns/rows) and the warning disappeared 😎 
@kristw 
cc @carlsverre @mithi
=> fix(xychart, react-spring): fix duplicate key warning in Axis/Grid

packages/visx-axis/src/types.ts, packages/visx-react-spring/src/axis/AnimatedTicks.tsx, packages/visx-xychart/test/components/Axis.test.tsx
- Allows supplying of tickLineProps for tick lines in AnimatedTicks for parity with Ticks ( #1211 )
- Adjusts LineProps to omit ref for react-spring with the slightly simplifying assumption that we aren't interested in supplying refs manually with regular Ticks either
=> new(react-spring): add tickLineProps to AnimatedTicks

packages/visx-xychart/src/components/series/private/BaseLineSeries.tsx, packages/visx-xychart/test/components/LineSeries.test.tsx
- Add colorAccessor to XYChart LineSeries prop that accepts a function that takes the dataKey and returns a color, replacing the default theme color
resolves #1260
Based on #1005
=> feat(xychart): add colorAccessor to LineSeries

packages/visx-brush/src/BaseBrush.tsx
- Fix vertical resizing of a `Brush` with `useWindowMoveEvents` https://github.com/airbnb/visx/issues/1385
`handleWindowPointerMove` was checking `brushingType === 'bottom'` for both top and bottom, so dragging the top did nothing, and dragging the bottom moved the whole brush (since it was applying the offset to both `y0` and `y1`).
=> fix(brush): vertical brush with useWindowMoveEvents

packages/visx-demo/src/sandboxes/visx-shape-splitlinepath/Example.tsx, packages/visx-shape/src/shapes/SplitLinePath.tsx
Fixes some key warnings I noticed in the splitline demo, one comes from the demo and the other from the component in `@visx/shape`
@kristw
=> fix(demo,shape): fix SplitLinePath key

packages/visx-brush/src/BaseBrush.tsx
- Fix the brush size when the chart resizes in `@visx/brush` based on width and height ratio
Detected in #1436
=> fix(brush): resize brush selection when chart resizes

packages/visx-shape/src/util/getOrCreateMeasurementElement.ts, packages/visx-text/src/util/getStringWidth.ts
Fixes: https://github.com/airbnb/visx/issues/1544
Currently the generated svg used to calculate text and shape size are being read by assitive technologies like screen readers.  This PR hides the generated element so it's now hidden for both screen reader and visual users. 
I tested using the demo app and verified the attribute was being added within Chrome dev tools.
=> fix(text, shape): Hide generated text element from assistive technologies

packages/visx-axis/src/axis/Axis.tsx, packages/visx-axis/src/types.ts, packages/visx-axis/src/utils/getAxisRangePaddingConfig.ts, packages/visx-axis/test/utils/getAxisRangePaddingConfig.test.ts
Hi, everyone! First of all, I want to say, that I'm impressed by the `visx` project, and I'm happy that I discovered it for myself! 
Currently, we are migrating our system from `recharts` to `visx` and found out that there is no way to specify different paddings for the start and the end of the axis. Such ability is present in `recharts` (https://recharts.org/en-US/api/XAxis#padding, https://recharts.org/en-US/api/YAxis#padding), and now we need to work around it using `hideAxisLine` option and our custom line. So it will be nice to have it also in `visx`.  
- add an ability to specify different paddings for the start and the end of the axis
=> feat(axis): add an ability to specify different paddings for the start and the end of the axis

packages/visx-tooltip/src/context/TooltipPositionContext.tsx, packages/visx-tooltip/src/index.ts, packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx
resolves #1329 
- Adds `isFlippedVertically` and `isFlippedHorizontally` flags in tooltip renderer to render different tooltip based on it's position
=> new(tooltip): provide isFlippedVertically and isFlippedHorizontally context

packages/visx-bounds/src/enhancers/withBoundingRects.tsx, packages/visx-tooltip/src/tooltips/Tooltip.tsx, packages/visx-tooltip/src/tooltips/TooltipWithBounds.tsx
This pull request extends the withBoundingRects to use optional refs instead of findDomNode. This should solve the deprecation warning in R18 with strictMode as discussed [here](https://github.com/airbnb/visx/issues/737)
To check the fix please enable `reactStrictMode: true` in `next.config.js` in the demo package. 
This _should_ not introduce any breaking changes. If the res is not passed, withBoundingRects falls back to findDOMNode. I would appreaciate pointers on how to correctly type the `nodeRef` in `TooltipWithBounds.tsx`
=> fix(tooltip, bounds): replace findDOMNode with refs for TooltipWithBounds

scripts/performRelease/createGithubRelease.ts, scripts/performRelease/index.ts
Currently we don't create a formal [Github release](https://github.com/airbnb/visx/releases) when we release new package versions, but ideally they are up-to-date with the changelog.
This adds a script to create a release anytime we update the changelog. Logic is based on the [Github release API docs](https://docs.github.com/en/rest/releases/releases#create-a-release). These are hard to test, so the next PR can be a test-case :)
=> internal(github-actions): add github release script

packages/visx-xychart/README.md
=> docs(xychart): fix typo

packages/visx-demo/src/sandboxes/visx-radar/Example.tsx
- Update example code
Before
After
=> fix(demo/radar):  uneven data elements renders spokes and web out of sync

packages/visx-brush/src/BaseBrush.tsx
Fixes two issues with brush updating on chart resize (see #1282 and #1436):
**1. When moving a brush that has been resized due to chart resize, it regresses to some old sizing**
Fixed by updating brush `start` and `end` when the chart resizes. Previously, only `extent` was updated.
_Repro steps:_
- Use the [Brush example](https://airbnb.io/visx/brush) from the Gallery
- Update the brush so that it is not the default size
- Resize the window width
- Move the brush by dragging
_Current behavior:_
It regresses to some of its old positioning.
_New behavior:_
It moves as expected in its new coordinate space.
**2. Resizing when there is no brush selection, creates a phantom brush near 0,0**
Fixed by only updating brush `start`, `end`, and `extent` if there is a brush (i.e. `extent` coordinates …
=> fix(brush): update brush start/end on window resize

babel.config.js, jest.config.js, packages/visx-scale/package.json, yarn.lock
Closes #1577
Bumping these packages allows for `d3-color` version 3.1.0 or higher to
be installed, fixing this vulnerability:
https://github.com/advisories/GHSA-36jr-mh4h-2g58
- Fix [GHSA-36jr-mh4h-2g58](https://github.com/advisories/GHSA-36jr-mh4h-2g58) vulnerability
=> deps(scale): bump `d3-interpolate` and `d3-scale`

babel.config.js, jest.config.js, packages/visx-scale/package.json, yarn.lock
Reverts airbnb/visx#1578
So save folks some pain with the implications of the ESM-only `d3` dependencies from this change, I'm going to 
- revert this PR
- release a new minor version with the old dependencies
- re-merge this PR
- release a new major version with the new dependencies so people can opt into the ESM changes
will ultimately fix https://github.com/airbnb/visx/issues/1613
cc @jreyes33 @rj-david
=> Revert breaking "deps(scale): bump `d3-interpolate` and `d3-scale`"

.github/workflows/pull_request.yml, packages/visx-annotation/tsconfig.json, packages/visx-demo/tsconfig.json
This adds a couple new checks to our `pull_request` github workflow:
- Ensure `tsconfig` references are up to date. Without nimbus, we don't get this for free anymore. I added a script to do this locally but we should run it in CI too.
- Ensure that the `nextjs` demo site builds without error. https://github.com/airbnb/visx/pull/1578 silently broke this so I'd like to avoid it in the future
=> internal(github/workflows): add tsconfig + demo site build checks

babel.config.js, jest.config.js, package.json, packages/visx-scale/package.json, yarn.lock
Reverts airbnb/visx#1619 which effectively duplicates https://github.com/airbnb/visx/pull/1578 (which bumps these d3 packages to fix a security vulnerability) to release it as a breaking change since the new d3 packages are `ESM`-only.
(re) closes https://github.com/airbnb/visx/issues/1577
depends on
=> Revert "Revert breaking "deps(scale): bump `d3-interpolate` and `d3-scale`""

packages/visx-demo/src/pages/docs/glyph.tsx, packages/visx-demo/src/pages/docs/gradient.tsx, packages/visx-demo/src/pages/docs/shape.tsx, packages/visx-demo/src/pages/docs/xychart.tsx, packages/visx-point/Readme.md
- Fixes missing `@visx/shape` `@visx/glyph` `@visx/gradient` `@visx/xychart` documentation
- Fixes `@visx/point` readme 
- Closes #1647
=> fix(demo): fix missing API documentation

packages/visx-zoom/src/Zoom.tsx
- Prevent wheel interfering with pinch 
Using a macbook, a touchpad pinch gesture will trigger `useGesture`'s pinch event, as desired, but it will also trigger the wheel event. Except in Safari.
With this change, the wheel event handler bails if a pinch gesture is ongoing.
Tested in Firefox, Chrome and Safari on a macbook.
Fixes: #1638
=> fix(zoom): prevent wheel interfering with pinch

packages/visx-tooltip/src/hooks/useTooltipInPortal.tsx
- none
- none per se
- no API changes
- useTooltipInPortal relies on the window scroll position but that is not available on the server. these changes use a common method for detecting server side rendering
-
=> fix(tooltip): handle SSR in useTooltipInPortal

package.json, packages/visx-scale/package.json, packages/visx-scale/src/operators/interpolate.ts, packages/visx-vendor/.gitignore, packages/visx-vendor/Readme.md, packages/visx-vendor/package.json, packages/visx-vendor/scripts/buildVendor/babel.config.js, packages/visx-vendor/scripts/buildVendor/index.ts, packages/visx-vendor/scripts/buildVendor/utils.ts, packages/visx-vendor/test/.eslintrc, packages/visx-vendor/test/d3-array.test.ts, packages/visx-vendor/test/d3-color.test.ts, packages/visx-vendor/test/d3-format.test.ts, packages/visx-vendor/test/d3-interpolate.test.ts, packages/visx-vendor/test/d3-scale.test.ts, packages/visx-vendor/test/d3-time-format.test.ts, packages/visx-vendor/test/d3-time.test.ts, packages/visx-vendor/test/internmap.test.ts, tsconfig.eslint.json, tsconfig.node.json, yarn.lock
This is part of https://github.com/airbnb/visx/pull/1716 and adds the logic for vendoring `esm` and `cjs` versions of ESM-only libs. Again this is heavily based on https://github.com/FormidableLabs/victory/tree/main/packages/victory-vendor
Some key notes for what this package does (some of this is also included in the readme):
- the `package.json` `dependencies` defines which packages are vendored. as noted in https://github.com/airbnb/visx/pull/1717, this is assumed to include **all transitive ESM-only dependencies** (e.g,. ESM-only `d3-scale` depends on another ESM-only `d3-array`) so that we can vendor all of them
- ~dependencies use [`npm` aliases](https://classic.yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add-alias) of the form `d3-array` => `vendor-d3-array@npm:d3-array`~
- ~why? …
=> add @visx/vendor

.github/workflows/pull_request.yml, package.json, packages/visx-vendor/scripts/flagVendorRequirements.ts
After doing some manual work to parse through our `d3-` dependencies and flag those with versions that are ESM-only, or have transitive dependencies which are ESM-only, I decided it's not a great idea to do this manually. 
🫠
We actually don't have a huge number of ESM-only dependencies at the moment, **but** if we were to version bump any number of `d3-` dependencies, we could pick up more ESM-only versions and we're back at having to figure out which are ESM-only. Ideally this detection can be automated.
This PR adds a script which we can use in CI to detect and throw errors if any ESM-only dependencies are detected. If any are detected, they can be added to our new/upcoming `@visx/vendor` package.
Example output
=> vendor: detect ESM-only packages

package.json, scripts/performRelease/performLernaRelease.ts, scripts/performRelease/types.ts, yarn.lock
Trying to fix this https://github.com/airbnb/visx/actions/runs/5406030077
=> github: update @octokit/openapi-types to fix release script

package.json, packages/visx-vendor/package.json, packages/visx-xychart/tsconfig.json
The published contents of `@visx/vendor` are off in the first alpha version. 
It seems like the default behavior should be to include **all** files, so this seems like the generated `lib/`, `esm/`, `vendor-cjs/`, index, and type files weren't published. Will do the following:
- unclear, the github actions logs suggest everything was generated. validating this locally and will merge this with the simple `files` fix if it works locally
=> vendor: add files entry to package.json

packages/visx-xychart/src/providers/TooltipProvider.tsx
-  Cleanup the `debouncedHideTooltip` function in the `TooltipProvider` component when it unmounts.
closes: #1726
=> fix(xychart): Cleanup async function in TooltipProvider

packages/visx-axis/src/axis/Axis.tsx, packages/visx-axis/src/types.ts, packages/visx-axis/test/Axis.test.tsx
- Expose the innerRef prop on all the various the `Axis` components. This makes it possible to get the dimensions of the of the `Axis` without using `getStringWidth` on all the tick values.
closes: #1086
=> feat(axis): Expose innerRef prop on the various Axis components

packages/visx-axis/src/axis/AxisRenderer.tsx
Resolve circular dependencies in [packages/visx-axis/src/axis](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis). 
Neighboring files ([Axis.tsx#10](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis/Axis.tsx#L10), [AxisBottom.tsx#4](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis/AxisBottom.tsx#L4), [AxisLeft.tsx#4](https://github.com/airbnb/visx/blob/master/packages/visx-axis/src/axis/AxisLeft.tsx#L4) etc.) import the `Orientation` constant from `../constants/orientation`, but for some reason `AxisRenderer.tsx` import `Orientation` from the public API (`../index.ts`). This is the cause of circular dependencies.
Before (webpack's [circular-dependency-plugin](https://www.npmjs.com/package/circular-dependency-plugin)):
``` …
```
=> visx-axis AxisRenderer.tsx: resolve circular dependency

packages/visx-react-spring/src/grid/AnimatedGridColumns.tsx, packages/visx-react-spring/src/grid/AnimatedGridRows.tsx
- Correctly pass through `offset` in AnimatedGridRows
- Correctly pass through `offset` in AnimatedGridColumns
=> fix: correctly pass through offset from AnimatedGridRows/Columns

packages/visx-brush/src/BaseBrush.tsx
- Fixed issue [#1465](https://github.com/airbnb/visx/issues/1465)
> React warns 'An update was scheduled from inside an update function' in case we set **resetOnEnd = true** or if we call the **reset()** method imperatively.
In short we call **setState** method inside of updater function of another **setState**
```typescript
setState(() => {
// ...
//...
setState(() => {
//...
})
})
```
In the [BaseBrush.ts](https://github.com/airbnb/visx/blob/aa8f837c0b69a6de64c9ecaff786cf63e4708437/packages/visx-brush/src/BaseBrush.tsx)
1) **updateBrush()** calls the **setState()** method
2) **handleDragEnd()** or **handleWindowPointerUp()** call the **updateBrush()** with updater function contains **reset()**
3) **reset()** also calls **updateBrush()**
1) Move brush "idle" state object to …
=> fix(brush): fix issue 'update was scheduled' warning on resetOnEnd #1465

packages/visx-demo/src/components/Gallery/DragITile.tsx
- Fixes typo in `DragITile` description. There is an extra trailing ">" character.
=> fix: typo in DragITile description

packages/visx-demo/src/components/Gallery/RadialBarsTile.tsx, packages/visx-demo/src/components/Gallery/index.tsx, packages/visx-demo/src/pages/radial-bars.tsx, packages/visx-demo/src/sandboxes/visx-radial-bars/Example.tsx, packages/visx-demo/src/sandboxes/visx-radial-bars/index.tsx, packages/visx-demo/src/sandboxes/visx-radial-bars/package.json, packages/visx-demo/src/sandboxes/visx-radial-bars/sandbox-styles.css
Added a simple radial bar chart demo to the gallery for #832.
Happy to hear any feedback and make changes if necessary. I tried to follow the other demos in the gallery as a guide.
=> feat(demo): add radial bars demo using Arc

packages/visx-demo/src/sandboxes/visx-radial-bars/Example.tsx
- Fixed the import for `@visx/mock-data` in the radial bars demo (#1785) which was crashing when viewed in CodeSandbox. I must've used the autocompleted import from my editor and didn't notice. 
- Added horizontal margin so the bar labels are visible for narrow widths too.
- Also made the gradient id more unique as per the review comment: https://github.com/airbnb/visx/pull/1785#discussion_r1448263424
=> fix: radial bars demo import in CodeSandbox

packages/visx-axis/src/axis/AxisRenderer.tsx
- Enables passing of partial labelProps per the docs
Closes #1790
=> fix(axis): include defaultTextProps in Axis labelProps

README.md
-  Remove two broken demo links from 'In the wild' section
=> docs: remove broken links from 'In the wild'

packages/visx-axis/src/axis/AxisRenderer.tsx, packages/visx-axis/src/types.ts
None.
Additional flexibility when using `Axis`.
`shapeRendering` can now be configured for `Axis` lines.
Not sure if this was introduced by #840. I haven't dug much into it. But I have noticed that on Windows, Firefox, when using the `Axis` with a `scaleLinear` and dashed pattern, some vertical lines looked very thick while others very thin.
After playing around in the HTML, I figured the culprit was the "smart" `shapeRendering`. So I want a way to disable it without resorting to ugly hacks.
The `CommonProps` for `visx-types` have changed.
=> new(axis): add shapeRendering prop to Axis

packages/visx-axis/src/axis/AxisRenderer.tsx, packages/visx-axis/src/types.ts
Reverts airbnb/visx#1739 . this actually made the tick line rendering **more blurry** as it overrode https://github.com/airbnb/visx/pull/840
by removing this, you can still set it via `axisLineClassName`, and you can set it for tick lines via `tickLineProps`
cc @Lonami
=> Revert "new(axis): add shapeRendering prop to Axis"

packages/visx-responsive/src/index.ts
#1783 introduced a bug where bundlers were treating type exports as non-type exports - I'm quite surprised that happened but also I didn't know that `export type` was introduced in 3.8, which is great because that makes it an easy fix.
=> fix: explicit type exports in @visx/responsive

packages/visx-legend/src/legends/Threshold.tsx, packages/visx-legend/test/LegendThreshold.test.tsx
- Changed how the labelTransform get an upper and lower value to get the color out of the threshold scale.  
This should guarantee a larger or smaller number than the upper and lower bounds is passed into the scale function to retrieve the correct color.  
- Remove the logical OR from the scale() input. It should now never be undefined and this was the cause of a bug if the the lower bound was 1 making `value` falsy.  
- Because I can't help but make eslint happy, added a type to the domain.  
Issue #1828
=> Fix LegendThreshold

packages/visx-brush/src/BaseBrush.tsx, packages/visx-brush/src/utils.ts
**How to induce?** 
resize the brush window by dragging and releasing one handle quickly, or quickly drag the brush window and release (harder to induce this way)
**Impact?**
Handle ends up quite far away from the mouse pointer's location. Sometimes the location of _both_ handles will be updated, resulting in a drastic resize of the brush window.
Two relevant issue have been linked below- I believe this PR should resolve both of them!
[Issue 1](https://github.com/airbnb/visx/issues/1804)
[Issue 2](https://github.com/airbnb/visx/issues/1736)
**Root cause** 
`mouseup` action is _supposed_ to disable subsequent dragging of the handle upon `mousemove`. This is achieved by updating the brush's state. However, when moving quickly, `mousemove` actions can trigger `handleWindowPointerMove` …
=> brush: fix brush jumping around after mouseup

packages/visx-demo/src/sandboxes/visx-xychart/ExampleControls.tsx, packages/visx-xychart/src/components/series/private/AnimatedPath.tsx
- Improves performance drastically when hovering over XYChart with tooltips on. This is achieved by no longer re-rendering unless any of the props change, as renders are quite expensive with `d3-interpolate-path`
- Added an gallery control to select data size for testing
This could also be achieved by doing a comparison for `previousD.current === d` - let me know if that's preferable over using React `memo`.
=> feat(xychart): improve performance when hovering with tooltip

scripts/updateTsReferences.ts
- Fix typescript error when accessing `error` in `scripts/updateTsReferences.ts`, this fixes running `yarn type:update-refs` 
---
Targets #1894 by @williaster
=> Fix typescript error when accessing `error` in `scripts/updateTsReferences.ts`
